import type { RotationalContent } from '@/lib/dailyContentTypes';

export const de: RotationalContent = {
  tips: [
    "Höre zu, um zu verstehen, nicht um zu antworten. Eine kurze Pause, bevor du reagierst, zeigt deinem Gegenüber, dass seine Worte wirklich angekommen sind – und diese kleine Gewohnheit vertieft mit der Zeit das Vertrauen.",
    "Bedanke dich für die alltäglichen Dinge. Wenn du den gekochten Kaffee oder den abgewaschenen Geschirrstapel bemerkst, weißt du deinen Partner spüren zu lassen, dass seine tägliche Mühe nie unbemerkt bleibt.",
    "Wenn ein Konflikt aufkommt, geht das Problem gemeinsam an, statt euch gegenseitig anzugreifen. Ihr seid ein Team, das einer Sache gegenübersteht – keine Gegner, die einen Punkt gewinnen wollen.",
    "Plant ungehetzte gemeinsame Zeit ein, und sei es nur zwanzig Minuten. Nähe entsteht selten in den Lücken; sie wächst, wenn ihr bewusst Raum dafür schafft.",
    "Frage deinen Partner, wie er getröstet werden möchte. Manche wollen Lösungen, andere eine Umarmung und Stille – und falsch zu raten kann sich wie Distanz anfühlen.",
    "Versöhne dich schnell nach einer Meinungsverschiedenheit. Ein aufrichtiges Nachfragen, sobald sich die Gemüter beruhigt haben, zählt weit mehr, als so zu tun, als hätte es die Reibung nie gegeben.",
    "Neugier hält die Liebe lebendig. Stelle deinem langjährigen Partner immer wieder neue Fragen, denn Menschen verändern sich leise, und die spannendsten entfalten sich noch immer.",
    "Sprich deine Wertschätzung laut aus, nicht nur in Gedanken. Unausgesprochene Dankbarkeit wärmt nur dich, während ausgesprochene Dankbarkeit den Menschen wärmt, den du liebst.",
    "Schütze eure Beziehung vor Verachtung. Augenrollen und Sarkasmus zersetzen die Verbindung schneller als fast alles andere – also wähle Respekt, selbst wenn du frustriert bist.",
    "Lass kleine Annäherungsversuche zählen. Wenn dein Partner etwas Kleines teilt, ist es der stille Kitt dauerhafter Liebe, dich ihm aufmerksam zuzuwenden.",
    "Entschuldige dich ohne ein „aber“ anzuhängen. Eine saubere Entschuldigung steht voll zu deinem Anteil, während eine bedingte den Vorwurf leise wieder über den Tisch zurückschiebt.",
    "Bewahrt euch ein paar Rituale, die nur euch gehören. Ein Spaziergang am Sonntag oder der gemeinsame Morgenkaffee schafft einen festen Rhythmus, der ein hektisches Leben miteinander verankert.",
    "Unterstelle gute Absicht, bevor du vom Schlimmsten ausgehst. Die meisten verletzenden Momente entstehen aus Ungeschick oder Stress, nicht weil ein Partner dir heimlich schaden möchte.",
    "Sprecht früh und oft über Geld. Sich über Ausgaben, Sparen und Ziele einig zu sein, verhindert den stillen Groll, den Finanzen sonst leise erzeugen können.",
    "Lass deinen Partner anders sein als du. Kompatibilität ist nicht Gleichheit; sie sind zwei verschiedene Menschen, die sich entscheiden, die jeweils eigene innere Welt des anderen zu achten.",
    "Bemerke, was dein Partner gerade trägt. Ein behutsames „du wirkst müde, lass mich das Abendessen übernehmen“ kann lauter Ich liebe dich sagen als Worte.",
    "Bewahrt euch etwas Eigenständigkeit innerhalb der Zweisamkeit. Eigene Freundschaften und Leidenschaften zu pflegen macht dich zu einem interessanteren, lebendigeren Partner, zu dem man gern nach Hause kommt.",
    "Lobe in der Öffentlichkeit, kläre Probleme im Privaten. Deinen Partner vor anderen aufzubauen und Reibung leise zu klären schützt sowohl Stolz als auch Vertrauen.",
    "Ersetze „du immer“ und „du nie“ durch „ich fühle“. Aus deinem Erleben zu sprechen lädt zum Verständnis ein, während pauschale Anschuldigungen Abwehr hervorrufen.",
    "Berührung zählt auch, wenn nichts im Argen liegt. Eine Hand auf der Schulter oder eine kurze Umarmung lässt den Körper weiter spüren, dass er geliebt wird.",
    "Wähle deinen Partner an schweren Tagen neu. Liebe ist nicht nur der Funke, in den du gefallen bist, sondern die Entscheidung, die du erneuerst, wenn es schwer wird.",
    "Interessiere dich für seine Welt. Echte Fragen zur Arbeit, zu Sorgen und Träumen deines Partners sagen ihm, dass sein Leben dir wirklich wichtig ist.",
    "Führe keine Buchhaltung. Großzügigkeit, die zurückgezahlt werden soll, ist ein Geschäft; Liebe gedeiht, wenn du frei gibst und darauf vertraust, dass sich die Waage ausgleicht.",
    "Benenne deine Bedürfnisse klar. Dein Partner kann deine Gedanken nicht lesen, und leise zu hoffen, dass er sie errät, endet oft in Enttäuschung für euch beide.",
    "Lacht oft miteinander. Gemeinsamer Humor löst Spannung, schafft Nähe und erinnert dich daran, dass der Mensch an deiner Seite auch dein liebster Begleiter ist.",
    "Sei beim Wiedersehen ganz präsent. Deinen Partner herzlich zu begrüßen, wenn ihr euch wieder seht – Handy weg, Blick hoch – gibt dem Abend den Ton vor.",
    "Vergib das Kleine schnell. An kleinen Kränkungen festzuhalten baut Stein um Stein eine Mauer, bis ihr einander nicht mehr erreichen könnt.",
    "Feiere die Erfolge deines Partners wie deine eigenen. Echte Freude über seinen Erfolg, ohne Neid, ist eine der tiefsten Formen der Liebe.",
    "Frage nach, bevor du annimmst, ihr hättet euch entfremdet. Ein einfaches „wie läuft es gerade bei uns?“ offenbart oft eine Nähe, die Distanz nur zu bedrohen schien.",
    "Achtet eure Grenzen, ohne sie persönlich zu nehmen. Eine Grenze ist eine Information über die Bedürfnisse deines Partners, keine Zurückweisung deiner Person.",
    "Macht in Streitgesprächen Versöhnungsangebote, etwa einen sanfteren Ton oder einen kleinen Scherz. Diese gereichten Friedensangebote anzunehmen verhindert, dass Meinungsverschiedenheiten eskalieren.",
    "Sei für die langweilige Organisation da. Hausarbeit, Besorgungen und Planung fair zu teilen ist eine der am meisten unterschätzten Liebessprachen überhaupt.",
    "Sei ehrlich bei den kleinen Dingen. Vertrauen entsteht in winzigen Momenten der Wahrheit, und kleine Lügen lehren einen Partner leise, an dir zu zweifeln.",
    "Frage „was brauchst du gerade von mir?“. Diese eine Frage durchschneidet das Rätselraten und gibt deinem Partner genau die Unterstützung, die er sich wünscht.",
    "Flirte weiter mit deinem langjährigen Partner. Ein Augenzwinkern, ein Kompliment, ein gestohlener Kuss erinnert ihn daran, dass er noch begehrt wird, nicht nur verlässlich ist.",
    "Lass ihn einen schlechten Tag haben. Du musst nicht jede Stimmung reparieren; manchmal ist das Liebevollste, einfach nahe zu bleiben, während sie vorübergeht.",
    "Sprecht über eure Beziehung, wenn es gut läuft, nicht nur wenn etwas kaputt ist. Pflegende Gespräche verhindern die größeren Krisengespräche.",
    "Ehre die Beziehung vor anderen. Warm über deinen Partner zu sprechen, wenn er nicht da ist, schützt die Partnerschaft vor Zersetzung von außen.",
    "Erkenne deinen eigenen Anteil an wiederkehrenden Streitigkeiten. Sich zu fragen „was sind hier meine 10 Prozent?“ verwandelt einen Stillstand in eine Chance, gemeinsam zu wachsen.",
    "Trefft Entscheidungen miteinander, nicht füreinander. Selbst kleine Absprachen vermitteln Respekt und erinnern deinen Partner daran, dass ihr wirklich ein Team seid.",
    "Beruhige dich, bevor du große Gespräche führst. Ein schwieriges Gespräch ruhig statt überflutet anzugehen hilft dir, das zu sagen, was du meinst, statt das, was verletzt.",
    "Begrüße das Wachstum deines Partners, auch wenn es unbequem ist. Jemanden zu lieben heißt, für den Menschen zu sein, der er wird, nicht nur für den, den du kennengelernt hast.",
    "Überrasche ihn mit Mühe, nicht nur mit Geschenken. Einen liebevollen Abend zu planen oder sein Lieblingsrezept zu lernen zeigt eine Liebe, die kein Geld kaufen kann.",
    "Sei der sichere Ort, in den er ausatmet. Wenn das Zuhause sich wie der eine Ort anfühlt, an dem er ganz entspannen kann, wird eure Beziehung zu seiner Zuflucht.",
    "Frage nach den Höhen und Tiefen seines Tages. Dieses einfache Ritual schafft täglich ein Fenster in das innere Gefühlswetter deines Partners.",
    "Bestätige Gefühle, auch wenn du die Logik nicht teilst. „Es ergibt Sinn, dass du dich so fühlst“ beruhigt Stürme weit besser, als Fakten zu korrigieren.",
    "Halte Versprechen klein genug, um sie zu halten. Verlässlichkeit, die auf bescheidenen, eingelösten Zusagen beruht, schafft mehr Vertrauen als große Schwüre, die du kaum erfüllen kannst.",
    "Übernimm Verantwortung für dein eigenes Glück. Ein Partner kann deine Freude bereichern, aber von ihm zu erwarten, ihre einzige Quelle zu sein, ist eine schwere Last.",
    "Greift hin und wieder eure gemeinsamen Träume auf. Über die Zukunft zu sprechen, die ihr aufbaut, rückt die tägliche Reibung in den richtigen Rahmen und hält die Motivation lebendig.",
    "Meldet euch an langen Tagen der Trennung kurz. Eine schnelle Mittagsnachricht, dass du an ihn denkst, hält den Faden der Verbindung gespannt.",
    "Lass das Rechthaben los, um verbunden zu bleiben. Einen Streit zu gewinnen und dabei die Wärme deines Partners zu verlieren ist selten ein Sieg, den es sich zu beanspruchen lohnt.",
    "Erkenne die Liebessprachen, die ihr jeweils sprecht. Wenn du Worte schenkst, er sich aber Zeit wünscht, verfehlt deine Mühe ihn vielleicht um Haaresbreite.",
    "Schafft beim Abendessen eine handyfreie Zone. Ungestörte Mahlzeiten sind die tägliche Chance, den Menschen gegenüber wirklich zu sehen und zu hören.",
    "Gehe behutsam mit den Unsicherheiten deines Partners um. Die Stellen, an denen er sich verletzlich fühlt, verdienen deine Fürsorge, nicht deinen Spott, selbst in verspielten Momenten.",
    "Schafft Raum für „Ich-Zeit“ und „Wir-Zeit“. Einsamkeit und Zweisamkeit zu würdigen bewahrt die Beziehung davor, sich wie ein Gefängnis oder wie Distanz anzufühlen.",
    "Drücke Verlangen und Bewunderung offen aus. Deinem Partner konkret zu sagen, was du an ihm anziehend findest, wird selten alt und nie unbemerkt.",
    "Begegne Groll, solange er klein ist. Eine kleine Frustration freundlich zu benennen verhindert, dass sie sich leise zu einem Groll verhärtet, den du später nicht erklären kannst.",
    "Zeige Interesse an seinen Freunden und seiner Familie. Die Menschen anzunehmen, die dein Partner liebt, signalisiert, dass du dich für sein ganzes Leben einsetzt, nicht nur für ihn.",
    "Werde langsamer, wenn du eine Entfremdung spürst. Statt dich weiter zurückzuziehen, lehne dich sanft hinein und frage, was deinem Partner durch den Kopf geht.",
    "Bewahre die Geheimnisse und Geschichten deines Partners sicher. Jemand zu sein, dem er sich ganz anvertrauen kann, ist das Fundament echter emotionaler Nähe.",
    "Achte beim frühen Daten darauf, wie jemand Menschen behandelt, die nichts für ihn tun können. Freundlichkeit zu Kellnern und Fremden offenbart den wahren Charakter.",
    "Beeile dich nicht, alles zu definieren. Eine frühe Verbindung atmen zu lassen erlaubt dir zu sehen, wer jemand wirklich ist, bevor Etiketten Druck oder Annahmen schaffen.",
    "Passe dich seinem Tempo an, ohne dich zu verlieren. Gesunde neue Liebe balanciert Begeisterung mit Geduld und lässt Vertrauen natürlich wachsen, statt Intensität zu erzwingen.",
    "Suche jemanden, dessen gewöhnliche Tage sich gut anfühlen, nicht nur dessen aufregende. Alltagskompatibilität überdauert dramatische Chemie jedes Mal.",
    "Achte darauf, wie ein Date mit Enttäuschung umgeht. Wie jemand auf einen kleinen Rückschlag reagiert, gibt einen Vorgeschmack darauf, wie er größere meistern wird.",
    "Bewahrt in der Fernbeziehung ein gemeinsames Gefühl von normalem Alltag. Zusammen eine Serie zu schauen oder per Video Besorgungen zu erledigen hält die Nähe lebendig.",
    "Plant den nächsten Besuch, bevor das aktuelle Auf-Wiedersehen kommt. Ein Datum im Kalender gibt Fernbeziehungen etwas Konkretes, woran sie sich festhalten können.",
    "Kommuniziert großzügig über die Distanz hinweg. Entfernung macht Annahmen gefährlich, also teile reichlich Kontext und Zuspruch, statt Stille der Fehldeutung zu überlassen.",
    "Vertrauen ist die Währung der Distanz. Ohne tägliche Nähe wird die Entscheidung, das Beste im anderen zu glauben, zum Rückgrat der Beziehung.",
    "Übe Selbstliebe, damit du Fülle mitbringst, nicht Bedürftigkeit. Die eigene Gesellschaft zu mögen macht dich zu einem Partner, der die Liebe wählt, statt sich an sie zu klammern.",
    "Sprich mit dir selbst so, wie du mit deinem Liebsten sprechen würdest. Harte innere Stimmen sickern in Beziehungen, während Selbstfreundlichkeit Wärme nach außen fließen lässt.",
    "Heile deine eigenen alten Wunden, statt sie einem Partner aufzubürden. Eine liebevolle Beziehung kann dein Wachstum begleiten, aber sie kann deine eigene Arbeit nicht ersetzen.",
    "Kenne deinen Wert, bevor du über Liebe verhandelst. Menschen, die ihren Wert verstehen, geben sich selten damit zufrieden, jemandes Nebensache oder Ersatzplan zu sein.",
    "Halte unangenehme Gefühle aus, statt sie abzuladen. Zu benennen, was du fühlst, bevor du reagierst, bewahrt deinen Partner davor, deine unverarbeiteten Stürme aufzunehmen.",
    "Entwickle die Fähigkeit, unter Stress reguliert zu bleiben. Deine ruhige Präsenz in den schweren Momenten deines Partners ist eine stille, kraftvolle Form der Liebe.",
    "Lies das Gefühl unter den Worten. Wenn dein Partner über das Geschirr schimpft, lautet die wahre Botschaft oft „ich fühle mich nicht unterstützt“ – und das verdient deine Aufmerksamkeit.",
    "Führe mit Empathie, wenn dein Partner aufgebracht ist, auch auf dich. Sich zu verteidigen kann warten; sich verstanden zu fühlen entschärft den Moment tatsächlich.",
    "Baut gemeinsam ein Gefühlsvokabular auf. Paare, die Gefühle präzise benennen können, lösen Konflikte tendenziell schneller als jene, die bei „gut“ und „wütend“ feststecken.",
    "Lass körperliche Nähe ein eigenes Gespräch sein. Einander ohne Absicht zu halten kann eine Sicherheit vermitteln, die Worte manchmal nur schwer erreichen.",
    "Halte Intimität abwechslungsreich und ungehetzt. Nähe vertieft sich, wenn ihr körperliche Verbundenheit als Entdeckung und Spiel behandelt statt als Routine oder Pflicht.",
    "Sprecht offen darüber, was ihr jeweils genießt. Ein entspanntes, ehrliches Gespräch über Intimität schafft Vertrauen und bewahrt das Verlangen davor, in Rätselraten zu verblassen.",
    "Sei zuerst der Freund deines Partners. Die Paare, die bleiben, mögen einander meist wirklich und genießen Gespräche noch lange, nachdem die frühen Funken sich gelegt haben.",
    "Tue kleine Gefälligkeiten unaufgefordert. Den Tank zu füllen oder das Handy aufzuladen sagt leise den ganzen Tag „ich denke an dich“.",
    "Findet Kompromisse, indem ihr Prioritäten tauscht, statt alles zu halbieren. Dort voll nachzugeben, wo es dir weniger wichtig ist, schafft Wohlwollen, wo es dir mehr bedeutet.",
    "Finde das Gewinn-Gewinn, bevor du dich mit dem Kompromiss zufriedengibst. Viele Konflikte mildern sich, wenn du fragst, was euch beide wirklich zufriedenstellen würde.",
    "Halte Grenzen mit Wärme, nicht mit Kälte. Du kannst klar Nein sagen und deinen Partner dabei dennoch geliebt und respektiert fühlen lassen.",
    "Bestrafe Verletzlichkeit nicht. Wenn dein Partner sich über eine Angst oder einen Fehler öffnet, sorgt es dafür, dass er dir wieder vertraut, wenn du ihm mit Zärtlichkeit begegnest.",
    "Baut eine Kultur der Wertschätzung auf und sucht nach dem Guten. Paare, die aktiv das Gute aneinander bemerken, berichten von deutlich dauerhafterem Glück.",
    "Lass deinen Partner sich gewählt fühlen, nicht nur geduldet. Ihm in Worten und Taten zu zeigen, dass du ihn wieder wählen würdest, hält die Liebe lebendig.",
    "Gib deinem Partner laut den Vertrauensvorschuss. „Ich bin sicher, du hast es nicht so gemeint“ entschärft Spannung, bevor sie sich aufbaut.",
    "Behandle die Ärgernisse deines Partners als Daten, nicht als Angriffe. Was ihn stört, weist oft auf ein unerfülltes Bedürfnis hin, das es zu verstehen lohnt, statt es abzutun.",
    "Halte Neugier größer als Urteil. Wenn dich etwas an deinem Partner verwundert, frage interessiert nach, statt mit Kritik zu enden.",
    "Feiert die Jahrestage kleiner Dinge, etwa eures ersten Gesprächs. Eure gemeinsame Geschichte zu ehren erinnert euch beide daran, wie weit ihr gemeinsam gekommen seid.",
    "Lass dich von deinem Partner beeinflussen. Paare gedeihen, wenn jeder die Meinungen und Vorlieben des anderen bei Entscheidungen wirklich berücksichtigt.",
    "Pflege die Freundschaft in eurer Romanze. Gemeinsame Insiderwitze, lockere Gespräche und einfache Gesellschaft tragen die Liebe durch die unglamourösen Jahreszeiten.",
    "Sei schnell im Trösten, langsam im Kritisieren. Das Verhältnis von Wärme zu Vorwurf, das du gibst, prägt, ob sich das Zuhause wie Sicherheit oder wie Urteil anfühlt.",
    "Bitte direkt und freundlich um das, was du willst. Andeutungen erzeugen Frust, während eine klare, sanfte Bitte deinem Partner eine echte Chance gibt, sie zu erfüllen.",
    "Bleibe lernbereit, wie man genau diesen Menschen liebt. Was in früheren Beziehungen funktionierte, passt vielleicht nicht; lass deinen Partner dir zeigen, was er braucht.",
    "Würdige die Mühe, auch wenn das Ergebnis hinterherhinkt. Anzuerkennen, dass dein Partner es versucht hat, ermutigt ihn weiterzumachen, statt leise aufzugeben.",
    "Suche Blickkontakt, wenn es darauf ankommt. Deinen Partner anzusehen, während er etwas Wichtiges teilt, sagt ihm, dass er dein ganzes Herz hat, nicht nur die Hälfte.",
    "Übergib eure Beziehung nicht dem Autopiloten. Langjährige Liebe braucht bewusste Aufmerksamkeit, sonst ersetzt Routine langsam die Verbindung, die einst mühelos schien.",
    "Sei bereit, der Erste zu sein, der weich wird. Jemand muss zuerst das Schwert senken, und diese Person zu sein ist eine Stärke, kein Verlust.",
    "Behandle die Hobbys deines Partners mit Respekt, auch wenn du sie nicht teilst. Das zu ehren, was ihn aufleuchten lässt, zeigt, dass du sein ganzes Selbst schätzt.",
    "Baue Vertrauen durch Beständigkeit auf. Immer wieder zu tun, was du sagst, lehrt deinen Partner, dass er endlich seine Deckung senken darf.",
    "Spende Zuspruch, bevor er erbeten wird. Trost anzubieten, wenn du die Sorge deines Partners spürst, zeigt eine Aufmerksamkeit, die Liebesworte allein nicht vermögen.",
    "Habt unterschiedliche Meinungen, ohne daraus eine Abstimmung über die Beziehung zu machen. Nicht jeder Konflikt heißt, dass etwas falsch ist; manchmal heißt er nur, dass ihr zwei Menschen seid.",
    "Geht weiter miteinander aus. Bewusst Zeit zu planen, sich schön zu machen, auszugehen und sich aufeinander zu konzentrieren, bewahrt die Romantik davor, leise in Logistik zu verblassen.",
    "Begrüße Rückmeldungen darüber, wie du liebst. Zu fragen „gibt es etwas, das du dir anders von mir wünschst?“ zeigt Demut und einen echten Wunsch zu wachsen.",
    "Lass kleine Freundlichkeiten sich ansammeln. Eine Beziehung wird weniger aus großen Gesten gebaut als aus tausend winzigen Entscheidungen, rücksichtsvoll und warm zu sein.",
    "Halte Raum für die Trauer und den Stress deines Partners, ohne hastig reparieren zu wollen. Manchmal ist Präsenz, nicht Ratschlag, die Liebe, die er wirklich braucht.",
    "Sei transparent bei Handy und Plänen. Offenheit dort, wo andere verbergen würden, schafft eine Grundlage des Vertrauens, die alles andere sicher anfühlen lässt.",
    "Wähle Neugier statt Eifersucht. Wenn Unsicherheit aufflammt, erkunde die Angst in dir selbst, statt Misstrauen auf einen Partner zu projizieren, der nichts falsch gemacht hat.",
    "Mach „wir kriegen das gemeinsam hin“ zu deinem Standard. Ungewissheit als geeinte Front zu begegnen verwandelt beängstigende Unbekannte in gemeinsame Abenteuer, die ihr meistern könnt.",
    "Lobe, wer sie sind, nicht nur, was sie tun. Deinem Partner zu sagen, dass du seine Güte oder seinen Mut bewunderst, nährt ihn tiefer als Lob für Aufgaben.",
    "Schütze Übergangszeiten, etwa die ersten Minuten zu Hause. Sich mit Wärme statt mit Beschwerden zu begrüßen gibt den emotionalen Ton für die kommenden Stunden vor.",
    "Erinnere dich an die Dinge, die ihnen wichtig sind, wenn sie sie dir erzählen. Auf eine Sorge zurückzukommen, die sie vor Tagen erwähnten, beweist, dass du wirklich zugehört hast.",
    "Bleibt auf derselben Seite des Tisches. Wenn ein Problem auftaucht, stell dir vor, neben deinem Partner zu sitzen und es anzuschauen, statt ihm gegenüber Vorwürfe zu machen.",
    "Bewahre eure Liebe privat, wenn sie Schutz braucht. Nicht jedes Detail gehört in soziale Medien; manche Intimität bleibt stärker, wenn sie zwischen euch bleibt.",
    "Sei großzügig mit Anerkennung und langsam mit Schuldzuweisung. Zu benennen, was dein Partner richtig gemacht hat, und eigene Fehltritte einzugestehen, verhindert, dass Groll Wurzeln schlägt.",
    "Lass Zuneigung bedingungslos sein, keine Belohnung. Wärme zurückzuhalten, um etwas zu beweisen, lehrt deinen Partner, dass deine Liebe mit Bedingungen verknüpft ist.",
    "Wachst gemeinsam, indem ihr Neues Seite an Seite ausprobiert. Geteilte Neuheit, von Reisen bis zu einem neuen Kurs, entfacht die Aufregung neu, die die frühe Liebe ganz natürlich hatte.",
    "Beende jeden Tag mit einem Moment der Verbindung. Ein paar ehrliche Worte oder eine lange Umarmung vor dem Schlafen näht euch wieder zusammen, nachdem der Tag euch auseinandergezogen hat.",
  ],
  facts: [
    "Wenn du dich verliebst, wird dein Gehirn von Dopamin überflutet, demselben Belohnungsbotenstoff, der an Motivation und Lust beteiligt ist – deshalb kann sich neue Liebe fast süchtig machend anfühlen.",
    "Oxytocin, oft „Bindungshormon“ genannt, schießt bei Umarmungen, Händchenhalten und Nähe nach oben und hilft Partnern, sich verbunden und vertrauensvoll zu fühlen.",
    "Studien legen nahe, dass ein paar Minuten gegenseitiges In-die-Augen-Schauen das Gefühl von Nähe steigern kann, selbst zwischen relativ Fremden.",
    "Der Ausdruck „sich verlieben“ ist vielleicht wörtlicher als poetisch; frühe Romantik kann den Serotoninspiegel auf Werte senken, wie man sie bei zwanghaftem Denken sieht.",
    "Forscher haben festgestellt, dass das Halten der Hand eines geliebten Menschen die Wahrnehmung von körperlichem Schmerz und Stress messbar verringern kann.",
    "Dein Herzschlag kann sich tatsächlich mit dem eines Partners synchronisieren, wenn ihr nah beieinander sitzt und euch anschaut, so Studien über Paare.",
    "Die alten Griechen beschrieben mehrere Arten der Liebe, darunter Eros (Leidenschaft), Philia (Freundschaft) und Agape (selbstlose Liebe), und erkannten Liebe als weit mehr als ein einziges Gefühl.",
    "Präriewühlmäuse sind in der Wissenschaft dafür berühmt, lebenslange Paarbindungen einzugehen, und ihre Erforschung hat viel über die Chemie der Monogamie gelehrt.",
    "Die Tradition des Verlobungsrings aus Diamant verbreitete sich vor allem nach einer berühmten Werbekampagne des 20. Jahrhunderts, die verkündete „Ein Diamant ist unvergänglich“.",
    "Schmetterlinge im Bauch in der frühen Liebe sind real; das Adrenalin der Anziehung kann Blut vom Verdauungssystem ableiten und dieses flatternde Gefühl erzeugen.",
    "Studien legen nahe, dass Paare, die regelmäßig miteinander lachen, von höherer Beziehungszufriedenheit berichten und sich mit der Zeit verbundener fühlen.",
    "Die Hochzeitstradition, den Ring am Ringfinger zu tragen, geht auf den alten Glauben an eine „Vena amoris“ zurück, eine Vene, die direkt zum Herzen führt.",
    "Romantische Liebe und tiefe Bindung aktivieren leicht unterschiedliche Hirnsysteme, was erklärt, wie Leidenschaft zu einer ruhigeren, stetigeren Verbindung reifen kann.",
    "Schwäne, oft als Symbole der Liebe gesehen, gehen häufig langanhaltende Paarbindungen ein und bleiben manchmal viele Jahre beim selben Partner.",
    "Forscher schätzen, dass es zwischen wenigen Sekunden und wenigen Minuten dauern kann, bis jemand entscheidet, ob er sich zu einer neuen Person hingezogen fühlt.",
    "Die „Flitterwochenphase“ intensiver früher Leidenschaft dauert typischerweise zwischen mehreren Monaten und etwa zwei Jahren, bevor sie sich in tiefere Bindung wandelt.",
    "Kuscheln und körperliche Zuneigung können die Ausschüttung von Endorphinen auslösen, den natürlichen Wohlfühlstoffen des Körpers, die auch Stress mindern helfen.",
    "In vielen Kulturen wurde die Ehe historisch aus wirtschaftlichen oder politischen Gründen arrangiert, und die Idee, vor allem aus Liebe zu heiraten, ist relativ modern.",
    "Studien legen nahe, dass Menschen sich oft am stärksten zu Gesichtern hingezogen fühlen, die annähernd symmetrisch sind, was manche Wissenschaftler mit unterbewussten Gesundheitshinweisen verbinden.",
    "Das Wort „Romanze“ bezog sich ursprünglich auf einen Stil mittelalterlicher Erzählkunst und bekam erst später die Bedeutung der leidenschaftlichen Liebe, die wir damit verbinden.",
    "Geruch spielt eine überraschende Rolle bei der Anziehung; Forschung legt nahe, dass Duft subtil beeinflussen kann, wen wir als möglichen Partner ansprechend finden.",
    "Langjährige Paare beginnen sich manchmal leicht zu ähneln, ein Phänomen, das Forscher teils auf Jahrzehnte gemeinsamer Mimik, Umgebung und Gefühle zurückführen.",
    "Der Brauch des Küssens unter dem Mistelzweig reicht Jahrhunderte zurück und war einst mit alten Traditionen von Frieden, Fruchtbarkeit und Wohlwollen verbunden.",
    "Sich zu verlieben kann vorübergehend die Aktivität in Hirnregionen mindern, die mit kritischem Urteil verbunden sind – ein Grund, warum Liebe ein wenig blind machen kann.",
    "Studien legen nahe, dass schon die Erwartung, dass jemand warm und freundlich ist, dich so handeln lässt, dass er im Gegenzug warm reagiert.",
    "Albatrosse führen aufwendige Balztänze auf und können dieselbe Partnerschaft über viele Brutsaisons hinweg halten, manchmal über einen Großteil ihres langen Lebens.",
    "Das Gehirn in der frühen Liebe kann dem Gehirn bei bestimmten Belohnungen gleichen und Belohnungszentren aktivieren, die uns zur Nähe mit dem Partner drängen.",
    "Forscher haben festgestellt, dass Paare, die einander regelmäßig Dankbarkeit ausdrücken, sich in ihrer Beziehung engagierter und zufriedener fühlen.",
    "Das Herzsymbol, das wir mit Liebe verbinden, ähnelt eigentlich keinem menschlichen Herzen; sein Ursprung ist umstritten und über Jahrhunderte vermutlich stilisiert worden.",
    "Tastsinn ist einer der ersten Sinne, die sich entwickeln, und sanfte körperliche Zuneigung bleibt ein lebenslang kraftvoller Weg, mit dem Menschen Liebe ausdrücken.",
    "Studien legen nahe, dass gemeinsam neue und aufregende Aktivitäten zu unternehmen die Beziehungszufriedenheit steigern kann, indem ein Teil der Neuheit früher Romantik wiederkehrt.",
    "Einige Pinguine sind für Balzrituale bekannt, bei denen sie einem potenziellen Partner einen sorgfältig ausgewählten Kieselstein überreichen.",
    "Das Hormon Vasopressin spielt neben Oxytocin vermutlich eine wichtige Rolle bei langfristiger Bindung und Verbundenheit zwischen Partnern.",
    "Der Valentinstag hat seine Wurzeln in antiken Festen und der Legende des heiligen Valentin und entwickelte sich über Jahrhunderte zur heutigen Feier romantischer Liebe.",
    "Forschung legt nahe, dass Menschen sich denen näher fühlen, denen sie sich öffnen, weshalb das Teilen persönlicher Geschichten die Nähe beschleunigen kann.",
    "Erröten, eine einzigartig menschliche Reaktion, kann Anziehung und Verlegenheit signalisieren, und einige Forscher meinen, es habe sich teils als ehrliches soziales Signal entwickelt.",
    "Der „Mere-Exposure-Effekt“ bedeutet, dass wir Menschen oft allein dadurch mehr mögen, dass wir sie wiederholt sehen – weshalb Nähe Romantik entfachen kann.",
    "Studien legen nahe, dass Paare, die Konflikte mit Humor und Sanftheit statt mit Verachtung bewältigen, weit eher zusammenbleiben.",
    "Seepferdchen sind für eine ungewöhnliche Aufteilung bekannt, bei der das Männchen die heranwachsenden Jungen trägt und nährt.",
    "Der Stoff Phenylethylamin, manchmal „Liebesmolekül“ genannt, wird bei Anziehung ausgeschüttet und kommt natürlich in kleinen Mengen auch in Schokolade vor.",
    "Über viele Kulturen und Epochen hinweg haben Dichter die Liebe als eines der zentralen Themen der Menschheit behandelt, was nahelegt, dass ihre emotionale Anziehung bemerkenswert universell ist.",
    "Die Forschung zu „Bindungsstilen“ legt nahe, dass unsere frühen Bindungen zu Bezugspersonen beeinflussen können, wie sicher oder ängstlich wir uns in erwachsenen Liebesbeziehungen fühlen.",
    "Studien legen nahe, dass selbst kurze Freundlichkeiten zwischen Partnern, etwa Tee zu machen oder eine schnelle Nachricht, sich zu dauerhaftem Beziehungswohlwollen summieren.",
    "Der Brauch der Hochzeitstorte hat alte Wurzeln, wobei verschiedene Kulturen historisch Brot oder Kuchen in Eheritualen als Symbol des Wohlstands verwendeten.",
    "Manche Wissenschaftler glauben, dass die Macht der Musik, Gefühle zu rühren, eng mit Bindung verknüpft ist, weshalb es in fast jeder Kultur Liebeslieder gibt.",
    "Forscher haben beobachtet, dass frisch verliebte Paare manchmal weniger Appetit haben und schlecht schlafen, teils wegen der aufschießenden Stress- und Belohnungsstoffe.",
    "Der „Schwänzeltanz“ der Honigbiene ist keine Romanze, doch viele Balzvorführungen im Tierreich sind aufwendige Auftritte, um einen Partner anzulocken und zu beeindrucken.",
    "Studien legen nahe, dass sich geschätzt zu fühlen einer der stärksten Prädiktoren dafür ist, ob Menschen sich zufrieden fühlen und in einer Beziehung bleiben wollen.",
    "Die Tradition, die Braut über die Schwelle zu tragen, wurzelt in alten Bräuchen, von denen man einst glaubte, sie schützten das Paar vor Unglück.",
    "Liebe und Schmerz können sich überschneidende Hirnbahnen teilen, was erklären kann, warum Liebeskummer sich tatsächlich körperlich schmerzhaft anfühlen kann.",
    "Forscher, die lange verheiratete Paare untersuchten, fanden, dass eine kleine Zahl, die noch intensive Liebe empfindet, Hirnaktivität ähnlich der frühen Romantik zeigt.",
    "Viele Vogelarten singen Duette mit ihren Partnern, wobei sie ihre Rufe so präzise abstimmen, dass es wie eine einzige Stimme klingen kann.",
    "Studien legen nahe, dass Paare tendenziell glücklicher sind, wenn sie im Alltag ein gesundes Verhältnis von positiven zu negativen Interaktionen wahren.",
    "Der Austausch von Ringen als Symbol der Bindung ist eine uralte Praxis, die in verschiedenen Formen über viele frühe Zivilisationen hinweg auftaucht.",
    "Körperliche Anziehung kann von etwas so Einfachem wie einem rasenden Herzschlag beeinflusst werden; Erregung aus Aufregung wird manchmal als romantische Anziehung fehlgedeutet.",
    "Manche Forscher beschreiben romantische Liebe als drei grobe Komponenten: Lust, Anziehung und Bindung, die jeweils von unterschiedlicher Hirnchemie angetrieben werden.",
    "Wölfe bilden typischerweise starke Paarbindungen, wobei ein gebundenes Paar oft den sozialen Kern ihres Rudels bildet.",
    "Studien legen nahe, dass Partner, die ihre Beziehung als Ort der Annahme empfinden, eher bereit sind, gesunde emotionale Risiken miteinander einzugehen.",
    "Die Farbe Rot wurde in einigen Studien mit Anziehungswahrnehmung verknüpft, wobei Menschen andere manchmal als ansprechender bewerten, wenn diese Rot tragen.",
    "Über die Geschichte hinweg waren Liebesbriefe geschätzte Andenken, und erhaltene Beispiele aus vergangenen Jahrhunderten zeigen, dass sich Sehnsucht und Hingabe kaum verändern.",
    "Forscher haben festgestellt, dass unterstützende Berührung eines Partners helfen kann, den Blutdruck zu senken und die Stressreaktion des Körpers zu lindern.",
    "Einige Pinguinarten, Gibbons und bestimmte Füchse werden von Biologen für ihre bemerkenswert starken und dauerhaften Paarbindungen hervorgehoben.",
    "Der „Romeo-und-Julia-Effekt“ beschreibt, wie äußerer Widerstand gegen eine Beziehung die Leidenschaft eines Paares manchmal verstärkt statt schwächt.",
    "Studien legen nahe, dass schon der Gedanke an einen geliebten Menschen Belohnungsareale des Gehirns aktivieren und einen messbaren Puffer gegen Stress bieten kann.",
    "Viele Kulturen tauschten historisch Verlobungszeichen aus, von Ringen über Bänder bis zu Münzen, lange bevor moderne Verlobungstraditionen Gestalt annahmen.",
    "Forschung legt nahe, dass Menschen oft unterschätzen, wie sehr ein aufrichtiges Kompliment den Tag ihres Partners erhellt, weshalb freundliche Worte zu oft ungesagt bleiben.",
    "Gibbons sind unter den Primaten dafür bekannt, langfristige Paarbindungen einzugehen und sogar koordinierte Morgenrufe gemeinsam zu singen.",
    "Das Gefühl von „Chemie“ mit jemandem spiegelt vielleicht teils wider, wie wohl und entspannt sich dein Nervensystem in seiner Gegenwart fühlt.",
    "Studien legen nahe, dass Paare, die gute Nachrichten gemeinsam teilen und feiern – nicht nur einander in schweren Zeiten stützen – sich verbundener fühlen.",
    "Biber paaren sich typischerweise und arbeiten zusammen, um ihre Burgen zu bauen und zu erhalten, und teilen die Mühe der Jungenaufzucht.",
    "Der Ausdruck „den Bund fürs Leben schließen“ stammt vermutlich von alten Hochzeitsbräuchen verschiedener Kulturen, bei denen man die Hände des Paares buchstäblich zusammenband.",
    "Forschung zur Anziehung legt nahe, dass Humor eine der am häufigsten geschätzten Eigenschaften ist, die Menschen bei einem langfristigen Partner suchen.",
    "Manche Wissenschaftler glauben, dass die menschliche Neigung, Paarbindungen einzugehen, sich teils entwickelt haben könnte, um die lange Aufgabe der Kindererziehung zu stützen.",
    "Studien legen nahe, dass Paare, die gemeinsame Rituale pflegen, so klein sie auch sind, von einem stärkeren Gefühl gemeinsamer Identität und Zugehörigkeit berichten.",
    "Der Mythos von Cupido, der geflügelten Gestalt, die Herzen mit Pfeilen trifft, stammt aus der römischen Mythologie und der älteren griechischen Figur des Eros.",
    "Forscher haben festgestellt, dass sich von einem Partner verstanden zu fühlen eng damit verbunden ist, sich geliebt zu fühlen – manchmal mehr als große romantische Gesten.",
    "Bestimmte Antilopen, Kraniche und Papageien gehören zu den vielen Tieren, bei denen Biologen dauerhafte Bindungen an einen einzigen Partner beobachtet haben.",
    "Studien legen nahe, dass die Art, wie Paare mit kleinen täglichen Ärgernissen umgehen, langfristige Zufriedenheit zuverlässiger vorhersagt als ihr Umgang mit seltenen großen Krisen.",
    "Die Tradition einer „Flitterwochen“-Reise nach der Hochzeit wurde im 19. Jahrhundert populär, obwohl das Wort selbst weit älter ist.",
    "Forschung legt nahe, dass körperliche Nähe im Schlaf, etwa die nahe Anwesenheit eines Partners, das Gefühl von Sicherheit und Erholung subtil verbessern kann.",
    "Manche Blumen, besonders die rote Rose, wurden durch Jahrhunderte der Dichtung, Kunst und kulturellen Tradition zu beständigen Symbolen der Liebe.",
    "Studien legen nahe, dass Paare, die sich nach einem Konflikt schnell versöhnen, statt Konflikte perfekt zu vermeiden, die stabilsten Beziehungen haben.",
    "Das Belohnungssystem des Gehirns kann auf das Lächeln eines Partners ähnlich reagieren wie auf andere zutiefst belohnende Erlebnisse und verstärkt so die Anziehung der Liebe.",
    "Viele Kulturen entwickelten Verkupplungstraditionen, und professionelle Heiratsvermittler gibt es in verschiedenen Gesellschaften seit Hunderten von Jahren.",
    "Forschung legt nahe, dass Zuneigung, die in der bevorzugten „Liebessprache“ des Partners ausgedrückt wird, kraftvoller ankommt als Zuneigung zu deinen eigenen Bedingungen.",
    "Störche, in der Folklore oft mit Babys verbunden, sind auch dafür bekannt, Jahr für Jahr zum selben Nest und Partner zurückzukehren.",
    "Studien legen nahe, dass Nostalgie über gemeinsame Erinnerungen die Bindung eines Paares stärken kann, indem sie an die gemeinsame Geschichte und Widerstandskraft erinnert.",
    "Der Brauch der Brautjungfern geht vielleicht auf alte Traditionen zurück, bei denen ähnlich gekleidete Begleiterinnen böse Geister verwirren sollten.",
    "Forschung legt nahe, dass Paare, die bei Meinungsverschiedenheiten ein „Wir“ statt ein „Ich gegen Dich“ wahren, diese tendenziell konstruktiver lösen.",
    "Weißkopfseeadler bilden oft langfristige Paarbindungen und kehren über viele Jahre gemeinsam zum selben Nistplatz zurück.",
    "Studien legen nahe, dass Vorfreude das Glück steigern kann, weshalb das Vorfreuen auf Zeit mit einem Partner fast so freudvoll sein kann wie die Zeit selbst.",
    "Die Tradition, Blumen als romantische Geste zu schenken, ist über viele Kulturen und Jahrhunderte hinweg als Sprache der Zuneigung dokumentiert.",
    "Forschung legt nahe, dass Menschen in unterstützenden Beziehungen sich von Krankheit und Stress etwas schneller erholen als jene, die sich isoliert fühlen.",
    "Einige Buntbarscharten werden von Biologen dafür hervorgehoben, als Paare zusammenzuarbeiten, um ihre Eier und Jungen zu bewachen und zu versorgen.",
    "Studien legen nahe, dass Paare, die regelmäßig körperliche Zuneigung ausdrücken – über die Konfliktlösung hinaus – stärkere emotionale Bindungen wahren.",
    "Der Begriff „Seelenverwandter“ taucht seit der Antike in der Philosophie auf, einschließlich eines berühmten Mythos, der in Platons Schriften erzählt wird.",
    "Forschung legt nahe, dass schon einen Partner zu haben, dem man sich anvertrauen kann, mit größerer Widerstandskraft in den stressreichsten Momenten des Lebens verbunden ist.",
    "Französische Kaiserfische gehören zu den Arten, bei denen Biologen beobachtet haben, dass sie als treue, kooperative Paare reisen und ihr Revier verteidigen.",
    "Studien legen nahe, dass die frühe Gewohnheit, einen Partner – in Maßen – zu idealisieren, Paaren tatsächlich helfen kann, über die Zeit zufrieden zu bleiben.",
    "Der Handschlag und der Kuss als Begrüßung haben beide tiefe historische Wurzeln, wobei der romantische Kuss in vielen alten Kulturen auftaucht.",
    "Forschung legt nahe, dass Paare, die sich Zeit für gemeinsame Freizeit nehmen, selbst kurze Momente, sich näher und mehr wie ein Team fühlen.",
    "Manche Wissenschaftler meinen, die universelle menschliche Fähigkeit zur Liebe könnte eines der mächtigsten Werkzeuge der Evolution für Kooperation und Überleben sein.",
    "Studien legen nahe, dass sich in einer Beziehung sicher zu fühlen Menschen befreit, im Rest ihres Lebens abenteuerlustiger und selbstbewusster zu sein.",
    "Die Tradition der Liebesdichtung reicht Jahrtausende zurück, wobei einige der ältesten bekannten Liebesgedichte auf antike Tontafeln geschrieben wurden.",
    "Forschung legt nahe, dass Partner sich oft nicht bei dramatischen Gesten am meisten geliebt fühlen, sondern in kleinen, beständigen Momenten der Aufmerksamkeit und Fürsorge.",
    "Bestimmte Eulenarten bilden dauerhafte Paarbindungen und arbeiten eng zusammen, um ihre Jungen aufzuziehen, indem sie Jagd- und Nistpflichten teilen.",
    "Studien legen nahe, dass Paare, die neben ihrer Beziehung eigene Freundschaften und Interessen pflegen, von größerem langfristigem Glück miteinander berichten.",
    "Der Schleier mancher Bräute hat alte Ursprünge und taucht in verschiedenen Kulturen als Symbol von Bescheidenheit, Geheimnis oder Schutz auf.",
    "Forschung legt nahe, dass das Erleben von Ehrfurcht, etwa beim gemeinsamen Betrachten eines Sonnenuntergangs, das Gefühl von Verbundenheit und gemeinsamem Sinn eines Paares vertiefen kann.",
    "Viele Kulturen kennen Volksbräuche um Liebeszauber und Talismane, die einen zeitlosen menschlichen Wunsch widerspiegeln, Zuneigung anzuziehen und zu bewahren.",
    "Studien legen nahe, dass Responsivität – das Gefühl, dass dein Partner deine Bedürfnisse wirklich bemerkt und ihm an ihnen liegt – zentral dafür ist, sich tief geliebt zu fühlen.",
    "Die Idee, einen Hochzeitstag mit bestimmten Geschenken zu feiern, wie Papier oder Gold für bestimmte Jahre, entwickelte sich nach und nach über die letzten Jahrhunderte.",
    "Forschung legt nahe, dass schon das Vorstellen künftiger Momente mit einem Partner die heutige Bindung und Motivation, die Beziehung zu pflegen, stärken kann.",
    "Einige Goldschopfpinguine und andere Seevögel finden in jeder Brutsaison wieder zum selben Partner zurück, nachdem sie Monate getrennt auf See verbracht haben.",
    "Studien legen nahe, dass das einfache „Danke“ an einen Partner einen positiven Kreislauf aus Wertschätzung und Großzügigkeit in Gang setzen kann.",
    "Das Wort „kuscheln“ klingt vielleicht modern, doch Menschen haben den Trost engen körperlichen Kontakts seit den frühesten Momenten unserer Spezies gesucht.",
    "Forschung legt nahe, dass Paare, die Herausforderungen als gemeinsame Probleme zum Lösen sehen statt als persönliches Versagen, durch Schwierigkeiten tendenziell stärker werden.",
  ],
  quotes: [
    { text: "Woraus auch immer unsere Seelen gemacht sind, seine und meine sind aus demselben Stoff.", author: "Emily Brontë" },
    { text: "Du weißt, dass du verliebt bist, wenn du nicht einschlafen kannst, weil die Wirklichkeit endlich schöner ist als deine Träume.", author: "Dr. Seuss" },
    { text: "Liebe besteht aus einer einzigen Seele, die zwei Körper bewohnt.", author: "Aristoteles" },
    { text: "Das Beste, woran man sich im Leben festhalten kann, ist einander.", author: "Audrey Hepburn" },
    { text: "Wir sind am lebendigsten, wenn wir verliebt sind.", author: "John Updike" },
    { text: "Liebe ist der Zustand, in dem das Glück eines anderen Menschen für das eigene unerlässlich ist.", author: "Robert A. Heinlein" },
    { text: "Zu lieben und geliebt zu werden heißt, die Sonne von beiden Seiten zu spüren.", author: "David Viscott" },
    { text: "Es gibt kein Mittel gegen die Liebe, außer mehr zu lieben.", author: "Henry David Thoreau" },
    { text: "Liebe besteht nicht darin, einander anzusehen, sondern gemeinsam in dieselbe Richtung zu blicken.", author: "Antoine de Saint-Exupéry" },
    { text: "Wenn ich weiß, was Liebe ist, dann deinetwegen.", author: "Hermann Hesse" },
    { text: "Das größte Glück des Lebens ist die Gewissheit, geliebt zu werden.", author: "Victor Hugo" },
    { text: "Liebe ist Freundschaft, die Feuer gefangen hat.", author: "Ann Landers" },
    { text: "Wo Liebe ist, da ist Leben.", author: "Mahatma Gandhi" },
    { text: "Von jemandem tief geliebt zu werden gibt dir Kraft, während jemanden tief zu lieben dir Mut gibt.", author: "Laotse" },
    { text: "Liebe ist, wenn das Glück des anderen wichtiger ist als das eigene.", author: "H. Jackson Brown Jr." },
    { text: "Das Herz hat seine Gründe, die der Verstand nicht kennt.", author: "Blaise Pascal" },
    { text: "Eine glückliche Ehe verlangt, sich viele Male zu verlieben, immer in dieselbe Person.", author: "Mignon McLaughlin" },
    { text: "Wir liebten mit einer Liebe, die mehr war als Liebe.", author: "Edgar Allan Poe" },
    { text: "Doch die schönsten Dinge der Welt kann man weder sehen noch berühren, man muss sie mit dem Herzen fühlen.", author: "Helen Keller" },
    { text: "Liebe heißt nicht, jemanden zum Leben zu finden. Sie heißt, jemanden zu finden, ohne den man nicht leben kann.", author: "Rafael Ortiz" },
    { text: "Liebe kennt keine Schranken. Sie nimmt Hürden, springt über Zäune, durchdringt Mauern, um voller Hoffnung an ihr Ziel zu gelangen.", author: "Maya Angelou" },
    { text: "Liebe ist ein unwiderstehliches Verlangen, unwiderstehlich begehrt zu werden.", author: "Robert Frost" },
    { text: "Man heiratet nicht jemanden, mit dem man leben kann, sondern den Menschen, ohne den man nicht leben kann.", author: "Unbekannt" },
    { text: "Der Weg der wahren Liebe verlief noch nie glatt.", author: "William Shakespeare" },
    { text: "Liebe alle, vertraue wenigen, tue niemandem Unrecht.", author: "William Shakespeare" },
    { text: "Die Liebe blickt nicht mit den Augen, sondern mit dem Gemüt.", author: "William Shakespeare" },
    { text: "Ich habe den gefunden, den meine Seele liebt.", author: "Hohelied Salomos" },
    { text: "Die Liebe ist langmütig und gütig. Sie ereifert sich nicht, sie prahlt nicht, sie bläht sich nicht auf.", author: "1. Korinther 13,4" },
    { text: "Bei der Berührung der Liebe wird jeder zum Dichter.", author: "Platon" },
    { text: "Das Schenken von Liebe ist an sich schon eine Erziehung.", author: "Eleanor Roosevelt" },
    { text: "Liebe ist die Blume, die man wachsen lassen muss.", author: "John Lennon" },
    { text: "Alles, was du brauchst, ist Liebe.", author: "John Lennon" },
    { text: "Liebe ist da oder eben nicht. Dünne Liebe ist überhaupt keine Liebe.", author: "Toni Morrison" },
    { text: "Liebe nimmt uns Masken ab, von denen wir fürchten, nicht ohne sie leben zu können, und wissen, dass wir nicht in ihnen leben können.", author: "James Baldwin" },
    { text: "Liebe ist eine Frucht, die zu jeder Zeit reif ist und in der Reichweite jeder Hand liegt.", author: "Mutter Teresa" },
    { text: "Verbreite Liebe, wohin du auch gehst. Lass niemanden zu dir kommen, ohne glücklicher zu gehen.", author: "Mutter Teresa" },
    { text: "Wir können nur durch Lieben lieben lernen.", author: "Iris Murdoch" },
    { text: "Liebe ist nichts, das man findet. Liebe ist etwas, das einen findet.", author: "Loretta Young" },
    { text: "Die Kunst der Liebe ist weitgehend die Kunst der Beharrlichkeit.", author: "Albert Ellis" },
    { text: "Überhaupt zu lieben heißt, verletzlich zu sein.", author: "C. S. Lewis" },
    { text: "Liebe ist kein zärtliches Gefühl, sondern ein beständiger Wunsch nach dem höchsten Wohl des geliebten Menschen.", author: "C. S. Lewis" },
    { text: "Liebe ist das Ganze. Wir sind nur Teile.", author: "Rumi" },
    { text: "Deine Aufgabe ist nicht, die Liebe zu suchen, sondern nur all die Schranken in dir zu finden, die du gegen sie errichtet hast.", author: "Rumi" },
    { text: "Lass die Schönheit dessen, was du liebst, das sein, was du tust.", author: "Rumi" },
    { text: "Die Liebe ist die Brücke zwischen dir und allem.", author: "Rumi" },
    { text: "Die Gravitation ist nicht dafür verantwortlich, dass Menschen sich verlieben.", author: "Albert Einstein" },
    { text: "Liebe besteht darin, dass zwei Einsamkeiten einander schützen, berühren und begrüßen.", author: "Rainer Maria Rilke" },
    { text: "Hast du einmal gelernt zu lieben, hast du gelernt zu leben.", author: "Unbekannt" },
    { text: "Liebe setzt sich aus vielem zusammen, doch ihr Fundament sind Freundschaft und Vertrauen.", author: "Unbekannt" },
    { text: "Wenn du jemanden liebst, liebst du den Menschen, wie er ist, und nicht, wie du ihn dir wünschst.", author: "Leo Tolstoi" },
    { text: "Er stieg herab und mühte sich, sie nicht lange anzusehen, als wäre sie die Sonne, und doch sah er sie, wie die Sonne, auch ohne hinzusehen.", author: "Leo Tolstoi" },
    { text: "Zweifle, ob die Sterne Feuer sind; zweifle, ob die Sonne sich bewegt; zweifle, ob die Wahrheit lügt; doch zweifle nie, dass ich dich liebe.", author: "William Shakespeare" },
    { text: "Wie ich dich liebe? Lass mich die Wege zählen.", author: "Elizabeth Barrett Browning" },
    { text: "Liebe steht vor dem Leben, kommt nach dem Tod, ist der Anfang der Schöpfung und der Inbegriff des Atems.", author: "Emily Dickinson" },
    { text: "Dass Liebe alles ist, ist alles, was wir von der Liebe wissen.", author: "Emily Dickinson" },
    { text: "Wenn du hundert Jahre alt wirst, möchte ich hundert Jahre minus einen Tag alt werden, damit ich nie ohne dich leben muss.", author: "A. A. Milne" },
    { text: "Liebe ist eine Leinwand, die von der Natur gestellt und von der Vorstellungskraft bestickt wird.", author: "Voltaire" },
    { text: "Die besten und schönsten Dinge dieser Welt kann man weder sehen noch hören, sondern muss sie mit dem Herzen fühlen.", author: "Helen Keller" },
    { text: "Eine Blume kann nicht ohne Sonnenschein blühen, und der Mensch kann nicht ohne Liebe leben.", author: "Max Müller" },
    { text: "Liebe ist wie der Wind, du kannst sie nicht sehen, aber du kannst sie fühlen.", author: "Nicholas Sparks" },
    { text: "Schon ihr bloßes Fehlen bedeutet mir mehr als die Gegenwart anderer.", author: "Edward Thomas" },
    { text: "Lieber teile ich ein Leben mit dir, als allen Zeitaltern dieser Welt allein zu begegnen.", author: "J. R. R. Tolkien" },
    { text: "Liebe ist der Hauptschlüssel, der die Tore des Glücks öffnet.", author: "Oliver Wendell Holmes" },
    { text: "Wir werden von dem geformt und gestaltet, was wir lieben.", author: "Johann Wolfgang von Goethe" },
    { text: "Liebe und Husten lassen sich nicht verbergen.", author: "George Herbert" },
    { text: "Zwei Menschen reichen einander im Vorübergehen die Welt.", author: "Unbekannt" },
    { text: "Liebe lässt die Seele aus ihrem Versteck hervorkriechen.", author: "Zora Neale Hurston" },
    { text: "In der Liebe ist immer etwas Wahnsinn. Doch im Wahnsinn ist auch immer etwas Vernunft.", author: "Friedrich Nietzsche" },
    { text: "Liebe ist die einzige Kraft, die einen Feind in einen Freund zu verwandeln vermag.", author: "Martin Luther King Jr." },
    { text: "Wir müssen die Fähigkeit zu vergeben entwickeln und bewahren.", author: "Martin Luther King Jr." },
    { text: "Der Weg, etwas zu lieben, besteht darin, sich bewusst zu machen, dass man es verlieren könnte.", author: "G. K. Chesterton" },
    { text: "Zu lieben ist niemals Zeitverschwendung.", author: "Astrid Alauda" },
    { text: "Liebe ist die Stimme unter allem Schweigen, die Hoffnung, die kein Gegenstück in der Angst hat.", author: "E. E. Cummings" },
    { text: "Ich trage dein Herz bei mir. Ich trage es in meinem Herzen.", author: "E. E. Cummings" },
    { text: "Liebe wächst durch Geben. Die Liebe, die wir verschenken, ist die einzige Liebe, die wir behalten.", author: "Elbert Hubbard" },
    { text: "Zu lieben ist nichts. Geliebt zu werden ist etwas. Doch zu lieben und geliebt zu werden, das ist alles.", author: "T. Tolis" },
    { text: "Die Liebe pflanzte eine Rose, und die Welt wurde süß.", author: "Katharine Lee Bates" },
    { text: "Liebe ist die Entfaltung zweier Naturen, sodass jede die andere umschließt.", author: "Felix Adler" },
    { text: "Sag mir, wen du liebst, und ich sage dir, wer du bist.", author: "Houssaye" },
    { text: "Wo du einst warst, klafft ein Loch in der Welt, um das ich tagsüber unablässig herumgehe.", author: "Edna St. Vincent Millay" },
  ],
};
