import type { RotationalContent } from '@/lib/dailyContentTypes';

export const en: RotationalContent = {
  tips: [
    "Listen to understand, not to reply. Pausing before you respond shows your partner their words actually landed, and that small habit deepens trust over time.",
    "Say thank you for the ordinary things. Noticing the coffee made or the dishes done reminds your partner that their everyday effort never goes unseen.",
    "When conflict rises, attack the problem together rather than each other. You are teammates facing an issue, not opponents trying to win a point.",
    "Schedule unhurried time together, even just twenty minutes. Connection rarely happens in the gaps; it grows when you deliberately make room for it.",
    "Ask your partner how they prefer to be comforted. Some want solutions, others want a hug and silence, and guessing wrong can feel like distance.",
    "Repair quickly after a disagreement. A sincere check-in once tempers cool matters far more than pretending the friction never happened at all.",
    "Curiosity keeps love alive. Keep asking your long-term partner new questions, because people quietly change and the most interesting ones are still unfolding.",
    "Express appreciation out loud, not just in your head. Unspoken gratitude warms only you, while spoken gratitude warms the person you love.",
    "Protect your relationship from contempt. Eye-rolling and sarcasm corrode connection faster than almost anything, so choose respect even when you are frustrated.",
    "Make bids for connection count. When your partner shares something small, turning toward them with attention is the quiet glue of lasting love.",
    "Apologize without adding 'but.' A clean apology owns your part fully, while a qualified one quietly hands the blame back across the table.",
    "Keep a few rituals that are just yours. A Sunday walk or shared morning coffee creates a steady rhythm that anchors busy lives together.",
    "Assume good intent before assuming the worst. Most hurtful moments come from clumsiness or stress, not from a partner secretly wishing you harm.",
    "Talk about money early and often. Aligning on spending, saving, and goals prevents the silent resentment that finances can otherwise quietly create.",
    "Let your partner be different from you. Compatibility is not sameness; it is two distinct people choosing to honor each other's separate inner world.",
    "Notice what your partner is carrying. A gentle 'you seem tired, let me handle dinner' can say I love you louder than words.",
    "Keep some independence inside togetherness. Pursuing your own friends and passions makes you a more interesting, energized partner to come home to.",
    "Praise in public, problem-solve in private. Building your partner up in front of others, and handling friction quietly, protects both pride and trust.",
    "Replace 'you always' and 'you never' with 'I feel.' Speaking from your experience invites understanding, while sweeping accusations invite defensiveness.",
    "Touch matters even when nothing is wrong. A hand on the shoulder or a quick hug keeps the body remembering it is loved.",
    "Choose your partner again on hard days. Love is not only the spark you fell into but the decision you renew when things get heavy.",
    "Be interested in their world. Asking real questions about your partner's work, worries, and dreams tells them their life genuinely matters to you.",
    "Don't keep score. Generosity given to be repaid is a transaction; love thrives when you give freely and trust the balance evens out.",
    "Name your needs clearly. Your partner cannot read your mind, and quietly hoping they will guess often ends in disappointment for you both.",
    "Laugh together often. Shared humor lowers tension, builds intimacy, and reminds you that the person beside you is also your favorite companion.",
    "Give your full presence at reunions. Greeting your partner warmly when you reconnect, phone down and eyes up, sets the tone for the evening.",
    "Forgive the small stuff fast. Holding onto minor grievances builds a wall brick by brick until you can no longer reach each other.",
    "Celebrate your partner's wins as your own. Genuine delight in their success, without envy, is one of the deepest forms of love.",
    "Check in before you assume you've drifted. A simple 'how are we doing lately?' often reveals connection that distance only seemed to threaten.",
    "Respect each other's boundaries without taking them personally. A boundary is information about your partner's needs, not a rejection of you.",
    "Make repair attempts during arguments, like a softer tone or small joke. Accepting these offered olive branches keeps disagreements from spiraling.",
    "Show up for the boring logistics. Splitting chores, errands, and planning fairly is one of the most underrated love languages there is.",
    "Be honest about the small things. Trust is built in tiny moments of truth, and little lies quietly teach a partner to doubt you.",
    "Ask 'what do you need from me right now?' This single question cuts through guesswork and gives your partner exactly the support they want.",
    "Keep flirting with your long-term partner. A wink, a compliment, a stolen kiss reminds them they are still desired, not just dependable.",
    "Let them have a bad day. You don't need to fix every mood; sometimes the kindest thing is simply staying close while it passes.",
    "Talk about your relationship when things are good, not only when they're broken. Maintenance conversations prevent the bigger crisis ones.",
    "Honor the relationship in front of others. Speaking warmly about your partner when they're not around protects the marriage from outside corrosion.",
    "Notice your own role in recurring fights. Asking 'what's my 10 percent here?' turns a stalemate into a chance to grow together.",
    "Make decisions with each other, not for each other. Even small consultations communicate respect and remind your partner you're truly a team.",
    "Soothe yourself before big conversations. Approaching a hard talk calm rather than flooded helps you say what you mean instead of what stings.",
    "Welcome your partner's growth even when it's inconvenient. Loving someone means rooting for the person they're becoming, not just the one you met.",
    "Surprise them with effort, not just gifts. Planning a thoughtful evening or learning their favorite recipe shows love that money cannot buy.",
    "Be the safe place they exhale into. When home feels like the one spot they can fully relax, your relationship becomes their refuge.",
    "Ask about the highs and lows of their day. This simple ritual creates a daily window into your partner's inner emotional weather.",
    "Validate feelings even when you disagree with the logic. 'That makes sense you'd feel that way' calms storms far better than correcting facts.",
    "Keep promises small enough to keep. Reliability built on modest, honored commitments earns more trust than grand vows you struggle to fulfill.",
    "Take responsibility for your own happiness. A partner can enrich your joy, but expecting them to be its sole source is a heavy burden.",
    "Revisit your shared dreams now and then. Talking about the future you're building keeps daily friction in perspective and motivation alive.",
    "Touch base during long days apart. A quick midday message saying you're thinking of them keeps the thread of connection from going slack.",
    "Let go of being right to stay connected. Winning an argument while losing your partner's warmth is rarely a victory worth claiming.",
    "Notice the love languages you each speak. If you give words but they crave time, your effort may be missing them by inches.",
    "Create a no-phone zone at dinner. Undistracted meals are a daily chance to actually see and hear the person sitting across from you.",
    "Be gentle with your partner's insecurities. The places they feel fragile deserve your care, not your teasing, even in playful moments.",
    "Make space for both 'me time' and 'we time.' Honoring solitude and togetherness keeps the relationship from feeling like either prison or distance.",
    "Express desire and admiration openly. Telling your partner specifically what you find attractive about them rarely gets old and never goes unappreciated.",
    "Address resentment while it's small. Naming a minor frustration kindly prevents it from quietly hardening into a grudge you can't explain later.",
    "Show interest in their friends and family. Embracing the people your partner loves signals that you're invested in their whole life, not just them.",
    "Slow down when you sense disconnection. Rather than pulling further away, lean in gently and ask what's been on your partner's mind.",
    "Keep your partner's secrets and stories safe. Being someone they can confide in fully is the foundation of true emotional intimacy.",
    "In early dating, watch how they treat people who can do nothing for them. Kindness to waiters and strangers reveals real character.",
    "Don't rush to define everything. Letting early connection breathe lets you see who someone really is before labels create pressure or assumptions.",
    "Match their pace without losing yourself. Healthy new love balances enthusiasm with patience, letting trust grow naturally rather than forcing intensity.",
    "Look for someone whose ordinary days feel good, not just whose exciting ones do. Daily compatibility outlasts dramatic chemistry every time.",
    "Pay attention to how a date handles disappointment. The way someone responds to a small letdown previews how they'll handle bigger ones.",
    "In long-distance love, protect a shared sense of normal life. Watching a show together or running errands on video keeps closeness alive.",
    "Plan the next visit before the current goodbye. Having a date on the calendar gives long-distance couples something concrete to hold onto.",
    "Communicate generously across the miles. Distance makes assumptions dangerous, so over-share context and reassurance rather than leaving silence to be misread.",
    "Trust is the currency of distance. Without daily proximity, choosing to believe the best in each other becomes the relationship's backbone.",
    "Practice self-love so you bring fullness, not need. Liking your own company makes you a partner who chooses love rather than clinging to it.",
    "Speak to yourself the way you'd speak to your beloved. Harsh inner talk leaks into relationships, while self-kindness lets warmth flow outward.",
    "Heal your own old wounds rather than asking a partner to. A loving relationship can support your growth, but it can't replace your own work.",
    "Know your worth before you negotiate love. People who understand their value rarely settle for being someone's afterthought or backup plan.",
    "Sit with uncomfortable emotions instead of dumping them. Naming what you feel before reacting keeps your partner from absorbing your unprocessed storms.",
    "Develop the skill of staying regulated under stress. Your calm presence during your partner's hard moments is a quiet, powerful kind of love.",
    "Read the emotion beneath the words. When your partner snaps about dishes, the real message is often 'I feel unsupported,' and that deserves your attention.",
    "Lead with empathy when your partner is upset, even at you. Defending yourself can wait; feeling understood is what actually de-escalates the moment.",
    "Build emotional vocabulary together. Couples who can name feelings precisely tend to resolve conflict faster than those stuck on 'fine' and 'angry.'",
    "Let physical closeness be its own conversation. Holding each other without an agenda can communicate safety that words sometimes struggle to reach.",
    "Keep intimacy varied and unhurried. Connection deepens when you treat physical closeness as exploration and play rather than routine or obligation.",
    "Talk openly about what you each enjoy. Comfortable, honest conversation about intimacy builds trust and keeps desire from fading into guesswork.",
    "Be your partner's friend first. The couples who last tend to genuinely like each other, enjoying conversation long after the early sparks settle.",
    "Do small acts of service unprompted. Filling their gas tank or charging their phone quietly says 'I'm thinking of you' all day long.",
    "Compromise by trading priorities, not splitting everything in half. Giving in fully where it matters less to you earns goodwill where it matters more.",
    "Find the win-win before you settle for the trade-off. Many conflicts soften when you ask what would make you both genuinely satisfied.",
    "Hold boundaries with warmth, not coldness. You can say no clearly while still letting your partner feel loved and respected throughout.",
    "Don't punish vulnerability. When your partner opens up about a fear or mistake, meeting them with tenderness ensures they'll trust you again.",
    "Build a culture of appreciation, scanning for what's right. Couples who actively notice the good in each other report far more lasting happiness.",
    "Make your partner feel chosen, not just tolerated. Reminding them, in words and actions, that you'd pick them again keeps love feeling alive.",
    "Give your partner the benefit of the doubt out loud. Saying 'I'm sure you didn't mean it that way' diffuses tension before it builds.",
    "Treat your partner's irritations as data, not attacks. What annoys them often points to an unmet need worth understanding rather than dismissing.",
    "Keep curiosity bigger than judgment. When something puzzles you about your partner, ask with interest instead of concluding with criticism.",
    "Celebrate anniversaries of small things, like your first conversation. Honoring your shared history reminds you both how far you've come together.",
    "Let your partner influence you. Couples thrive when each person genuinely takes the other's opinions and preferences into account when making choices.",
    "Tend the friendship inside your romance. Shared inside jokes, easy conversation, and simple companionship are what carry love through the unglamorous seasons.",
    "Be quick to comfort, slow to criticize. The ratio of warmth to complaint you offer shapes whether home feels like safety or like judgment.",
    "Ask for what you want directly and kindly. Hinting breeds frustration, while a clear gentle request gives your partner a real chance to deliver.",
    "Stay teachable about how to love this specific person. What worked for past relationships may not fit; let your partner show you what they need.",
    "Acknowledge effort even when results fall short. Recognizing that your partner tried encourages them to keep trying instead of quietly giving up.",
    "Make eye contact when it matters. Looking at your partner while they share something important tells them they have your whole heart, not half.",
    "Don't outsource your relationship to autopilot. Long-term love needs intentional attention, or routine slowly replaces the connection that once felt effortless.",
    "Be willing to be the first to soften. Someone has to lower the sword first, and choosing to be that person is a strength, not a loss.",
    "Treat your partner's hobbies with respect even if you don't share them. Honoring what lights them up shows you cherish their whole self.",
    "Build trust by being consistent. Doing what you say, again and again, teaches your partner that they can finally let their guard down.",
    "Give reassurance before it's requested. Offering comfort when you sense your partner's worry shows an attentiveness that words of love alone cannot.",
    "Disagree without making it a referendum on the relationship. Not every conflict means something is wrong; sometimes it just means you're two people.",
    "Keep dating your partner. Planning intentional time to dress up, go out, and focus on each other keeps romance from quietly fading into logistics.",
    "Welcome feedback about how you love. Asking 'is there something you wish I did differently?' shows humility and a real desire to grow.",
    "Let small kindnesses accumulate. A relationship is built less from grand gestures than from a thousand tiny choices to be considerate and warm.",
    "Hold space for your partner's grief and stress without rushing to fix it. Sometimes presence, not advice, is the love they actually need.",
    "Be transparent about your phone and plans. Openness where others might hide builds a baseline of trust that makes everything else feel safe.",
    "Choose curiosity over jealousy. When insecurity flares, explore the fear within yourself rather than projecting suspicion onto a partner who's done nothing wrong.",
    "Make 'we'll figure it out together' your default. Facing uncertainty as a united front turns scary unknowns into shared adventures you can handle.",
    "Compliment who they are, not just what they do. Telling your partner you admire their kindness or courage nourishes them more deeply than praise for tasks.",
    "Protect transition times, like the first minutes home. Greeting each other with warmth instead of complaints sets the emotional tone for the hours ahead.",
    "Remember the things they tell you matter. Following up on a worry they mentioned days ago proves you were truly listening all along.",
    "Stay on the same side of the table. When a problem arises, imagine sitting beside your partner facing it, rather than across from them blaming.",
    "Keep your love private when it needs protecting. Not every detail belongs on social media; some intimacy stays stronger when it stays between you.",
    "Be generous with credit and slow with blame. Naming what your partner did right, and owning your own missteps, keeps resentment from taking root.",
    "Let affection be unconditional, not a reward. Withholding warmth to make a point teaches your partner that your love comes with terms attached.",
    "Grow together by trying new things side by side. Shared novelty, from travel to a new class, reignites the excitement that early love had naturally.",
    "End each day with a moment of connection. A few honest words or a long hug before sleep stitches you back together after the day pulls you apart.",
  ],
  facts: [
    "When you fall in love, your brain floods with dopamine, the same reward chemical involved in motivation and pleasure, which is why new romance can feel almost addictive.",
    "Oxytocin, often called the 'bonding hormone,' surges during hugs, hand-holding, and closeness, helping partners feel attached and trusting toward each other.",
    "Studies suggest that gazing into each other's eyes for a few minutes can increase feelings of intimacy, even between relative strangers.",
    "The phrase 'falling in love' may be more literal than poetic; early romance can lower serotonin to levels similar to those seen in obsessive thinking.",
    "Researchers have found that holding a loved one's hand can measurably reduce a person's perception of physical pain and stress.",
    "Your heartbeat can actually synchronize with a romantic partner's when you sit close and gaze at each other, according to studies on couples.",
    "The ancient Greeks described several types of love, including eros (passion), philia (friendship), and agape (selfless love), recognizing love as far more than one feeling.",
    "Prairie voles are famous in science for forming lifelong pair bonds, and studying them has taught researchers a great deal about the chemistry of monogamy.",
    "The tradition of the diamond engagement ring became widespread largely after a famous 20th-century advertising campaign declared 'A Diamond Is Forever.'",
    "Butterflies in your stomach during early love are real; the adrenaline of attraction can divert blood from your digestive system, creating that fluttery feeling.",
    "Studies suggest that couples who laugh together regularly tend to report higher relationship satisfaction and feel more connected over time.",
    "The wedding tradition of wearing a ring on the fourth finger traces back to an old belief in a 'vena amoris,' a vein running straight to the heart.",
    "Romantic love and deep attachment activate slightly different brain systems, which helps explain how passion can mature into a calmer, steadier bond.",
    "Swans, often seen as symbols of love, frequently form long-lasting pair bonds, sometimes staying with the same mate for many years.",
    "Researchers estimate it can take anywhere from a few seconds to a few minutes for someone to decide whether they feel attracted to a new person.",
    "The 'honeymoon phase' of intense early passion typically lasts somewhere between several months and about two years before settling into deeper attachment.",
    "Cuddling and physical affection can trigger the release of endorphins, the body's natural feel-good chemicals that also help reduce stress.",
    "In many cultures historically, marriage was arranged for economic or political reasons, and the idea of marrying primarily for love is relatively modern.",
    "Studies suggest that people often feel most attracted to faces that are roughly symmetrical, which some scientists link to subconscious cues about health.",
    "The word 'romance' originally referred to a style of medieval storytelling, only later coming to mean the passionate love we associate with it today.",
    "Smell plays a surprising role in attraction; research suggests scent can subtly influence who we find appealing as a potential partner.",
    "Long-term couples sometimes begin to resemble each other slightly, a phenomenon researchers link partly to decades of sharing expressions, environment, and emotions.",
    "The custom of kissing under mistletoe dates back centuries and was once linked to ancient traditions of peace, fertility, and goodwill.",
    "Falling in love can temporarily reduce activity in brain regions tied to critical judgment, which is part of why love can feel a little blind.",
    "Studies suggest that simply expecting someone to be warm and friendly can lead you to behave in ways that make them respond warmly in return.",
    "Albatrosses perform elaborate courtship dances and can maintain the same partnership across many breeding seasons, sometimes for much of their long lives.",
    "The brain in early love can resemble the brain on certain rewards, lighting up reward centers that drive us to seek closeness with our partner.",
    "Researchers have found that couples who regularly express gratitude to each other tend to feel more committed and satisfied in their relationship.",
    "The heart-shape symbol we associate with love doesn't actually resemble a human heart; its origins are debated and likely stylized over centuries.",
    "Touch is one of the first senses to develop, and gentle physical affection remains a powerful way humans communicate love throughout life.",
    "Studies suggest that doing new and exciting activities together can boost relationship satisfaction by recreating some of the novelty of early romance.",
    "Some penguins are known for courtship rituals that include presenting a carefully chosen pebble to a potential mate.",
    "The hormone vasopressin, alongside oxytocin, is thought to play an important role in long-term bonding and attachment between partners.",
    "Valentine's Day traces its roots to ancient festivals and the legend of Saint Valentine, evolving over centuries into today's celebration of romantic love.",
    "Research suggests that people tend to feel closer to those they self-disclose to, which is why sharing personal stories can accelerate intimacy.",
    "Blushing, a uniquely human response, can signal attraction and embarrassment, and some researchers think it evolved partly as an honest social signal.",
    "The 'mere exposure effect' means we often grow to like people more simply by seeing them repeatedly, which is why proximity can spark romance.",
    "Studies suggest that couples who navigate conflict with humor and gentleness rather than contempt are far more likely to stay together.",
    "Seahorses are famous for an unusual arrangement in which the male carries and nurtures the developing young.",
    "The chemical phenylethylamine, sometimes nicknamed the 'love molecule,' is released during attraction and is also found naturally in small amounts in chocolate.",
    "Across many cultures and eras, poets have treated love as one of humanity's central themes, suggesting its emotional pull is remarkably universal.",
    "Research on 'attachment styles' suggests our early bonds with caregivers can influence how secure or anxious we feel in adult romantic relationships.",
    "Studies suggest that even brief acts of kindness between partners, like making tea or a quick text, accumulate into lasting relationship goodwill.",
    "The custom of a wedding cake has ancient roots, with various cultures historically using bread or cake in marriage rituals symbolizing prosperity.",
    "Some scientists believe music's power to stir emotion is closely tied to bonding, which may be why love songs are found in nearly every culture.",
    "Researchers have observed that newly-in-love couples sometimes experience reduced appetite and trouble sleeping, partly due to surging stress and reward chemicals.",
    "The honeybee 'waggle dance' isn't romance, but many animal courtship displays are elaborate performances meant to attract and impress a mate.",
    "Studies suggest that feeling appreciated is one of the strongest predictors of whether people feel satisfied and want to stay in a relationship.",
    "The tradition of carrying a bride over the threshold has roots in ancient customs once believed to protect the couple from bad luck.",
    "Love and pain can share overlapping brain pathways, which may help explain why heartbreak can genuinely feel physically painful.",
    "Researchers studying long-married couples have found that a small number who report still feeling intense love show brain activity resembling early romance.",
    "Many bird species sing duets with their mates, with partners coordinating their calls so precisely it can sound like a single voice.",
    "Studies suggest that couples tend to be happier when they maintain a healthy balance of positive to negative interactions in daily life.",
    "The exchange of rings as a symbol of commitment is an ancient practice, appearing in various forms across many early civilizations.",
    "Physical attraction can be influenced by something as simple as a racing heartbeat; arousal from excitement is sometimes misread as romantic attraction.",
    "Some researchers describe romantic love as having three broad components: lust, attraction, and attachment, each driven by different brain chemistry.",
    "Wolves typically form strong pair bonds, with a bonded pair often forming the social core of their pack.",
    "Studies suggest that partners who feel their relationship is a place of acceptance are more willing to take healthy emotional risks with each other.",
    "The color red has been linked in some studies to perceptions of attraction, with people sometimes rating others as more appealing when wearing it.",
    "Across history, love letters have been treasured keepsakes, and surviving examples from centuries ago reveal that longing and devotion change little over time.",
    "Researchers have found that supportive touch from a partner can help lower blood pressure and ease the body's response to stress.",
    "Some species of penguins, gibbons, and certain foxes are noted by biologists for forming notably strong and lasting pair bonds.",
    "The 'Romeo and Juliet effect' describes how outside opposition to a relationship can sometimes intensify, rather than weaken, a couple's passion.",
    "Studies suggest that simply thinking about a loved one can activate reward areas of the brain and provide a measurable buffer against stress.",
    "Many cultures historically exchanged tokens of betrothal, from rings to ribbons to coins, long before modern engagement traditions took shape.",
    "Research suggests that people often underestimate how much a sincere compliment will brighten their partner's day, leaving kind words unspoken too often.",
    "Gibbons are known among primates for forming long-term pair bonds and even singing coordinated morning calls together.",
    "The feeling of 'chemistry' with someone may partly reflect how comfortable and at ease your nervous system feels in their presence.",
    "Studies suggest that couples who share and celebrate good news together, not just support each other in hard times, tend to feel more connected.",
    "Beavers typically pair up and work together to build and maintain their lodges, sharing the labor of raising their young.",
    "The phrase 'tying the knot' likely comes from old marriage customs in various cultures that literally involved binding the couple's hands together.",
    "Research on attraction suggests that a sense of humor is one of the most commonly valued traits people seek in a long-term partner.",
    "Some scientists believe that the human tendency to form pair bonds may have evolved partly to support the long task of raising children.",
    "Studies suggest that couples who maintain shared rituals, however small, report a stronger sense of identity and belonging together.",
    "The myth of Cupid, the winged figure who strikes hearts with arrows, comes from Roman mythology and the older Greek figure of Eros.",
    "Researchers have found that feeling understood by a partner is closely tied to feeling loved, sometimes even more than grand romantic gestures.",
    "Certain antelope, cranes, and parrots are among the many animals biologists have observed maintaining lasting bonds with a single partner.",
    "Studies suggest that the way couples handle small daily annoyances predicts long-term satisfaction more reliably than how they handle rare big crises.",
    "The tradition of a 'honeymoon' getaway after marriage became popular in the 19th century, though the word itself is far older.",
    "Research suggests that physical closeness during sleep, like a partner's nearby presence, can subtly improve feelings of safety and rest.",
    "Some flowers, especially the red rose, became enduring symbols of love through centuries of poetry, art, and cultural tradition.",
    "Studies suggest that couples who can repair after conflict quickly, rather than perfectly avoiding conflict, tend to have the strongest relationships.",
    "The brain's reward system can respond to a partner's smile in ways similar to other deeply rewarding experiences, reinforcing the pull of love.",
    "Many cultures developed matchmaking traditions, and professional matchmakers have existed in various societies for hundreds of years.",
    "Research suggests that expressing affection through your partner's preferred 'love language' tends to land more powerfully than affection on your own terms.",
    "Storks, often associated with babies in folklore, are also known for frequently returning to the same nest and mate year after year.",
    "Studies suggest that nostalgia about shared memories can strengthen a couple's bond by reminding them of their history and resilience together.",
    "The custom of bridesmaids may trace back to ancient traditions in which similarly dressed attendants were thought to confuse evil spirits.",
    "Research suggests that couples who maintain a sense of 'we' rather than 'me versus you' during disagreements tend to resolve them more constructively.",
    "Bald eagles often form long-term pair bonds and may return to the same nesting site together across many years.",
    "Studies suggest that anticipation can heighten happiness, which is why looking forward to time with a partner can be almost as joyful as the time itself.",
    "The tradition of giving flowers as a romantic gesture has been documented across many cultures and centuries as a language of affection.",
    "Research suggests that people in supportive relationships tend to recover from illness and stress somewhat faster than those who feel isolated.",
    "Some species of cichlid fish are noted by biologists for cooperating as pairs to guard and care for their eggs and young.",
    "Studies suggest that couples who express physical affection regularly, beyond just during conflict resolution, tend to maintain stronger emotional bonds.",
    "The notion of a 'soulmate' has appeared in philosophy since antiquity, including a famous myth recounted in Plato's writings.",
    "Research suggests that simply having a partner you can confide in is associated with greater resilience during life's most stressful moments.",
    "French angelfish are among the species biologists have observed traveling and defending territory as faithful, cooperative pairs.",
    "Studies suggest that the early-relationship habit of idealizing a partner, within reason, can actually help couples stay satisfied over time.",
    "The handshake and the kiss as greetings both have deep historical roots, with the romantic kiss appearing across many ancient cultures.",
    "Research suggests that couples who make time for shared leisure, even brief moments, report feeling closer and more like a team.",
    "Some scientists think the universal human capacity for love may be one of evolution's most powerful tools for cooperation and survival.",
    "Studies suggest that feeling secure in a relationship frees people to be more adventurous and confident in the rest of their lives.",
    "The tradition of love poetry stretches back thousands of years, with some of the oldest known love poems written on ancient clay tablets.",
    "Research suggests that partners often feel most loved not during dramatic gestures, but in small, consistent moments of attention and care.",
    "Certain owl species form lasting pair bonds and cooperate closely to raise their owlets, sharing hunting and nesting duties.",
    "Studies suggest that couples who maintain individual friendships and interests, alongside their relationship, tend to report greater long-term happiness together.",
    "The veil worn by some brides has ancient origins, appearing in various cultures as a symbol of modesty, mystery, or protection.",
    "Research suggests that the experience of awe, like watching a sunset together, can deepen a couple's sense of connection and shared meaning.",
    "Many cultures have folk traditions about love charms and tokens, reflecting a timeless human wish to attract and keep affection.",
    "Studies suggest that responsiveness, the sense that your partner truly notices and cares about your needs, is central to feeling deeply loved.",
    "The idea of celebrating a wedding anniversary with specific gifts, like paper or gold for certain years, developed gradually over the last few centuries.",
    "Research suggests that even imagining future moments with a partner can strengthen present-day commitment and motivation to nurture the relationship.",
    "Some macaroni penguins and other seabirds reunite with the same mate each breeding season after spending months apart at sea.",
    "Studies suggest that the simple act of saying 'thank you' to a partner can set off a positive cycle of appreciation and generosity.",
    "The word 'cuddle' may sound modern, but humans have sought the comfort of close physical contact since the earliest moments of our species.",
    "Research suggests that couples who view challenges as shared problems to solve, rather than personal failings, tend to grow stronger through hardship.",
  ],
  quotes: [
    { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
    { text: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
    { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle" },
    { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
    { text: "We are most alive when we're in love.", author: "John Updike" },
    { text: "Love is that condition in which the happiness of another person is essential to your own.", author: "Robert A. Heinlein" },
    { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
    { text: "There is no remedy for love but to love more.", author: "Henry David Thoreau" },
    { text: "Love does not consist in gazing at each other, but in looking outward together in the same direction.", author: "Antoine de Saint-Exupéry" },
    { text: "If I know what love is, it is because of you.", author: "Hermann Hesse" },
    { text: "The greatest happiness of life is the conviction that we are loved.", author: "Victor Hugo" },
    { text: "Love is friendship that has caught fire.", author: "Ann Landers" },
    { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
    { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu" },
    { text: "Love is when the other person's happiness is more important than your own.", author: "H. Jackson Brown Jr." },
    { text: "The heart has its reasons which reason knows nothing of.", author: "Blaise Pascal" },
    { text: "A successful marriage requires falling in love many times, always with the same person.", author: "Mignon McLaughlin" },
    { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
    { text: "But the most beautiful things in the world cannot be seen or even touched, they must be felt with the heart.", author: "Helen Keller" },
    { text: "Love is not finding someone to live with. It's finding someone you can't live without.", author: "Rafael Ortiz" },
    { text: "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", author: "Maya Angelou" },
    { text: "Love is an irresistible desire to be irresistibly desired.", author: "Robert Frost" },
    { text: "You don't marry someone you can live with, you marry the person who you cannot live without.", author: "Unknown" },
    { text: "The course of true love never did run smooth.", author: "William Shakespeare" },
    { text: "Love all, trust a few, do wrong to none.", author: "William Shakespeare" },
    { text: "Love looks not with the eyes, but with the mind.", author: "William Shakespeare" },
    { text: "I have found the one whom my soul loves.", author: "Song of Solomon" },
    { text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", author: "1 Corinthians 13:4" },
    { text: "At the touch of love everyone becomes a poet.", author: "Plato" },
    { text: "The giving of love is an education in itself.", author: "Eleanor Roosevelt" },
    { text: "Love is the flower you've got to let grow.", author: "John Lennon" },
    { text: "All you need is love.", author: "John Lennon" },
    { text: "Love is or it ain't. Thin love ain't love at all.", author: "Toni Morrison" },
    { text: "Love takes off masks that we fear we cannot live without and know we cannot live within.", author: "James Baldwin" },
    { text: "Love is a fruit in season at all times, and within reach of every hand.", author: "Mother Teresa" },
    { text: "Spread love everywhere you go. Let no one ever come to you without leaving happier.", author: "Mother Teresa" },
    { text: "We can only learn to love by loving.", author: "Iris Murdoch" },
    { text: "Love isn't something you find. Love is something that finds you.", author: "Loretta Young" },
    { text: "The art of love is largely the art of persistence.", author: "Albert Ellis" },
    { text: "To love at all is to be vulnerable.", author: "C. S. Lewis" },
    { text: "Love is not affectionate feeling, but a steady wish for the loved person's ultimate good.", author: "C. S. Lewis" },
    { text: "Love is the whole thing. We are only pieces.", author: "Rumi" },
    { text: "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.", author: "Rumi" },
    { text: "Let the beauty of what you love be what you do.", author: "Rumi" },
    { text: "Love is the bridge between you and everything.", author: "Rumi" },
    { text: "Gravitation is not responsible for people falling in love.", author: "Albert Einstein" },
    { text: "Love consists in this, that two solitudes protect and touch and greet each other.", author: "Rainer Maria Rilke" },
    { text: "Once you have learned to love, you will have learned to live.", author: "Unknown" },
    { text: "Love is composed of many things, but its foundation is friendship and trust.", author: "Unknown" },
    { text: "When you love someone, you love the person as they are, and not as you'd like them to be.", author: "Leo Tolstoy" },
    { text: "He stepped down, trying not to look long at her, as if she were the sun, yet he saw her, like the sun, even without looking.", author: "Leo Tolstoy" },
    { text: "Doubt thou the stars are fire; doubt that the sun doth move; doubt truth to be a liar; but never doubt I love.", author: "William Shakespeare" },
    { text: "How do I love thee? Let me count the ways.", author: "Elizabeth Barrett Browning" },
    { text: "Love is anterior to life, posterior to death, initial of creation, and the exponent of breath.", author: "Emily Dickinson" },
    { text: "That love is all there is, is all we know of love.", author: "Emily Dickinson" },
    { text: "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.", author: "A. A. Milne" },
    { text: "Love is a canvas furnished by nature and embroidered by imagination.", author: "Voltaire" },
    { text: "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.", author: "Helen Keller" },
    { text: "A flower cannot blossom without sunshine, and man cannot live without love.", author: "Max Müller" },
    { text: "Love is like the wind, you can't see it but you can feel it.", author: "Nicholas Sparks" },
    { text: "The simple lack of her is more to me than others' presence.", author: "Edward Thomas" },
    { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J. R. R. Tolkien" },
    { text: "Love is the master key that opens the gates of happiness.", author: "Oliver Wendell Holmes" },
    { text: "We are shaped and fashioned by what we love.", author: "Johann Wolfgang von Goethe" },
    { text: "Love, and a cough, cannot be hid.", author: "George Herbert" },
    { text: "Two persons love in passing the world to one another.", author: "Unknown" },
    { text: "Love makes your soul crawl out from its hiding place.", author: "Zora Neale Hurston" },
    { text: "There is always some madness in love. But there is also always some reason in madness.", author: "Friedrich Nietzsche" },
    { text: "Love is the only force capable of transforming an enemy into a friend.", author: "Martin Luther King Jr." },
    { text: "We must develop and maintain the capacity to forgive.", author: "Martin Luther King Jr." },
    { text: "The way to love anything is to realize that it may be lost.", author: "G. K. Chesterton" },
    { text: "Loving is never a waste of time.", author: "Astrid Alauda" },
    { text: "Love is the voice under all silences, the hope which has no opposite in fear.", author: "E. E. Cummings" },
    { text: "I carry your heart with me. I carry it in my heart.", author: "E. E. Cummings" },
    { text: "Love grows by giving. The love we give away is the only love we keep.", author: "Elbert Hubbard" },
    { text: "To love is nothing. To be loved is something. But to love and be loved, that's everything.", author: "T. Tolis" },
    { text: "Love planted a rose, and the world turned sweet.", author: "Katharine Lee Bates" },
    { text: "Love is the expansion of two natures in such fashion that each includes the other.", author: "Felix Adler" },
    { text: "Tell me whom you love, and I will tell you who you are.", author: "Houssaye" },
    { text: "Where you used to be, there is a hole in the world, which I find myself constantly walking around in the daytime.", author: "Edna St. Vincent Millay" },
  ],
};
