import type { RotationalContent } from '@/lib/dailyContentTypes';

export const es: RotationalContent = {
  tips: [
    "Escucha para comprender, no para responder. Hacer una pausa antes de contestar le demuestra a tu pareja que sus palabras realmente calaron, y ese pequeño hábito fortalece la confianza con el tiempo.",
    "Da las gracias por las cosas cotidianas. Notar el café preparado o los platos lavados le recuerda a tu pareja que su esfuerzo diario nunca pasa desapercibido.",
    "Cuando surja un conflicto, ataquen el problema juntos en lugar de atacarse entre ustedes. Son un equipo enfrentando un asunto, no rivales tratando de ganar un punto.",
    "Reserven tiempo sin prisas para estar juntos, aunque sean solo veinte minutos. La conexión rara vez ocurre en los huecos; crece cuando deliberadamente le haces espacio.",
    "Pregúntale a tu pareja cómo prefiere que la consueles. Algunos buscan soluciones, otros un abrazo y silencio, y adivinar mal puede sentirse como distancia.",
    "Repara rápido después de una discusión. Un acercamiento sincero una vez que los ánimos se calman importa mucho más que fingir que la fricción nunca existió.",
    "La curiosidad mantiene vivo el amor. Sigue haciéndole preguntas nuevas a tu pareja de toda la vida, porque la gente cambia en silencio y lo más interesante sigue revelándose.",
    "Expresa tu agradecimiento en voz alta, no solo en tu cabeza. La gratitud callada solo te reconforta a ti; la gratitud expresada reconforta a quien amas.",
    "Protege tu relación del desprecio. Poner los ojos en blanco y el sarcasmo corroen la conexión más rápido que casi cualquier cosa, así que elige el respeto incluso cuando estés frustrado.",
    "Haz que cuenten los intentos de conexión. Cuando tu pareja comparte algo pequeño, volverte hacia ella con atención es el pegamento silencioso del amor duradero.",
    "Pide perdón sin añadir un «pero». Una disculpa limpia asume tu parte por completo, mientras que una condicionada devuelve la culpa al otro lado de la mesa.",
    "Conserven algunos rituales que sean solo suyos. Un paseo dominical o el café compartido por la mañana crea un ritmo constante que ancla dos vidas ajetreadas.",
    "Asume buena intención antes de pensar lo peor. La mayoría de los momentos hirientes vienen de la torpeza o el estrés, no de una pareja que en secreto desea hacerte daño.",
    "Hablen de dinero pronto y a menudo. Ponerse de acuerdo sobre gastar, ahorrar y las metas evita el resentimiento silencioso que las finanzas pueden generar.",
    "Deja que tu pareja sea diferente de ti. La compatibilidad no es igualdad; son dos personas distintas que eligen honrar el mundo interior del otro.",
    "Date cuenta de lo que tu pareja está cargando. Un suave «te ves cansado, yo me encargo de la cena» puede decir te amo más fuerte que las palabras.",
    "Conserva algo de independencia dentro de la unión. Cultivar tus propias amistades y pasiones te convierte en una pareja más interesante y con más energía al volver a casa.",
    "Elogia en público, resuelve los problemas en privado. Enaltecer a tu pareja delante de otros y manejar la fricción discretamente protege tanto el orgullo como la confianza.",
    "Cambia «tú siempre» y «tú nunca» por «yo siento». Hablar desde tu experiencia invita a la comprensión, mientras que las acusaciones generales provocan defensiva.",
    "El contacto físico importa incluso cuando nada anda mal. Una mano en el hombro o un abrazo rápido mantienen al cuerpo recordando que es amado.",
    "Elige a tu pareja de nuevo en los días difíciles. El amor no es solo la chispa en la que caíste, sino la decisión que renuevas cuando las cosas se ponen pesadas.",
    "Interésate por su mundo. Hacer preguntas reales sobre el trabajo, las preocupaciones y los sueños de tu pareja le dice que su vida de verdad te importa.",
    "No lleves la cuenta. La generosidad que se da esperando un pago es una transacción; el amor florece cuando das con libertad y confías en que la balanza se equilibrará.",
    "Nombra tus necesidades con claridad. Tu pareja no puede leerte la mente, y esperar en silencio a que adivine suele terminar en decepción para ambos.",
    "Rían juntos a menudo. El humor compartido baja la tensión, construye intimidad y te recuerda que la persona a tu lado también es tu compañía favorita.",
    "Entrégate por completo en los reencuentros. Saludar a tu pareja con calidez al reconectarse, con el teléfono abajo y la mirada en alto, marca el tono de la noche.",
    "Perdona rápido lo pequeño. Aferrarse a agravios menores levanta un muro ladrillo a ladrillo hasta que ya no pueden alcanzarse el uno al otro.",
    "Celebra los triunfos de tu pareja como propios. El gozo genuino por su éxito, sin envidia, es una de las formas más profundas de amor.",
    "Pregunta antes de dar por hecho que se han distanciado. Un simple «¿cómo vamos últimamente?» suele revelar una conexión que la distancia solo parecía amenazar.",
    "Respeten los límites del otro sin tomarlos como algo personal. Un límite es información sobre las necesidades de tu pareja, no un rechazo hacia ti.",
    "Haz intentos de reconciliación durante las discusiones, como un tono más suave o una pequeña broma. Aceptar esas ramas de olivo evita que los desacuerdos se desborden.",
    "Hazte presente para la logística aburrida. Repartir las tareas, los mandados y la planificación de forma justa es uno de los lenguajes del amor más subestimados que existen.",
    "Sé honesto en las cosas pequeñas. La confianza se construye en diminutos momentos de verdad, y las mentiritas le enseñan en silencio a tu pareja a dudar de ti.",
    "Pregunta «¿qué necesitas de mí ahora mismo?». Esta sola pregunta corta las suposiciones y le da a tu pareja exactamente el apoyo que quiere.",
    "Sigue coqueteando con tu pareja de toda la vida. Un guiño, un cumplido, un beso robado le recuerdan que sigue siendo deseada, no solo confiable.",
    "Permítele tener un mal día. No necesitas arreglar cada estado de ánimo; a veces lo más amable es simplemente quedarte cerca mientras pasa.",
    "Hablen de su relación cuando las cosas van bien, no solo cuando están rotas. Las conversaciones de mantenimiento previenen las de crisis mayores.",
    "Honra la relación delante de los demás. Hablar con cariño de tu pareja cuando no está presente protege el vínculo de la corrosión externa.",
    "Reconoce tu propio papel en las peleas que se repiten. Preguntarte «¿cuál es mi 10 por ciento aquí?» convierte un punto muerto en una oportunidad de crecer juntos.",
    "Tomen decisiones el uno con el otro, no el uno por el otro. Incluso las consultas pequeñas comunican respeto y le recuerdan a tu pareja que de verdad son un equipo.",
    "Cálmate antes de las conversaciones importantes. Abordar una charla difícil sereno en lugar de desbordado te ayuda a decir lo que sientes en vez de lo que hiere.",
    "Recibe con gusto el crecimiento de tu pareja aunque sea inconveniente. Amar a alguien significa apoyar a la persona en la que se está convirtiendo, no solo a la que conociste.",
    "Sorpréndela con esfuerzo, no solo con regalos. Planear una velada con cariño o aprender su receta favorita demuestra un amor que el dinero no puede comprar.",
    "Sé el lugar seguro donde pueda soltar el aire. Cuando el hogar se siente como el único sitio donde puede relajarse del todo, tu relación se vuelve su refugio.",
    "Pregunta por lo mejor y lo peor de su día. Este sencillo ritual crea una ventana diaria al clima emocional interior de tu pareja.",
    "Valida los sentimientos aunque no estés de acuerdo con la lógica. Un «tiene sentido que te sientas así» calma tormentas mucho mejor que corregir los hechos.",
    "Haz promesas lo bastante pequeñas como para cumplirlas. La fiabilidad construida sobre compromisos modestos y honrados gana más confianza que grandes votos que te cuesta cumplir.",
    "Hazte responsable de tu propia felicidad. Una pareja puede enriquecer tu alegría, pero esperar que sea su única fuente es una carga muy pesada.",
    "Revisen de vez en cuando sus sueños compartidos. Hablar del futuro que están construyendo mantiene en perspectiva la fricción diaria y viva la motivación.",
    "Manténganse en contacto durante los largos días separados. Un mensaje rápido a mediodía diciendo que piensas en ella evita que el hilo de la conexión se afloje.",
    "Suelta la necesidad de tener razón para seguir conectado. Ganar una discusión mientras pierdes la calidez de tu pareja rara vez es una victoria que valga la pena reclamar.",
    "Fíjate en los lenguajes del amor que cada uno habla. Si tú das palabras pero ella anhela tiempo, tu esfuerzo puede estar errándole por centímetros.",
    "Crea una zona libre de teléfonos en la cena. Las comidas sin distracciones son una oportunidad diaria de ver y escuchar de verdad a la persona frente a ti.",
    "Sé delicado con las inseguridades de tu pareja. Los lugares donde se siente frágil merecen tu cuidado, no tus burlas, ni siquiera en momentos de juego.",
    "Haz espacio tanto para el «tiempo para mí» como para el «tiempo para nosotros». Honrar la soledad y la unión evita que la relación se sienta como una cárcel o como distancia.",
    "Expresa el deseo y la admiración abiertamente. Decirle a tu pareja qué te atrae específicamente de ella rara vez cansa y nunca pasa sin ser apreciado.",
    "Atiende el resentimiento mientras es pequeño. Nombrar con amabilidad una frustración menor evita que se endurezca en silencio hasta volverse un rencor que luego no sabrás explicar.",
    "Muestra interés por sus amistades y su familia. Acoger a las personas que tu pareja ama indica que te involucras en toda su vida, no solo en ella.",
    "Frena cuando percibas desconexión. En lugar de alejarte más, acércate con suavidad y pregúntale qué ha tenido en mente tu pareja.",
    "Guarda a salvo los secretos y las historias de tu pareja. Ser alguien en quien puede confiar plenamente es la base de la verdadera intimidad emocional.",
    "Al comienzo de una relación, observa cómo trata a quienes no pueden hacer nada por ella. La amabilidad con los meseros y los desconocidos revela el carácter real.",
    "No te apures en definirlo todo. Dejar respirar la conexión temprana te permite ver quién es alguien realmente antes de que las etiquetas creen presión o suposiciones.",
    "Sigue su ritmo sin perderte a ti mismo. Un amor nuevo y sano equilibra el entusiasmo con la paciencia, dejando que la confianza crezca con naturalidad en vez de forzar la intensidad.",
    "Busca a alguien cuyos días ordinarios se sientan bien, no solo los emocionantes. La compatibilidad cotidiana supera siempre a la química dramática.",
    "Presta atención a cómo maneja una cita la decepción. La forma en que alguien responde a un pequeño contratiempo anticipa cómo manejará los mayores.",
    "En el amor a distancia, protejan una sensación compartida de vida normal. Ver una serie juntos o hacer mandados por videollamada mantiene viva la cercanía.",
    "Planeen la próxima visita antes de la despedida actual. Tener una fecha en el calendario les da a las parejas a distancia algo concreto a lo que aferrarse.",
    "Comuníquense con generosidad a pesar de los kilómetros. La distancia vuelve peligrosas las suposiciones, así que comparte de más el contexto y la tranquilidad en vez de dejar que el silencio se malinterprete.",
    "La confianza es la moneda de la distancia. Sin la cercanía diaria, elegir creer lo mejor del otro se convierte en la columna vertebral de la relación.",
    "Practica el amor propio para aportar plenitud, no carencia. Disfrutar de tu propia compañía te convierte en una pareja que elige el amor en lugar de aferrarse a él.",
    "Háblate como le hablarías a tu ser amado. El diálogo interior duro se filtra en las relaciones, mientras que la amabilidad contigo mismo deja que la calidez fluya hacia afuera.",
    "Sana tus propias heridas viejas en lugar de pedirle a tu pareja que lo haga. Una relación amorosa puede apoyar tu crecimiento, pero no puede reemplazar tu propio trabajo.",
    "Conoce tu valor antes de negociar el amor. Quienes entienden cuánto valen rara vez se conforman con ser la opción de último momento de alguien.",
    "Acompaña las emociones incómodas en vez de descargarlas. Nombrar lo que sientes antes de reaccionar evita que tu pareja absorba tus tormentas sin procesar.",
    "Desarrolla la habilidad de mantenerte sereno bajo estrés. Tu presencia calmada durante los momentos difíciles de tu pareja es una forma silenciosa y poderosa de amor.",
    "Lee la emoción debajo de las palabras. Cuando tu pareja se enoja por los platos, el mensaje real suele ser «me siento sin apoyo», y eso merece tu atención.",
    "Guíate por la empatía cuando tu pareja esté molesta, incluso contigo. Defenderte puede esperar; sentirse comprendido es lo que de verdad calma el momento.",
    "Construyan juntos un vocabulario emocional. Las parejas que pueden nombrar los sentimientos con precisión suelen resolver los conflictos más rápido que quienes se quedan en «bien» y «enojado».",
    "Deja que la cercanía física sea una conversación en sí misma. Abrazarse sin agenda puede comunicar una seguridad que las palabras a veces no alcanzan.",
    "Mantengan la intimidad variada y sin prisas. La conexión se profundiza cuando tratan la cercanía física como exploración y juego, no como rutina u obligación.",
    "Hablen abiertamente de lo que cada uno disfruta. Una conversación cómoda y honesta sobre la intimidad construye confianza y evita que el deseo se desvanezca en conjeturas.",
    "Sé amigo de tu pareja antes que nada. Las parejas que perduran tienden a quererse de verdad, disfrutando de la conversación mucho después de que las primeras chispas se asienten.",
    "Haz pequeños gestos de servicio sin que te los pidan. Llenarle el tanque de gasolina o cargarle el teléfono en silencio dice «pienso en ti» durante todo el día.",
    "Cedan intercambiando prioridades, no dividiéndolo todo por la mitad. Ceder por completo donde te importa menos te gana buena voluntad donde te importa más.",
    "Busca la solución en la que ambos ganan antes de conformarte con el sacrificio. Muchos conflictos se suavizan cuando preguntas qué los dejaría a ambos genuinamente satisfechos.",
    "Sostén tus límites con calidez, no con frialdad. Puedes decir que no con claridad y, aun así, hacer que tu pareja se sienta amada y respetada en todo momento.",
    "No castigues la vulnerabilidad. Cuando tu pareja se abre sobre un miedo o un error, recibirla con ternura garantiza que volverá a confiar en ti.",
    "Cultiva una cultura de aprecio, buscando lo que está bien. Las parejas que activamente notan lo bueno del otro reportan una felicidad mucho más duradera.",
    "Haz que tu pareja se sienta elegida, no solo tolerada. Recordarle, con palabras y acciones, que volverías a elegirla mantiene vivo el amor.",
    "Dale a tu pareja el beneficio de la duda en voz alta. Decir «seguro que no lo dijiste con esa intención» disipa la tensión antes de que crezca.",
    "Trata las molestias de tu pareja como datos, no como ataques. Lo que la irrita a menudo apunta a una necesidad insatisfecha que vale la pena entender en lugar de descartar.",
    "Mantén la curiosidad más grande que el juicio. Cuando algo de tu pareja te desconcierte, pregunta con interés en vez de concluir con crítica.",
    "Celebren aniversarios de cosas pequeñas, como su primera conversación. Honrar su historia compartida les recuerda a ambos cuánto han avanzado juntos.",
    "Deja que tu pareja te influya. Las parejas prosperan cuando cada persona toma genuinamente en cuenta las opiniones y preferencias del otro al decidir.",
    "Cuida la amistad dentro de tu romance. Las bromas privadas, la conversación fácil y la simple compañía son lo que sostiene al amor en las temporadas poco glamorosas.",
    "Sé rápido para consolar y lento para criticar. La proporción de calidez frente a queja que ofreces define si el hogar se siente como refugio o como juicio.",
    "Pide lo que quieres de forma directa y amable. Las indirectas siembran frustración, mientras que una petición clara y suave le da a tu pareja una verdadera oportunidad de responder.",
    "Mantente dispuesto a aprender cómo amar a esta persona en concreto. Lo que funcionó en relaciones pasadas puede no encajar; deja que tu pareja te muestre lo que necesita.",
    "Reconoce el esfuerzo aunque los resultados se queden cortos. Valorar que tu pareja lo intentó la anima a seguir intentándolo en vez de rendirse en silencio.",
    "Haz contacto visual cuando importa. Mirar a tu pareja mientras comparte algo importante le dice que tiene tu corazón entero, no la mitad.",
    "No dejes tu relación en piloto automático. El amor a largo plazo necesita atención intencionada, o la rutina reemplaza poco a poco la conexión que antes parecía sin esfuerzo.",
    "Atrévete a ser el primero en ablandarte. Alguien tiene que bajar la espada primero, y elegir ser esa persona es una fortaleza, no una derrota.",
    "Trata las aficiones de tu pareja con respeto aunque no las compartas. Honrar lo que la ilumina demuestra que valoras todo su ser.",
    "Construye confianza siendo consistente. Hacer lo que dices, una y otra vez, le enseña a tu pareja que por fin puede bajar la guardia.",
    "Ofrece tranquilidad antes de que te la pidan. Brindar consuelo cuando percibes la preocupación de tu pareja demuestra una atención que las palabras de amor por sí solas no pueden.",
    "Discrepa sin convertirlo en un referéndum sobre la relación. No todo conflicto significa que algo anda mal; a veces solo significa que son dos personas.",
    "Sigue saliendo en citas con tu pareja. Planear tiempo intencionado para arreglarse, salir y enfocarse el uno en el otro evita que el romance se desvanezca en logística.",
    "Recibe con apertura las opiniones sobre cómo amas. Preguntar «¿hay algo que desearías que hiciera distinto?» muestra humildad y un deseo real de crecer.",
    "Deja que las pequeñas bondades se acumulen. Una relación se construye menos con grandes gestos que con mil diminutas decisiones de ser considerado y cálido.",
    "Sostén el espacio para el duelo y el estrés de tu pareja sin apresurarte a arreglarlo. A veces la presencia, no el consejo, es el amor que realmente necesita.",
    "Sé transparente con tu teléfono y tus planes. La apertura donde otros ocultarían construye una base de confianza que hace que todo lo demás se sienta seguro.",
    "Elige la curiosidad por encima de los celos. Cuando la inseguridad estalla, explora el miedo dentro de ti en vez de proyectar sospecha sobre una pareja que no ha hecho nada malo.",
    "Haz que «lo resolveremos juntos» sea tu respuesta por defecto. Enfrentar la incertidumbre como un frente unido convierte lo desconocido aterrador en aventuras compartidas que pueden manejar.",
    "Elogia quién es, no solo lo que hace. Decirle a tu pareja que admiras su bondad o su valentía la nutre más profundamente que el elogio por las tareas.",
    "Protege los momentos de transición, como los primeros minutos en casa. Saludarse con calidez en lugar de con quejas marca el tono emocional de las horas siguientes.",
    "Recuerda las cosas que te dice que le importan. Retomar una preocupación que mencionó hace días demuestra que de verdad estabas escuchando todo el tiempo.",
    "Quédense del mismo lado de la mesa. Cuando surja un problema, imagina sentarte junto a tu pareja para enfrentarlo, en lugar de frente a ella echándole la culpa.",
    "Mantén tu amor en privado cuando necesite protección. No todo detalle pertenece a las redes sociales; cierta intimidad se conserva más fuerte cuando queda entre ustedes.",
    "Sé generoso con el reconocimiento y lento con la culpa. Nombrar lo que tu pareja hizo bien, y asumir tus propios tropiezos, evita que el resentimiento eche raíces.",
    "Que el cariño sea incondicional, no una recompensa. Retener la calidez para dejar claro un punto le enseña a tu pareja que tu amor viene con condiciones.",
    "Crezcan juntos probando cosas nuevas lado a lado. La novedad compartida, desde viajar hasta una clase nueva, reaviva la emoción que el amor temprano tenía de manera natural.",
    "Terminen cada día con un momento de conexión. Unas palabras honestas o un largo abrazo antes de dormir vuelven a unirlos después de que el día los separa.",
  ],
  facts: [
    "Cuando te enamoras, tu cerebro se inunda de dopamina, la misma sustancia de recompensa implicada en la motivación y el placer, razón por la cual un romance nuevo puede sentirse casi adictivo.",
    "La oxitocina, a menudo llamada la «hormona del vínculo», se dispara durante los abrazos, el tomarse de las manos y la cercanía, ayudando a las parejas a sentirse unidas y a confiar entre sí.",
    "Algunos estudios sugieren que mirarse a los ojos durante unos minutos puede aumentar la sensación de intimidad, incluso entre personas relativamente desconocidas.",
    "La expresión «caer enamorado» puede ser más literal que poética; el romance temprano puede bajar la serotonina a niveles parecidos a los del pensamiento obsesivo.",
    "Los investigadores han descubierto que sostener la mano de un ser querido puede reducir de forma medible la percepción del dolor físico y del estrés.",
    "Tu latido cardíaco puede llegar a sincronizarse con el de tu pareja romántica cuando se sientan cerca y se miran, según estudios sobre parejas.",
    "Los antiguos griegos describían varios tipos de amor, entre ellos eros (pasión), philia (amistad) y agape (amor desinteresado), reconociendo que el amor es mucho más que un solo sentimiento.",
    "Los ratones de campo de las praderas son famosos en la ciencia por formar vínculos de pareja de por vida, y estudiarlos les ha enseñado mucho a los investigadores sobre la química de la monogamia.",
    "La tradición del anillo de compromiso de diamante se popularizó en gran parte tras una famosa campaña publicitaria del siglo XX que proclamó «Un diamante es para siempre».",
    "Las mariposas en el estómago durante el amor temprano son reales; la adrenalina de la atracción puede desviar la sangre del sistema digestivo, creando esa sensación de revoloteo.",
    "Los estudios sugieren que las parejas que ríen juntas con regularidad tienden a reportar mayor satisfacción en su relación y a sentirse más conectadas con el tiempo.",
    "La tradición de llevar el anillo en el cuarto dedo se remonta a una antigua creencia en una «vena amoris», una vena que corría directa hasta el corazón.",
    "El amor romántico y el apego profundo activan sistemas cerebrales ligeramente distintos, lo que ayuda a explicar cómo la pasión puede madurar hacia un vínculo más sereno y estable.",
    "Los cisnes, vistos a menudo como símbolos de amor, suelen formar vínculos de pareja duraderos, a veces permaneciendo con la misma pareja durante muchos años.",
    "Los investigadores estiman que a alguien puede tomarle desde unos segundos hasta unos minutos decidir si se siente atraído por una persona nueva.",
    "La «fase de luna de miel» de pasión temprana intensa suele durar entre varios meses y unos dos años antes de asentarse en un apego más profundo.",
    "Acurrucarse y el cariño físico pueden activar la liberación de endorfinas, las sustancias naturales del bienestar del cuerpo que también ayudan a reducir el estrés.",
    "En muchas culturas a lo largo de la historia, el matrimonio se arreglaba por razones económicas o políticas, y la idea de casarse principalmente por amor es relativamente moderna.",
    "Los estudios sugieren que las personas suelen sentirse más atraídas por rostros bastante simétricos, algo que algunos científicos vinculan con señales subconscientes sobre la salud.",
    "La palabra «romance» originalmente se refería a un estilo de narración medieval, y solo más tarde pasó a significar el amor apasionado que asociamos con ella hoy.",
    "El olfato cumple un papel sorprendente en la atracción; las investigaciones sugieren que el aroma puede influir sutilmente en quién nos resulta atractivo como posible pareja.",
    "Las parejas de larga duración a veces empiezan a parecerse ligeramente, un fenómeno que los investigadores atribuyen en parte a décadas de compartir expresiones, entorno y emociones.",
    "La costumbre de besarse bajo el muérdago se remonta a siglos atrás y alguna vez estuvo ligada a antiguas tradiciones de paz, fertilidad y buena voluntad.",
    "Enamorarse puede reducir temporalmente la actividad en regiones cerebrales ligadas al juicio crítico, lo cual es parte de por qué el amor puede sentirse un poco ciego.",
    "Los estudios sugieren que simplemente esperar que alguien sea cálido y amable puede llevarte a comportarte de maneras que hacen que esa persona responda con calidez.",
    "Los albatros realizan elaboradas danzas de cortejo y pueden mantener la misma pareja a lo largo de muchas temporadas de cría, a veces durante gran parte de sus largas vidas.",
    "El cerebro en el amor temprano puede asemejarse al cerebro ante ciertas recompensas, encendiendo los centros de recompensa que nos impulsan a buscar la cercanía con nuestra pareja.",
    "Los investigadores han descubierto que las parejas que expresan gratitud entre sí con regularidad tienden a sentirse más comprometidas y satisfechas en su relación.",
    "El símbolo en forma de corazón que asociamos con el amor en realidad no se parece a un corazón humano; sus orígenes se debaten y probablemente se estilizaron a lo largo de los siglos.",
    "El tacto es uno de los primeros sentidos en desarrollarse, y el cariño físico suave sigue siendo una forma poderosa en que los humanos comunican amor a lo largo de la vida.",
    "Los estudios sugieren que hacer juntos actividades nuevas y emocionantes puede aumentar la satisfacción en la relación al recrear parte de la novedad del romance temprano.",
    "Algunos pingüinos son conocidos por rituales de cortejo que incluyen ofrecer un guijarro cuidadosamente elegido a una posible pareja.",
    "Se cree que la hormona vasopresina, junto con la oxitocina, desempeña un papel importante en el vínculo y el apego a largo plazo entre las parejas.",
    "El Día de San Valentín tiene sus raíces en antiguos festivales y en la leyenda de san Valentín, evolucionando a lo largo de los siglos hasta la celebración actual del amor romántico.",
    "Las investigaciones sugieren que las personas tienden a sentirse más cercanas a aquellas a quienes se confían, razón por la cual compartir historias personales puede acelerar la intimidad.",
    "El sonrojo, una respuesta exclusivamente humana, puede señalar atracción y vergüenza, y algunos investigadores creen que evolucionó en parte como una señal social honesta.",
    "El «efecto de mera exposición» significa que a menudo llegamos a querer más a las personas simplemente por verlas repetidamente, razón por la cual la cercanía puede encender el romance.",
    "Los estudios sugieren que las parejas que enfrentan el conflicto con humor y delicadeza en lugar de desprecio tienen muchas más probabilidades de permanecer juntas.",
    "Los caballitos de mar son famosos por una disposición inusual en la que el macho lleva y cuida a las crías en desarrollo.",
    "La sustancia química feniletilamina, a veces apodada la «molécula del amor», se libera durante la atracción y también se encuentra de forma natural en pequeñas cantidades en el chocolate.",
    "A lo largo de muchas culturas y épocas, los poetas han tratado el amor como uno de los temas centrales de la humanidad, lo que sugiere que su atractivo emocional es notablemente universal.",
    "Las investigaciones sobre los «estilos de apego» sugieren que nuestros vínculos tempranos con quienes nos cuidaron pueden influir en lo seguros o ansiosos que nos sentimos en las relaciones románticas adultas.",
    "Los estudios sugieren que incluso los pequeños gestos de amabilidad entre parejas, como preparar un té o un mensaje rápido, se acumulan en una buena voluntad duradera en la relación.",
    "La costumbre del pastel de boda tiene raíces antiguas, ya que diversas culturas usaron históricamente pan o pastel en rituales matrimoniales que simbolizaban la prosperidad.",
    "Algunos científicos creen que el poder de la música para conmover está estrechamente ligado al vínculo, lo que quizá explique por qué hay canciones de amor en casi todas las culturas.",
    "Los investigadores han observado que las parejas recién enamoradas a veces experimentan menos apetito y problemas para dormir, en parte debido a las oleadas de sustancias de estrés y recompensa.",
    "La «danza del meneo» de las abejas no es romance, pero muchas exhibiciones de cortejo animal son actuaciones elaboradas destinadas a atraer e impresionar a una pareja.",
    "Los estudios sugieren que sentirse apreciado es uno de los predictores más fuertes de si las personas se sienten satisfechas y quieren permanecer en una relación.",
    "La tradición de cargar a la novia al cruzar el umbral tiene raíces en costumbres antiguas que alguna vez se creyó protegían a la pareja de la mala suerte.",
    "El amor y el dolor pueden compartir vías cerebrales superpuestas, lo que quizá ayude a explicar por qué un desamor puede sentirse genuinamente doloroso a nivel físico.",
    "Los investigadores que estudian a parejas casadas desde hace mucho han descubierto que un pequeño número que dice seguir sintiendo amor intenso muestra una actividad cerebral parecida a la del romance temprano.",
    "Muchas especies de aves cantan dúos con sus parejas, coordinando sus llamados con tanta precisión que puede sonar como una sola voz.",
    "Los estudios sugieren que las parejas tienden a ser más felices cuando mantienen un equilibrio sano entre interacciones positivas y negativas en la vida diaria.",
    "El intercambio de anillos como símbolo de compromiso es una práctica antigua que aparece de diversas formas en muchas civilizaciones tempranas.",
    "La atracción física puede verse influida por algo tan simple como un corazón acelerado; la excitación provocada por la emoción a veces se interpreta erróneamente como atracción romántica.",
    "Algunos investigadores describen el amor romántico como compuesto por tres grandes componentes: deseo, atracción y apego, cada uno impulsado por una química cerebral distinta.",
    "Los lobos suelen formar vínculos de pareja fuertes, y una pareja unida a menudo constituye el núcleo social de su manada.",
    "Los estudios sugieren que las parejas que sienten que su relación es un lugar de aceptación están más dispuestas a asumir riesgos emocionales sanos entre sí.",
    "El color rojo se ha relacionado en algunos estudios con la percepción de atracción, ya que a veces las personas califican a otras como más atractivas cuando lo llevan puesto.",
    "A lo largo de la historia, las cartas de amor han sido recuerdos atesorados, y ejemplares que sobreviven de hace siglos revelan que el anhelo y la devoción cambian poco con el tiempo.",
    "Los investigadores han descubierto que el contacto físico afectuoso de una pareja puede ayudar a bajar la presión arterial y a aliviar la respuesta del cuerpo ante el estrés.",
    "Algunas especies de pingüinos, gibones y ciertos zorros son señaladas por los biólogos por formar vínculos de pareja notablemente fuertes y duraderos.",
    "El «efecto Romeo y Julieta» describe cómo la oposición externa a una relación a veces puede intensificar, en lugar de debilitar, la pasión de una pareja.",
    "Los estudios sugieren que el simple hecho de pensar en un ser querido puede activar áreas de recompensa del cerebro y ofrecer un amortiguador medible contra el estrés.",
    "Muchas culturas intercambiaban históricamente prendas de compromiso, desde anillos hasta cintas y monedas, mucho antes de que tomaran forma las tradiciones modernas de compromiso.",
    "Las investigaciones sugieren que las personas a menudo subestiman cuánto alegrará el día de su pareja un cumplido sincero, dejando demasiadas veces las palabras amables sin decir.",
    "Los gibones son conocidos entre los primates por formar vínculos de pareja a largo plazo e incluso cantar juntos llamados matutinos coordinados.",
    "La sensación de «química» con alguien puede reflejar en parte lo cómodo y a gusto que se siente tu sistema nervioso en su presencia.",
    "Los estudios sugieren que las parejas que comparten y celebran juntas las buenas noticias, y no solo se apoyan en los momentos difíciles, tienden a sentirse más conectadas.",
    "Los castores suelen emparejarse y trabajar juntos para construir y mantener sus madrigueras, compartiendo el esfuerzo de criar a sus pequeños.",
    "La expresión «atar el nudo» probablemente proviene de antiguas costumbres matrimoniales de diversas culturas que literalmente implicaban atar las manos de la pareja.",
    "Las investigaciones sobre la atracción sugieren que el sentido del humor es uno de los rasgos más valorados que la gente busca en una pareja a largo plazo.",
    "Algunos científicos creen que la tendencia humana a formar vínculos de pareja pudo haber evolucionado en parte para apoyar la larga tarea de criar hijos.",
    "Los estudios sugieren que las parejas que mantienen rituales compartidos, por pequeños que sean, reportan un sentido más fuerte de identidad y pertenencia juntos.",
    "El mito de Cupido, la figura alada que atraviesa los corazones con flechas, proviene de la mitología romana y de la figura griega más antigua de Eros.",
    "Los investigadores han descubierto que sentirse comprendido por la pareja está estrechamente ligado a sentirse amado, a veces incluso más que los grandes gestos románticos.",
    "Ciertos antílopes, grullas y loros están entre los muchos animales que los biólogos han observado manteniendo vínculos duraderos con una sola pareja.",
    "Los estudios sugieren que la forma en que las parejas manejan las pequeñas molestias diarias predice la satisfacción a largo plazo de manera más fiable que cómo manejan las raras grandes crisis.",
    "La tradición de una «luna de miel» después del matrimonio se popularizó en el siglo XIX, aunque la palabra en sí es mucho más antigua.",
    "Las investigaciones sugieren que la cercanía física durante el sueño, como la presencia cercana de una pareja, puede mejorar sutilmente la sensación de seguridad y descanso.",
    "Algunas flores, en especial la rosa roja, se convirtieron en símbolos perdurables del amor a través de siglos de poesía, arte y tradición cultural.",
    "Los estudios sugieren que las parejas que pueden reparar rápido tras un conflicto, en lugar de evitarlo a la perfección, tienden a tener las relaciones más fuertes.",
    "El sistema de recompensa del cerebro puede responder a la sonrisa de una pareja de maneras similares a otras experiencias profundamente gratificantes, reforzando la atracción del amor.",
    "Muchas culturas desarrollaron tradiciones de emparejamiento, y los casamenteros profesionales han existido en diversas sociedades durante cientos de años.",
    "Las investigaciones sugieren que expresar el cariño a través del «lenguaje del amor» preferido de tu pareja suele tener un impacto más fuerte que el cariño en tus propios términos.",
    "Las cigüeñas, a menudo asociadas con los bebés en el folclore, también son conocidas por regresar con frecuencia al mismo nido y a la misma pareja año tras año.",
    "Los estudios sugieren que la nostalgia por los recuerdos compartidos puede fortalecer el vínculo de una pareja al recordarle su historia y su resiliencia juntos.",
    "La costumbre de las damas de honor podría remontarse a antiguas tradiciones en las que se creía que asistentes vestidas de forma similar confundían a los espíritus malignos.",
    "Las investigaciones sugieren que las parejas que mantienen un sentido de «nosotros» en lugar de «yo contra ti» durante los desacuerdos tienden a resolverlos de forma más constructiva.",
    "Las águilas calvas a menudo forman vínculos de pareja a largo plazo y pueden regresar juntas al mismo sitio de anidación a lo largo de muchos años.",
    "Los estudios sugieren que la anticipación puede aumentar la felicidad, razón por la cual esperar con ilusión el tiempo con una pareja puede ser casi tan gozoso como el tiempo en sí.",
    "La tradición de regalar flores como gesto romántico se ha documentado en muchas culturas y siglos como un lenguaje del afecto.",
    "Las investigaciones sugieren que las personas en relaciones de apoyo tienden a recuperarse de la enfermedad y el estrés algo más rápido que quienes se sienten aislados.",
    "Algunas especies de peces cíclidos son señaladas por los biólogos por cooperar en pareja para custodiar y cuidar sus huevos y crías.",
    "Los estudios sugieren que las parejas que expresan cariño físico con regularidad, más allá de la resolución de conflictos, tienden a mantener vínculos emocionales más fuertes.",
    "La noción de «alma gemela» ha aparecido en la filosofía desde la antigüedad, incluido un famoso mito relatado en los escritos de Platón.",
    "Las investigaciones sugieren que el simple hecho de tener una pareja en quien confiar se asocia con una mayor resiliencia durante los momentos más estresantes de la vida.",
    "Los peces ángel franceses están entre las especies que los biólogos han observado desplazándose y defendiendo territorio como parejas fieles y cooperativas.",
    "Los estudios sugieren que el hábito de la relación temprana de idealizar a la pareja, dentro de lo razonable, puede en realidad ayudar a las parejas a mantenerse satisfechas con el tiempo.",
    "El apretón de manos y el beso como saludos tienen profundas raíces históricas, y el beso romántico aparece en muchas culturas antiguas.",
    "Las investigaciones sugieren que las parejas que hacen tiempo para el ocio compartido, aunque sean momentos breves, reportan sentirse más cercanas y más como un equipo.",
    "Algunos científicos creen que la capacidad humana universal para el amor podría ser una de las herramientas más poderosas de la evolución para la cooperación y la supervivencia.",
    "Los estudios sugieren que sentirse seguro en una relación libera a las personas para ser más aventureras y seguras en el resto de su vida.",
    "La tradición de la poesía amorosa se remonta a miles de años, con algunos de los poemas de amor más antiguos que se conocen escritos en antiguas tablillas de arcilla.",
    "Las investigaciones sugieren que las parejas a menudo se sienten más amadas no durante los gestos dramáticos, sino en pequeños y constantes momentos de atención y cuidado.",
    "Ciertas especies de búhos forman vínculos de pareja duraderos y cooperan estrechamente para criar a sus polluelos, compartiendo las tareas de caza y anidación.",
    "Los estudios sugieren que las parejas que mantienen amistades e intereses individuales, junto con su relación, tienden a reportar una mayor felicidad a largo plazo juntos.",
    "El velo que llevan algunas novias tiene orígenes antiguos, apareciendo en diversas culturas como símbolo de modestia, misterio o protección.",
    "Las investigaciones sugieren que la experiencia del asombro, como contemplar juntos una puesta de sol, puede profundizar el sentido de conexión y de significado compartido de una pareja.",
    "Muchas culturas tienen tradiciones populares sobre amuletos y prendas de amor, reflejando un deseo humano atemporal de atraer y conservar el afecto.",
    "Los estudios sugieren que la receptividad, la sensación de que tu pareja realmente nota y se preocupa por tus necesidades, es central para sentirse profundamente amado.",
    "La idea de celebrar un aniversario de boda con regalos específicos, como papel u oro para ciertos años, se desarrolló gradualmente durante los últimos siglos.",
    "Las investigaciones sugieren que incluso imaginar momentos futuros con la pareja puede fortalecer el compromiso presente y la motivación para cuidar la relación.",
    "Algunos pingüinos macaroni y otras aves marinas se reúnen con la misma pareja cada temporada de cría tras pasar meses separados en el mar.",
    "Los estudios sugieren que el simple acto de decir «gracias» a la pareja puede desencadenar un ciclo positivo de aprecio y generosidad.",
    "La palabra «acurrucarse» puede sonar moderna, pero los humanos han buscado el consuelo del contacto físico cercano desde los primeros momentos de nuestra especie.",
    "Las investigaciones sugieren que las parejas que ven los desafíos como problemas compartidos a resolver, en lugar de fallas personales, tienden a fortalecerse a través de la adversidad.",
  ],
  quotes: [
    { text: "Sea cual sea la materia de la que están hechas nuestras almas, la suya y la mía son la misma.", author: "Emily Brontë" },
    { text: "Sabes que estás enamorado cuando no puedes dormir porque la realidad por fin es mejor que tus sueños.", author: "Dr. Seuss" },
    { text: "El amor se compone de una sola alma que habita en dos cuerpos.", author: "Aristóteles" },
    { text: "Lo mejor a lo que aferrarse en la vida es el uno al otro.", author: "Audrey Hepburn" },
    { text: "Estamos más vivos que nunca cuando estamos enamorados.", author: "John Updike" },
    { text: "El amor es esa condición en la que la felicidad de otra persona es esencial para la tuya.", author: "Robert A. Heinlein" },
    { text: "Amar y ser amado es sentir el sol por ambos lados.", author: "David Viscott" },
    { text: "No hay más remedio para el amor que amar más.", author: "Henry David Thoreau" },
    { text: "El amor no consiste en mirarse el uno al otro, sino en mirar juntos en la misma dirección.", author: "Antoine de Saint-Exupéry" },
    { text: "Si sé lo que es el amor, es gracias a ti.", author: "Hermann Hesse" },
    { text: "La mayor felicidad de la vida es la convicción de que somos amados.", author: "Victor Hugo" },
    { text: "El amor es la amistad que ha prendido en llamas.", author: "Ann Landers" },
    { text: "Donde hay amor, hay vida.", author: "Mahatma Gandhi" },
    { text: "Ser amado profundamente por alguien te da fuerza, mientras que amar a alguien profundamente te da valor.", author: "Lao Tse" },
    { text: "El amor es cuando la felicidad de la otra persona es más importante que la tuya.", author: "H. Jackson Brown Jr." },
    { text: "El corazón tiene razones que la razón no entiende.", author: "Blaise Pascal" },
    { text: "Un matrimonio exitoso requiere enamorarse muchas veces, siempre de la misma persona.", author: "Mignon McLaughlin" },
    { text: "Amamos con un amor que era más que amor.", author: "Edgar Allan Poe" },
    { text: "Pero las cosas más hermosas del mundo no se pueden ver ni siquiera tocar, deben sentirse con el corazón.", author: "Helen Keller" },
    { text: "El amor no es encontrar a alguien con quien vivir. Es encontrar a alguien sin quien no puedes vivir.", author: "Rafael Ortiz" },
    { text: "El amor no reconoce barreras. Salta obstáculos, brinca cercas y atraviesa muros para llegar a su destino lleno de esperanza.", author: "Maya Angelou" },
    { text: "El amor es un deseo irresistible de ser irresistiblemente deseado.", author: "Robert Frost" },
    { text: "No te casas con alguien con quien puedes vivir, te casas con la persona sin quien no puedes vivir.", author: "Anónimo" },
    { text: "El curso del verdadero amor nunca fue sereno.", author: "William Shakespeare" },
    { text: "Ama a todos, confía en pocos, no le hagas mal a nadie.", author: "William Shakespeare" },
    { text: "El amor no mira con los ojos, sino con la mente.", author: "William Shakespeare" },
    { text: "He encontrado a aquel a quien ama mi alma.", author: "Cantar de los Cantares" },
    { text: "El amor es paciente, el amor es bondadoso. No tiene envidia, no es jactancioso, no es orgulloso.", author: "1 Corintios 13:4" },
    { text: "Al toque del amor, todos se vuelven poetas.", author: "Platón" },
    { text: "Dar amor es en sí mismo una educación.", author: "Eleanor Roosevelt" },
    { text: "El amor es la flor que tienes que dejar crecer.", author: "John Lennon" },
    { text: "Todo lo que necesitas es amor.", author: "John Lennon" },
    { text: "El amor es o no es. El amor tibio no es amor en absoluto.", author: "Toni Morrison" },
    { text: "El amor quita las máscaras que tememos no poder vivir sin ellas y que sabemos que no podemos vivir dentro de ellas.", author: "James Baldwin" },
    { text: "El amor es un fruto de todas las estaciones y al alcance de toda mano.", author: "Madre Teresa" },
    { text: "Difunde amor por donde vayas. Que nadie llegue a ti sin marcharse más feliz.", author: "Madre Teresa" },
    { text: "Solo podemos aprender a amar amando.", author: "Iris Murdoch" },
    { text: "El amor no es algo que encuentras. El amor es algo que te encuentra a ti.", author: "Loretta Young" },
    { text: "El arte de amar es en gran medida el arte de la perseverancia.", author: "Albert Ellis" },
    { text: "Amar, en cualquier grado, es ser vulnerable.", author: "C. S. Lewis" },
    { text: "El amor no es un sentimiento afectuoso, sino un deseo constante del bien último de la persona amada.", author: "C. S. Lewis" },
    { text: "El amor es el todo. Nosotros solo somos las partes.", author: "Rumi" },
    { text: "Tu tarea no es buscar el amor, sino simplemente buscar y encontrar todas las barreras dentro de ti que has construido contra él.", author: "Rumi" },
    { text: "Que la belleza de lo que amas sea lo que haces.", author: "Rumi" },
    { text: "El amor es el puente entre tú y todo lo demás.", author: "Rumi" },
    { text: "La gravedad no es responsable de que la gente se enamore.", author: "Albert Einstein" },
    { text: "El amor consiste en esto: que dos soledades se protejan, se toquen y se saluden.", author: "Rainer Maria Rilke" },
    { text: "Una vez que has aprendido a amar, habrás aprendido a vivir.", author: "Anónimo" },
    { text: "El amor se compone de muchas cosas, pero su cimiento es la amistad y la confianza.", author: "Anónimo" },
    { text: "Cuando amas a alguien, amas a la persona tal como es, y no como te gustaría que fuera.", author: "León Tolstói" },
    { text: "Bajó del tren, tratando de no mirarla demasiado, como si ella fuera el sol, y sin embargo la veía, como al sol, incluso sin mirarla.", author: "León Tolstói" },
    { text: "Duda de que las estrellas sean fuego; duda de que el sol se mueva; duda de que la verdad sea mentira; pero nunca dudes de que te amo.", author: "William Shakespeare" },
    { text: "¿Cómo te amo? Déjame contar las maneras.", author: "Elizabeth Barrett Browning" },
    { text: "El amor es anterior a la vida, posterior a la muerte, principio de la creación y exponente del aliento.", author: "Emily Dickinson" },
    { text: "Que el amor es todo lo que hay, es todo lo que sabemos del amor.", author: "Emily Dickinson" },
    { text: "Si vives hasta los cien, quiero vivir hasta los cien menos un día, para nunca tener que vivir sin ti.", author: "A. A. Milne" },
    { text: "El amor es un lienzo provisto por la naturaleza y bordado por la imaginación.", author: "Voltaire" },
    { text: "Las cosas más bellas y mejores de este mundo no se pueden ver ni oír, sino que deben sentirse con el corazón.", author: "Helen Keller" },
    { text: "Una flor no puede florecer sin sol, y el hombre no puede vivir sin amor.", author: "Max Müller" },
    { text: "El amor es como el viento: no puedes verlo, pero puedes sentirlo.", author: "Nicholas Sparks" },
    { text: "La simple falta de ella es para mí más que la presencia de los demás.", author: "Edward Thomas" },
    { text: "Preferiría compartir una sola vida contigo que enfrentar todas las eras de este mundo a solas.", author: "J. R. R. Tolkien" },
    { text: "El amor es la llave maestra que abre las puertas de la felicidad.", author: "Oliver Wendell Holmes" },
    { text: "Somos moldeados y formados por aquello que amamos.", author: "Johann Wolfgang von Goethe" },
    { text: "El amor, como la tos, no se puede ocultar.", author: "George Herbert" },
    { text: "Dos personas se aman entregándose el mundo el uno al otro.", author: "Anónimo" },
    { text: "El amor hace que tu alma salga arrastrándose de su escondite.", author: "Zora Neale Hurston" },
    { text: "Siempre hay algo de locura en el amor. Pero también siempre hay algo de razón en la locura.", author: "Friedrich Nietzsche" },
    { text: "El amor es la única fuerza capaz de transformar a un enemigo en un amigo.", author: "Martin Luther King Jr." },
    { text: "Debemos desarrollar y mantener la capacidad de perdonar.", author: "Martin Luther King Jr." },
    { text: "La manera de amar algo es darse cuenta de que puede perderse.", author: "G. K. Chesterton" },
    { text: "Amar nunca es una pérdida de tiempo.", author: "Astrid Alauda" },
    { text: "El amor es la voz bajo todos los silencios, la esperanza que no tiene opuesto en el miedo.", author: "E. E. Cummings" },
    { text: "Llevo tu corazón conmigo. Lo llevo en mi corazón.", author: "E. E. Cummings" },
    { text: "El amor crece dando. El amor que regalamos es el único amor que conservamos.", author: "Elbert Hubbard" },
    { text: "Amar no es nada. Ser amado es algo. Pero amar y ser amado, eso lo es todo.", author: "T. Tolis" },
    { text: "El amor plantó una rosa, y el mundo se volvió dulce.", author: "Katharine Lee Bates" },
    { text: "El amor es la expansión de dos naturalezas de tal modo que cada una incluye a la otra.", author: "Felix Adler" },
    { text: "Dime a quién amas, y te diré quién eres.", author: "Houssaye" },
    { text: "Donde solías estar, hay un agujero en el mundo, alrededor del cual me encuentro caminando constantemente durante el día.", author: "Edna St. Vincent Millay" },
  ],
};
