import type { RotationalContent } from '@/lib/dailyContentTypes';

export const fr: RotationalContent = {
  tips: [
    "Écoutez pour comprendre, pas pour répondre. Marquer une pause avant de réagir montre à votre partenaire que ses mots ont vraiment touché juste, et cette petite habitude renforce la confiance avec le temps.",
    "Dites merci pour les gestes ordinaires. Remarquer le café préparé ou la vaisselle faite rappelle à votre partenaire que ses efforts quotidiens ne passent jamais inaperçus.",
    "Quand un conflit éclate, attaquez le problème ensemble plutôt que de vous attaquer l'un l'autre. Vous êtes une équipe face à une difficulté, pas des adversaires cherchant à marquer un point.",
    "Réservez du temps tranquille à deux, ne serait-ce que vingt minutes. La connexion naît rarement dans les interstices ; elle grandit quand on lui fait délibérément de la place.",
    "Demandez à votre partenaire comment il préfère être réconforté. Certains veulent des solutions, d'autres une étreinte et du silence, et se tromper peut créer une distance.",
    "Réparez vite après un désaccord. Un échange sincère, une fois l'orage passé, compte bien plus que de faire comme si la friction n'avait jamais eu lieu.",
    "La curiosité maintient l'amour vivant. Continuez à poser de nouvelles questions à votre partenaire de longue date, car les gens changent en silence et les plus fascinants se révèlent encore.",
    "Exprimez votre reconnaissance à voix haute, pas seulement dans votre tête. Une gratitude tue ne réchauffe que vous, alors qu'une gratitude dite réchauffe la personne que vous aimez.",
    "Protégez votre relation du mépris. Les yeux levés au ciel et le sarcasme rongent le lien plus vite que presque tout, alors choisissez le respect même quand vous êtes agacé.",
    "Saisissez les appels à la connexion. Quand votre partenaire partage une petite chose, vous tourner vers lui avec attention est le ciment discret d'un amour durable.",
    "Excusez-vous sans ajouter de « mais ». Des excuses sincères assument pleinement votre part, tandis qu'une excuse à conditions renvoie discrètement la faute à l'autre.",
    "Gardez quelques rituels qui n'appartiennent qu'à vous. Une promenade du dimanche ou un café partagé le matin crée un rythme stable qui ancre des vies bien remplies.",
    "Présumez la bonne intention avant de craindre le pire. La plupart des moments blessants viennent de maladresse ou de stress, pas d'un partenaire vous voulant secrètement du mal.",
    "Parlez d'argent tôt et souvent. S'accorder sur les dépenses, l'épargne et les objectifs évite le ressentiment silencieux que les finances peuvent créer.",
    "Laissez votre partenaire être différent de vous. La compatibilité n'est pas l'identique ; ce sont deux êtres distincts qui choisissent d'honorer le monde intérieur de l'autre.",
    "Remarquez ce que porte votre partenaire. Un doux « tu as l'air fatigué, je m'occupe du dîner » peut dire je t'aime plus fort que les mots.",
    "Gardez une part d'indépendance au sein de la vie commune. Cultiver vos propres amis et passions fait de vous un partenaire plus intéressant et énergique à retrouver.",
    "Faites des compliments en public, réglez les problèmes en privé. Valoriser votre partenaire devant les autres et gérer les frictions discrètement protège à la fois la fierté et la confiance.",
    "Remplacez « tu fais toujours » et « tu ne fais jamais » par « je ressens ». Parler de votre vécu invite à la compréhension, là où les accusations globales suscitent la défensive.",
    "Le contact compte même quand tout va bien. Une main sur l'épaule ou une étreinte rapide rappelle au corps qu'il est aimé.",
    "Choisissez à nouveau votre partenaire les jours difficiles. L'amour n'est pas seulement l'étincelle dans laquelle on tombe, mais la décision que l'on renouvelle quand tout devient lourd.",
    "Intéressez-vous à son univers. Poser de vraies questions sur le travail, les soucis et les rêves de votre partenaire lui dit que sa vie compte vraiment pour vous.",
    "Ne tenez pas les comptes. Une générosité donnée pour être remboursée est une transaction ; l'amour s'épanouit quand on donne librement, en faisant confiance à l'équilibre.",
    "Nommez vos besoins clairement. Votre partenaire ne lit pas dans vos pensées, et espérer en silence qu'il devine finit souvent par vous décevoir tous les deux.",
    "Riez souvent ensemble. L'humour partagé apaise les tensions, nourrit l'intimité et rappelle que la personne à vos côtés est aussi votre compagnon préféré.",
    "Soyez pleinement présent aux retrouvailles. Accueillir chaleureusement votre partenaire, téléphone posé et regard levé, donne le ton de la soirée.",
    "Pardonnez vite les petites choses. Garder rancune des griefs mineurs élève un mur brique après brique, jusqu'à ne plus pouvoir se rejoindre.",
    "Célébrez les réussites de votre partenaire comme les vôtres. Une joie sincère face à son succès, sans envie, est l'une des formes les plus profondes de l'amour.",
    "Vérifiez avant de croire que vous vous êtes éloignés. Un simple « comment va-t-on tous les deux en ce moment ? » révèle souvent un lien que la distance ne faisait que menacer.",
    "Respectez les limites de l'autre sans les prendre personnellement. Une limite renseigne sur les besoins de votre partenaire, ce n'est pas un rejet de vous.",
    "Tentez des gestes d'apaisement pendant les disputes, comme un ton plus doux ou une petite blague. Accepter ces rameaux d'olivier empêche les désaccords de s'envenimer.",
    "Soyez présent pour la logistique ennuyeuse. Partager équitablement les tâches, les courses et l'organisation est l'un des langages de l'amour les plus sous-estimés.",
    "Soyez honnête sur les petites choses. La confiance se construit dans de minuscules moments de vérité, et les petits mensonges apprennent en silence à l'autre à douter de vous.",
    "Demandez « de quoi as-tu besoin de ma part, là, tout de suite ? » Cette seule question coupe court aux suppositions et offre à votre partenaire exactement le soutien qu'il souhaite.",
    "Continuez à séduire votre partenaire de longue date. Un clin d'œil, un compliment, un baiser volé lui rappellent qu'il est encore désiré, et pas seulement fiable.",
    "Laissez-le avoir une mauvaise journée. Vous n'avez pas à réparer chaque humeur ; parfois, le plus tendre est simplement de rester proche pendant qu'elle passe.",
    "Parlez de votre relation quand tout va bien, pas seulement quand elle se fissure. Les conversations d'entretien préviennent les grandes crises.",
    "Honorez la relation devant les autres. Parler chaleureusement de votre partenaire en son absence protège le couple de l'érosion extérieure.",
    "Reconnaissez votre rôle dans les disputes récurrentes. Se demander « quels sont mes 10 % là-dedans ? » transforme une impasse en occasion de grandir ensemble.",
    "Prenez les décisions avec l'autre, pas à sa place. Même de petites consultations expriment le respect et rappellent à votre partenaire que vous formez une vraie équipe.",
    "Apaisez-vous avant les grandes conversations. Aborder un sujet difficile calme plutôt que submergé vous aide à dire ce que vous pensez vraiment, pas ce qui blesse.",
    "Accueillez l'évolution de votre partenaire même quand elle dérange. Aimer quelqu'un, c'est soutenir la personne qu'il devient, pas seulement celle que vous avez rencontrée.",
    "Surprenez-le par l'effort, pas seulement par les cadeaux. Préparer une soirée pleine d'attention ou apprendre sa recette préférée montre un amour que l'argent ne peut acheter.",
    "Soyez le refuge où il peut souffler. Quand le foyer devient le seul endroit où il peut pleinement se détendre, votre relation devient son abri.",
    "Demandez les hauts et les bas de sa journée. Ce rituel tout simple ouvre chaque jour une fenêtre sur la météo intérieure de votre partenaire.",
    "Validez les émotions même quand la logique vous échappe. « C'est normal que tu ressentes ça » apaise les tempêtes bien mieux que de corriger les faits.",
    "Faites des promesses assez modestes pour les tenir. Une fiabilité bâtie sur de petits engagements honorés inspire plus confiance que de grands serments difficiles à tenir.",
    "Prenez la responsabilité de votre propre bonheur. Un partenaire peut enrichir votre joie, mais attendre qu'il en soit l'unique source est un fardeau bien lourd.",
    "Revisitez vos rêves communs de temps en temps. Parler de l'avenir que vous bâtissez remet les frictions quotidiennes en perspective et garde la motivation vivante.",
    "Donnez signe de vie pendant les longues journées séparés. Un petit message en milieu de journée disant que vous pensez à l'autre empêche le fil du lien de se relâcher.",
    "Renoncez à avoir raison pour rester connecté. Gagner une dispute en perdant la chaleur de votre partenaire est rarement une victoire qui vaut la peine.",
    "Repérez le langage de l'amour que chacun parle. Si vous offrez des mots alors qu'il a soif de temps, votre effort le manque peut-être de peu.",
    "Créez une zone sans téléphone à table. Les repas sans distraction sont une chance quotidienne de vraiment voir et entendre la personne en face de vous.",
    "Soyez doux avec les insécurités de votre partenaire. Les endroits où il se sent fragile méritent votre attention, pas vos taquineries, même par jeu.",
    "Faites place au temps « pour soi » et au temps « pour nous ». Honorer la solitude et la vie commune évite que la relation devienne une prison ou un éloignement.",
    "Exprimez ouvertement le désir et l'admiration. Dire précisément à votre partenaire ce qui vous séduit chez lui ne lasse jamais et n'est jamais reçu avec indifférence.",
    "Traitez le ressentiment tant qu'il est petit. Nommer avec douceur une frustration mineure l'empêche de durcir en rancune que vous ne sauriez plus expliquer.",
    "Montrez de l'intérêt pour ses amis et sa famille. Accueillir les personnes que votre partenaire aime signale que vous vous investissez dans toute sa vie, pas seulement en lui.",
    "Ralentissez quand vous sentez une déconnexion. Plutôt que de vous éloigner davantage, rapprochez-vous doucement et demandez ce qui occupe l'esprit de votre partenaire.",
    "Gardez en sécurité les secrets et les histoires de votre partenaire. Être quelqu'un à qui il peut tout confier est le socle d'une vraie intimité émotionnelle.",
    "Au début d'une relation, observez comment l'autre traite ceux qui ne peuvent rien lui apporter. La gentillesse envers les serveurs et les inconnus révèle le vrai caractère.",
    "Ne vous précipitez pas pour tout définir. Laisser respirer un lien naissant permet de voir qui est vraiment l'autre avant que les étiquettes ne créent pression et attentes.",
    "Accordez-vous à son rythme sans vous perdre. Un amour neuf et sain équilibre l'enthousiasme et la patience, laissant la confiance grandir naturellement plutôt que de forcer l'intensité.",
    "Cherchez quelqu'un dont les journées ordinaires vous font du bien, pas seulement celles qui sont palpitantes. La compatibilité du quotidien survit toujours à l'alchimie spectaculaire.",
    "Observez comment votre rendez-vous gère une déception. La façon dont quelqu'un réagit à un petit revers annonce comment il affrontera les plus grands.",
    "Dans l'amour à distance, préservez un quotidien partagé. Regarder une série ensemble ou faire des courses en visio maintient la proximité vivante.",
    "Planifiez la prochaine visite avant l'au revoir actuel. Avoir une date sur le calendrier donne aux couples à distance quelque chose de concret à quoi s'accrocher.",
    "Communiquez généreusement malgré les kilomètres. La distance rend les suppositions dangereuses, alors partagez largement contexte et réconfort plutôt que de laisser le silence être mal interprété.",
    "La confiance est la monnaie de la distance. Sans proximité quotidienne, choisir de croire au meilleur chez l'autre devient la colonne vertébrale de la relation.",
    "Pratiquez l'amour de soi pour apporter de la plénitude, pas du manque. Apprécier sa propre compagnie fait de vous un partenaire qui choisit l'amour plutôt que de s'y accrocher.",
    "Parlez-vous comme vous parleriez à l'être aimé. Un discours intérieur dur déteint sur les relations, tandis que la bienveillance envers soi laisse la chaleur rayonner.",
    "Soignez vos vieilles blessures plutôt que d'en charger un partenaire. Une relation aimante peut soutenir votre évolution, mais elle ne peut remplacer votre propre travail.",
    "Connaissez votre valeur avant de négocier l'amour. Ceux qui comprennent ce qu'ils valent se contentent rarement d'être une arrière-pensée ou un plan de secours.",
    "Asseyez-vous avec les émotions inconfortables au lieu de les déverser. Nommer ce que vous ressentez avant de réagir épargne à votre partenaire vos tempêtes non digérées.",
    "Développez l'art de rester serein sous le stress. Votre présence calme dans les moments difficiles de votre partenaire est une forme d'amour discrète et puissante.",
    "Lisez l'émotion sous les mots. Quand votre partenaire s'agace pour la vaisselle, le vrai message est souvent « je me sens peu soutenu », et cela mérite votre attention.",
    "Menez avec empathie quand votre partenaire est contrarié, même contre vous. Se défendre peut attendre ; c'est se sentir compris qui apaise réellement le moment.",
    "Construisez ensemble un vocabulaire émotionnel. Les couples capables de nommer précisément leurs sentiments résolvent les conflits plus vite que ceux bloqués sur « ça va » et « en colère ».",
    "Laissez la proximité physique être sa propre conversation. Se tenir l'un l'autre sans intention peut transmettre une sécurité que les mots peinent parfois à atteindre.",
    "Gardez l'intimité variée et sans hâte. Le lien s'approfondit quand on aborde la proximité physique comme une exploration et un jeu plutôt qu'une routine ou une obligation.",
    "Parlez ouvertement de ce que chacun apprécie. Une conversation honnête et détendue sur l'intimité bâtit la confiance et empêche le désir de se perdre dans les suppositions.",
    "Soyez d'abord l'ami de votre partenaire. Les couples qui durent ont tendance à vraiment s'apprécier, savourant la conversation longtemps après que les premières étincelles se sont apaisées.",
    "Rendez de petits services sans qu'on vous le demande. Faire le plein de sa voiture ou recharger son téléphone dit discrètement « je pense à toi » toute la journée.",
    "Faites des compromis en échangeant des priorités, pas en coupant tout en deux. Céder pleinement là où cela compte moins pour vous gagne de la bonne volonté là où cela compte plus.",
    "Cherchez le gagnant-gagnant avant de vous résigner au compromis. Bien des conflits s'apaisent quand on se demande ce qui satisferait vraiment chacun.",
    "Posez des limites avec chaleur, pas avec froideur. Vous pouvez dire non clairement tout en laissant votre partenaire se sentir aimé et respecté.",
    "Ne punissez pas la vulnérabilité. Quand votre partenaire s'ouvre sur une peur ou une erreur, l'accueillir avec tendresse garantit qu'il vous fera de nouveau confiance.",
    "Cultivez une culture de l'appréciation, en cherchant ce qui va bien. Les couples qui remarquent activement le meilleur chez l'autre rapportent un bonheur bien plus durable.",
    "Faites sentir à votre partenaire qu'il est choisi, pas seulement toléré. Lui rappeler, en mots et en gestes, que vous le choisiriez encore garde l'amour vivant.",
    "Accordez à voix haute le bénéfice du doute à votre partenaire. Dire « je suis sûr que tu ne le pensais pas ainsi » désamorce la tension avant qu'elle ne monte.",
    "Traitez les agacements de votre partenaire comme des informations, pas des attaques. Ce qui l'irrite pointe souvent un besoin non comblé qu'il vaut mieux comprendre que balayer.",
    "Gardez la curiosité plus grande que le jugement. Quand quelque chose vous intrigue chez votre partenaire, demandez avec intérêt au lieu de conclure par la critique.",
    "Célébrez les anniversaires des petites choses, comme votre première conversation. Honorer votre histoire commune vous rappelle à tous deux le chemin parcouru ensemble.",
    "Laissez votre partenaire vous influencer. Les couples s'épanouissent quand chacun prend sincèrement en compte les opinions et préférences de l'autre dans ses choix.",
    "Entretenez l'amitié au cœur de votre romance. Les blagues complices, la conversation facile et la simple compagnie sont ce qui porte l'amour à travers les saisons sans éclat.",
    "Soyez prompt à réconforter, lent à critiquer. Le rapport entre la chaleur et le reproche que vous offrez décide si le foyer devient un refuge ou un tribunal.",
    "Demandez ce que vous voulez directement et gentiment. Les sous-entendus nourrissent la frustration, tandis qu'une demande claire et douce donne à votre partenaire une vraie chance d'y répondre.",
    "Restez prêt à apprendre comment aimer cette personne précise. Ce qui marchait par le passé peut ne pas convenir ; laissez votre partenaire vous montrer ce dont il a besoin.",
    "Reconnaissez l'effort même quand le résultat n'y est pas. Souligner que votre partenaire a essayé l'encourage à continuer plutôt qu'à abandonner en silence.",
    "Regardez-vous dans les yeux quand ça compte. Fixer votre partenaire pendant qu'il partage quelque chose d'important lui dit qu'il a votre cœur tout entier, pas la moitié.",
    "Ne confiez pas votre relation au pilote automatique. L'amour durable a besoin d'une attention intentionnelle, sinon la routine remplace lentement le lien qui paraissait jadis sans effort.",
    "Acceptez d'être le premier à vous adoucir. Quelqu'un doit baisser l'épée en premier, et choisir d'être cette personne est une force, pas une défaite.",
    "Respectez les loisirs de votre partenaire même si vous ne les partagez pas. Honorer ce qui l'illumine montre que vous chérissez tout son être.",
    "Bâtissez la confiance par la constance. Faire ce que vous dites, encore et encore, apprend à votre partenaire qu'il peut enfin baisser la garde.",
    "Offrez du réconfort avant qu'on ne le demande. Apporter de l'apaisement quand vous sentez l'inquiétude de votre partenaire témoigne d'une attention que les mots d'amour seuls ne peuvent dire.",
    "Désaccordez-vous sans en faire un référendum sur la relation. Chaque conflit ne signifie pas que quelque chose ne va pas ; parfois cela signifie simplement que vous êtes deux personnes.",
    "Continuez à courtiser votre partenaire. Prévoir des moments dédiés pour vous faire beaux, sortir et vous concentrer l'un sur l'autre empêche la romance de se diluer dans la logistique.",
    "Accueillez les retours sur votre façon d'aimer. Demander « y a-t-il quelque chose que tu aimerais que je fasse autrement ? » montre de l'humilité et un vrai désir de grandir.",
    "Laissez s'accumuler les petites attentions. Une relation se bâtit moins de grands gestes que d'un millier de minuscules choix d'être prévenant et chaleureux.",
    "Faites de la place au chagrin et au stress de votre partenaire sans vous précipiter pour les résoudre. Parfois, la présence, pas les conseils, est l'amour dont il a vraiment besoin.",
    "Soyez transparent sur votre téléphone et vos projets. L'ouverture là où d'autres cacheraient bâtit une base de confiance qui rend tout le reste rassurant.",
    "Choisissez la curiosité plutôt que la jalousie. Quand l'insécurité s'enflamme, explorez la peur en vous au lieu de projeter le soupçon sur un partenaire qui n'a rien fait de mal.",
    "Faites de « on trouvera une solution ensemble » votre réflexe. Affronter l'incertitude en front uni transforme les inconnues angoissantes en aventures partagées que vous pouvez gérer.",
    "Complimentez qui ils sont, pas seulement ce qu'ils font. Dire à votre partenaire que vous admirez sa gentillesse ou son courage le nourrit plus profondément qu'un éloge pour des tâches.",
    "Protégez les moments de transition, comme les premières minutes à la maison. Vous accueillir avec chaleur plutôt que par des reproches donne le ton émotionnel des heures à venir.",
    "Rappelez-vous les choses qui comptent pour eux. Revenir sur un souci évoqué il y a des jours prouve que vous écoutiez vraiment depuis le début.",
    "Restez du même côté de la table. Quand un problème surgit, imaginez-vous assis aux côtés de votre partenaire face à lui, plutôt qu'en face à l'accuser.",
    "Gardez votre amour privé quand il a besoin d'être protégé. Tout détail n'a pas sa place sur les réseaux sociaux ; une certaine intimité reste plus forte en restant entre vous.",
    "Soyez généreux dans la reconnaissance et lent dans le reproche. Nommer ce que votre partenaire a bien fait, et assumer vos propres faux pas, empêche le ressentiment de s'enraciner.",
    "Que l'affection soit inconditionnelle, pas une récompense. Retenir la chaleur pour prouver quelque chose apprend à votre partenaire que votre amour est assorti de conditions.",
    "Grandissez ensemble en essayant de nouvelles choses côte à côte. La nouveauté partagée, du voyage à un nouveau cours, ranime l'excitation que l'amour naissant possédait naturellement.",
    "Terminez chaque journée par un moment de connexion. Quelques mots sincères ou une longue étreinte avant de dormir vous recousent l'un à l'autre après que le jour vous a séparés.",
  ],
  facts: [
    "Quand vous tombez amoureux, votre cerveau est inondé de dopamine, la même molécule de récompense liée à la motivation et au plaisir, ce qui explique pourquoi une nouvelle romance peut sembler presque addictive.",
    "L'ocytocine, souvent appelée « hormone de l'attachement », monte en flèche lors des câlins, des mains tenues et de la proximité, aidant les partenaires à se sentir liés et confiants.",
    "Des études suggèrent que se regarder dans les yeux pendant quelques minutes peut accroître le sentiment d'intimité, même entre relatifs inconnus.",
    "L'expression « tomber amoureux » est peut-être plus littérale que poétique ; les débuts d'une romance peuvent abaisser la sérotonine à des niveaux proches de ceux observés dans la pensée obsessionnelle.",
    "Les chercheurs ont découvert que tenir la main d'un être aimé peut réduire de façon mesurable la perception de la douleur physique et du stress.",
    "Votre rythme cardiaque peut réellement se synchroniser avec celui d'un partenaire amoureux quand vous êtes assis tout près et que vous vous regardez, selon des études sur les couples.",
    "Les Grecs anciens décrivaient plusieurs formes d'amour, dont l'éros (la passion), la philia (l'amitié) et l'agapè (l'amour désintéressé), reconnaissant l'amour comme bien plus qu'un seul sentiment.",
    "Les campagnols des prairies sont célèbres en science pour former des liens à vie, et les étudier a beaucoup appris aux chercheurs sur la chimie de la monogamie.",
    "La tradition de la bague de fiançailles en diamant s'est répandue surtout après une célèbre campagne publicitaire du XXe siècle proclamant « Un diamant est éternel ».",
    "Les papillons dans le ventre aux débuts de l'amour sont réels ; l'adrénaline de l'attirance peut détourner le sang du système digestif, créant cette sensation de frémissement.",
    "Des études suggèrent que les couples qui rient ensemble régulièrement déclarent une plus grande satisfaction relationnelle et se sentent plus liés avec le temps.",
    "La tradition de porter l'alliance à l'annulaire remonte à une ancienne croyance en une « vena amoris », une veine reliant directement ce doigt au cœur.",
    "L'amour romantique et l'attachement profond activent des systèmes cérébraux légèrement différents, ce qui aide à comprendre comment la passion peut mûrir en un lien plus calme et stable.",
    "Les cygnes, souvent vus comme des symboles d'amour, forment fréquemment des liens durables, restant parfois avec le même partenaire pendant de nombreuses années.",
    "Les chercheurs estiment qu'il peut falloir de quelques secondes à quelques minutes pour décider si l'on se sent attiré par une nouvelle personne.",
    "La « phase de lune de miel » de passion intense des débuts dure généralement entre plusieurs mois et environ deux ans avant de se muer en un attachement plus profond.",
    "Les câlins et l'affection physique peuvent déclencher la libération d'endorphines, les substances naturelles du bien-être qui aident aussi à réduire le stress.",
    "Dans de nombreuses cultures, le mariage était historiquement arrangé pour des raisons économiques ou politiques, et l'idée de se marier d'abord par amour est relativement récente.",
    "Des études suggèrent que les gens se sentent souvent le plus attirés par des visages à peu près symétriques, ce que certains scientifiques relient à des signaux inconscients de santé.",
    "Le mot « romance » désignait à l'origine un style de récit médiéval, ne prenant que plus tard le sens d'amour passionné qu'on lui associe aujourd'hui.",
    "L'odorat joue un rôle surprenant dans l'attirance ; la recherche suggère que le parfum peut subtilement influencer qui nous trouvons attirant comme partenaire potentiel.",
    "Les couples de longue date se mettent parfois à se ressembler légèrement, un phénomène que les chercheurs lient en partie à des décennies d'expressions, d'environnement et d'émotions partagés.",
    "La coutume de s'embrasser sous le gui remonte à des siècles et fut autrefois liée à d'anciennes traditions de paix, de fertilité et de bienveillance.",
    "Tomber amoureux peut temporairement réduire l'activité des régions cérébrales liées au jugement critique, ce qui explique en partie pourquoi l'amour peut sembler un peu aveugle.",
    "Des études suggèrent que le simple fait de s'attendre à ce que quelqu'un soit chaleureux et amical peut vous amener à agir de façon à ce qu'il vous réponde chaleureusement à son tour.",
    "Les albatros exécutent d'élaborées parades nuptiales et peuvent maintenir le même partenariat sur de nombreuses saisons de reproduction, parfois durant une grande partie de leur longue vie.",
    "Le cerveau aux débuts de l'amour peut ressembler au cerveau face à certaines récompenses, allumant les centres de récompense qui nous poussent à rechercher la proximité avec notre partenaire.",
    "Les chercheurs ont constaté que les couples qui expriment régulièrement leur gratitude se sentent plus engagés et satisfaits dans leur relation.",
    "Le symbole en forme de cœur que nous associons à l'amour ne ressemble pas vraiment à un cœur humain ; ses origines sont débattues et probablement stylisées au fil des siècles.",
    "Le toucher est l'un des premiers sens à se développer, et l'affection physique douce reste une puissante manière pour les humains de communiquer l'amour tout au long de la vie.",
    "Des études suggèrent que faire des activités nouvelles et excitantes ensemble peut renforcer la satisfaction relationnelle en recréant une part de la nouveauté des débuts.",
    "Certains manchots sont connus pour des rituels de séduction qui incluent l'offrande d'un caillou soigneusement choisi à un partenaire potentiel.",
    "L'hormone vasopressine, aux côtés de l'ocytocine, jouerait un rôle important dans l'attachement et le lien durable entre partenaires.",
    "La Saint-Valentin tire ses racines d'anciennes fêtes et de la légende de saint Valentin, évoluant au fil des siècles vers la célébration de l'amour romantique d'aujourd'hui.",
    "La recherche suggère que les gens se sentent plus proches de ceux à qui ils se confient, raison pour laquelle partager des histoires personnelles peut accélérer l'intimité.",
    "Le rougissement, réponse propre à l'humain, peut signaler l'attirance comme l'embarras, et certains chercheurs pensent qu'il a évolué en partie comme un signal social honnête.",
    "L'« effet de simple exposition » signifie que nous finissons souvent par apprécier davantage les gens simplement en les voyant à plusieurs reprises, d'où le rôle de la proximité dans la naissance d'une romance.",
    "Des études suggèrent que les couples qui traversent les conflits avec humour et douceur plutôt qu'avec mépris ont bien plus de chances de rester ensemble.",
    "Les hippocampes sont célèbres pour un arrangement inhabituel dans lequel le mâle porte et nourrit les petits en développement.",
    "La phényléthylamine, parfois surnommée « molécule de l'amour », est libérée lors de l'attirance et se trouve aussi naturellement en petites quantités dans le chocolat.",
    "À travers de nombreuses cultures et époques, les poètes ont traité l'amour comme l'un des thèmes centraux de l'humanité, signe que son attrait émotionnel est remarquablement universel.",
    "La recherche sur les « styles d'attachement » suggère que nos premiers liens avec ceux qui nous ont élevés peuvent influencer notre sécurité ou notre anxiété dans les relations adultes.",
    "Des études suggèrent que même de brefs gestes de gentillesse entre partenaires, comme préparer un thé ou envoyer un petit message, s'accumulent en une bonne volonté durable.",
    "La coutume du gâteau de mariage a d'anciennes racines, diverses cultures ayant historiquement utilisé du pain ou du gâteau dans les rituels nuptiaux pour symboliser la prospérité.",
    "Certains scientifiques pensent que le pouvoir de la musique à émouvoir est étroitement lié à l'attachement, ce qui pourrait expliquer pourquoi on trouve des chansons d'amour dans presque toutes les cultures.",
    "Les chercheurs ont observé que les couples nouvellement amoureux connaissent parfois une baisse d'appétit et des troubles du sommeil, dus en partie à la montée des substances de stress et de récompense.",
    "La « danse frétillante » de l'abeille n'est pas romantique, mais de nombreuses parades nuptiales animales sont des performances élaborées destinées à attirer et impressionner un partenaire.",
    "Des études suggèrent que se sentir apprécié est l'un des plus forts indicateurs de la satisfaction des gens et de leur désir de rester dans une relation.",
    "La tradition de porter la mariée à travers le seuil a ses racines dans d'anciennes coutumes que l'on croyait autrefois capables de protéger le couple du mauvais sort.",
    "L'amour et la douleur peuvent partager des circuits cérébraux communs, ce qui aide à comprendre pourquoi un chagrin d'amour peut être réellement douloureux physiquement.",
    "Les chercheurs étudiant des couples mariés de longue date ont découvert qu'un petit nombre disant ressentir encore un amour intense présentent une activité cérébrale semblable à celle des débuts.",
    "De nombreuses espèces d'oiseaux chantent en duo avec leur partenaire, coordonnant leurs appels avec une telle précision que cela peut sembler une seule voix.",
    "Des études suggèrent que les couples ont tendance à être plus heureux quand ils maintiennent un équilibre sain entre interactions positives et négatives au quotidien.",
    "L'échange d'anneaux comme symbole d'engagement est une pratique ancienne, apparue sous diverses formes dans de nombreuses civilisations primitives.",
    "L'attirance physique peut être influencée par quelque chose d'aussi simple qu'un cœur qui s'emballe ; l'excitation due à l'émotion est parfois confondue avec une attirance romantique.",
    "Certains chercheurs décrivent l'amour romantique comme ayant trois grandes composantes : le désir, l'attirance et l'attachement, chacune guidée par une chimie cérébrale différente.",
    "Les loups forment généralement des liens forts, un couple lié constituant souvent le noyau social de leur meute.",
    "Des études suggèrent que les partenaires qui vivent leur relation comme un lieu d'acceptation sont plus enclins à prendre de sains risques émotionnels l'un avec l'autre.",
    "La couleur rouge a été liée dans certaines études à la perception de l'attirance, les gens jugeant parfois les autres plus séduisants lorsqu'ils la portent.",
    "À travers l'histoire, les lettres d'amour ont été des trésors précieux, et des exemples ayant survécu des siècles révèlent que désir et dévotion changent peu avec le temps.",
    "Les chercheurs ont découvert qu'un toucher réconfortant d'un partenaire peut aider à faire baisser la tension artérielle et à apaiser la réaction du corps au stress.",
    "Certaines espèces de manchots, de gibbons et certains renards sont notés par les biologistes pour former des liens particulièrement forts et durables.",
    "L'« effet Roméo et Juliette » décrit comment l'opposition extérieure à une relation peut parfois intensifier, plutôt qu'affaiblir, la passion d'un couple.",
    "Des études suggèrent que le simple fait de penser à un être aimé peut activer les zones de récompense du cerveau et offrir un rempart mesurable contre le stress.",
    "De nombreuses cultures échangeaient historiquement des gages de fiançailles, des anneaux aux rubans en passant par les pièces, bien avant l'apparition des traditions modernes.",
    "La recherche suggère que les gens sous-estiment souvent à quel point un compliment sincère illuminera la journée de leur partenaire, laissant trop souvent les mots gentils inexprimés.",
    "Les gibbons sont connus parmi les primates pour former des liens durables et même chanter ensemble des appels matinaux coordonnés.",
    "Le sentiment d'« alchimie » avec quelqu'un peut en partie refléter à quel point votre système nerveux se sent à l'aise et détendu en sa présence.",
    "Des études suggèrent que les couples qui partagent et célèbrent les bonnes nouvelles ensemble, et pas seulement se soutiennent dans les moments durs, se sentent plus liés.",
    "Les castors s'apparient généralement et travaillent ensemble pour construire et entretenir leur hutte, partageant le labeur d'élever leurs petits.",
    "L'expression « se passer la corde au cou » vient probablement d'anciennes coutumes de mariage de diverses cultures qui liaient littéralement les mains du couple.",
    "La recherche sur l'attirance suggère que le sens de l'humour est l'un des traits les plus communément valorisés que les gens recherchent chez un partenaire de longue durée.",
    "Certains scientifiques pensent que la tendance humaine à former des liens de couple a pu évoluer en partie pour soutenir la longue tâche d'élever des enfants.",
    "Des études suggèrent que les couples qui maintiennent des rituels partagés, aussi minimes soient-ils, rapportent un sentiment plus fort d'identité et d'appartenance commune.",
    "Le mythe de Cupidon, la figure ailée qui transperce les cœurs de ses flèches, vient de la mythologie romaine et de la figure grecque plus ancienne d'Éros.",
    "Les chercheurs ont découvert que se sentir compris par un partenaire est étroitement lié au sentiment d'être aimé, parfois même plus que les grands gestes romantiques.",
    "Certaines antilopes, grues et certains perroquets figurent parmi les nombreux animaux que les biologistes ont observés maintenir des liens durables avec un seul partenaire.",
    "Des études suggèrent que la façon dont les couples gèrent les petits agacements quotidiens prédit la satisfaction à long terme plus fidèlement que la façon dont ils affrontent de rares grandes crises.",
    "La tradition d'une escapade de « lune de miel » après le mariage est devenue populaire au XIXe siècle, bien que le mot lui-même soit bien plus ancien.",
    "La recherche suggère que la proximité physique pendant le sommeil, comme la présence d'un partenaire tout près, peut subtilement améliorer le sentiment de sécurité et de repos.",
    "Certaines fleurs, surtout la rose rouge, sont devenues des symboles durables de l'amour à travers des siècles de poésie, d'art et de tradition culturelle.",
    "Des études suggèrent que les couples capables de réparer vite après un conflit, plutôt que de l'éviter parfaitement, ont tendance à avoir les relations les plus solides.",
    "Le système de récompense du cerveau peut réagir au sourire d'un partenaire de façon semblable à d'autres expériences profondément gratifiantes, renforçant l'attrait de l'amour.",
    "De nombreuses cultures ont développé des traditions d'entremise, et des marieurs professionnels ont existé dans diverses sociétés pendant des centaines d'années.",
    "La recherche suggère qu'exprimer son affection à travers le « langage de l'amour » préféré de votre partenaire touche plus fort que de l'affection à vos propres conditions.",
    "Les cigognes, souvent associées aux bébés dans le folklore, sont aussi connues pour revenir fréquemment au même nid et au même partenaire d'année en année.",
    "Des études suggèrent que la nostalgie des souvenirs partagés peut renforcer le lien d'un couple en lui rappelant son histoire et sa résilience communes.",
    "La coutume des demoiselles d'honneur remonte peut-être à d'anciennes traditions où des suivantes vêtues de façon semblable étaient censées tromper les mauvais esprits.",
    "La recherche suggère que les couples qui maintiennent un sentiment de « nous » plutôt que de « moi contre toi » pendant les désaccords les résolvent plus constructivement.",
    "Les pygargues à tête blanche forment souvent des liens durables et peuvent revenir ensemble au même site de nidification pendant de nombreuses années.",
    "Des études suggèrent que l'anticipation peut accroître le bonheur, raison pour laquelle se réjouir à l'avance d'un moment avec un partenaire peut être presque aussi joyeux que le moment lui-même.",
    "La tradition d'offrir des fleurs en geste romantique est documentée à travers de nombreuses cultures et siècles comme un langage de l'affection.",
    "La recherche suggère que les gens en relation soutenante ont tendance à se remettre de la maladie et du stress un peu plus vite que ceux qui se sentent isolés.",
    "Certaines espèces de cichlidés sont remarquées par les biologistes pour coopérer en couple afin de garder et soigner leurs œufs et leurs petits.",
    "Des études suggèrent que les couples qui s'expriment régulièrement de l'affection physique, au-delà des seuls moments de réconciliation, maintiennent des liens émotionnels plus forts.",
    "La notion d'« âme sœur » apparaît en philosophie depuis l'Antiquité, notamment dans un célèbre mythe relaté dans les écrits de Platon.",
    "La recherche suggère que le simple fait d'avoir un partenaire à qui se confier est associé à une plus grande résilience dans les moments les plus stressants de la vie.",
    "Les poissons-anges français figurent parmi les espèces que les biologistes ont observées voyager et défendre leur territoire en couples fidèles et coopératifs.",
    "Des études suggèrent que l'habitude des débuts d'idéaliser un partenaire, dans une certaine mesure, peut en réalité aider les couples à rester satisfaits avec le temps.",
    "La poignée de main et le baiser comme salutations ont tous deux de profondes racines historiques, le baiser romantique apparaissant dans de nombreuses cultures anciennes.",
    "La recherche suggère que les couples qui se réservent du temps de loisir partagé, même de brefs instants, se sentent plus proches et davantage en équipe.",
    "Certains scientifiques pensent que la capacité humaine universelle d'aimer pourrait être l'un des outils les plus puissants de l'évolution pour la coopération et la survie.",
    "Des études suggèrent que se sentir en sécurité dans une relation libère les gens et les rend plus audacieux et confiants dans le reste de leur vie.",
    "La tradition de la poésie amoureuse remonte à des milliers d'années, certains des plus anciens poèmes d'amour connus ayant été écrits sur d'antiques tablettes d'argile.",
    "La recherche suggère que les partenaires se sentent souvent le plus aimés non lors de gestes spectaculaires, mais dans de petits moments constants d'attention et de soin.",
    "Certaines espèces de hiboux forment des liens durables et coopèrent étroitement pour élever leurs petits, se partageant la chasse et la garde du nid.",
    "Des études suggèrent que les couples qui entretiennent des amitiés et des centres d'intérêt personnels, en parallèle de leur relation, rapportent un bonheur commun plus grand sur le long terme.",
    "Le voile porté par certaines mariées a des origines anciennes, apparaissant dans diverses cultures comme symbole de pudeur, de mystère ou de protection.",
    "La recherche suggère que l'expérience de l'émerveillement, comme regarder un coucher de soleil ensemble, peut approfondir le sentiment de connexion et de sens partagé d'un couple.",
    "De nombreuses cultures ont des traditions populaires de charmes et de gages d'amour, reflet d'un désir humain intemporel d'attirer et de garder l'affection.",
    "Des études suggèrent que la réceptivité, le sentiment que votre partenaire remarque et se soucie vraiment de vos besoins, est au cœur du sentiment d'être profondément aimé.",
    "L'idée de célébrer un anniversaire de mariage avec des cadeaux précis, comme le papier ou l'or pour certaines années, s'est développée peu à peu au cours des derniers siècles.",
    "La recherche suggère que même imaginer des moments futurs avec un partenaire peut renforcer l'engagement présent et la motivation à entretenir la relation.",
    "Certains gorfous macaroni et autres oiseaux marins retrouvent le même partenaire à chaque saison de reproduction, après des mois passés séparés en mer.",
    "Des études suggèrent que le simple fait de dire « merci » à un partenaire peut enclencher un cercle vertueux d'appréciation et de générosité.",
    "Le mot « câlin » peut sembler moderne, mais les humains recherchent le réconfort d'un contact physique proche depuis les tout premiers instants de notre espèce.",
    "La recherche suggère que les couples qui voient les défis comme des problèmes communs à résoudre, plutôt que comme des défauts personnels, ont tendance à se renforcer dans l'épreuve.",
  ],
  quotes: [
    { text: "De quoi que soient faites nos âmes, la sienne et la mienne sont identiques.", author: "Emily Brontë" },
    { text: "On sait qu'on est amoureux quand on n'arrive plus à dormir parce que la réalité est enfin plus belle que les rêves.", author: "Dr. Seuss" },
    { text: "L'amour est fait d'une seule âme habitant deux corps.", author: "Aristote" },
    { text: "La plus belle chose à laquelle se raccrocher dans la vie, c'est l'autre.", author: "Audrey Hepburn" },
    { text: "Nous sommes le plus vivants quand nous aimons.", author: "John Updike" },
    { text: "L'amour est cet état où le bonheur d'une autre personne est essentiel au vôtre.", author: "Robert A. Heinlein" },
    { text: "Aimer et être aimé, c'est sentir le soleil des deux côtés.", author: "David Viscott" },
    { text: "Il n'existe d'autre remède à l'amour que d'aimer davantage.", author: "Henry David Thoreau" },
    { text: "Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.", author: "Antoine de Saint-Exupéry" },
    { text: "Si je sais ce qu'est l'amour, c'est grâce à toi.", author: "Hermann Hesse" },
    { text: "Le plus grand bonheur de la vie, c'est la conviction d'être aimé.", author: "Victor Hugo" },
    { text: "L'amour est une amitié qui a pris feu.", author: "Ann Landers" },
    { text: "Là où il y a de l'amour, il y a de la vie.", author: "Mahatma Gandhi" },
    { text: "Être profondément aimé par quelqu'un vous donne de la force, tandis qu'aimer quelqu'un profondément vous donne du courage.", author: "Lao Tseu" },
    { text: "L'amour, c'est quand le bonheur de l'autre compte plus que le vôtre.", author: "H. Jackson Brown Jr." },
    { text: "Le cœur a ses raisons que la raison ne connaît point.", author: "Blaise Pascal" },
    { text: "Un mariage réussi exige de tomber amoureux plusieurs fois, toujours de la même personne.", author: "Mignon McLaughlin" },
    { text: "Nous nous aimions d'un amour plus grand que l'amour.", author: "Edgar Allan Poe" },
    { text: "Mais les plus belles choses du monde ne peuvent être vues ni même touchées : elles doivent être ressenties avec le cœur.", author: "Helen Keller" },
    { text: "Aimer, ce n'est pas trouver quelqu'un avec qui vivre. C'est trouver quelqu'un sans qui on ne peut vivre.", author: "Rafael Ortiz" },
    { text: "L'amour ne connaît pas de barrières. Il franchit les obstacles, saute les clôtures, traverse les murs pour arriver à destination, plein d'espoir.", author: "Maya Angelou" },
    { text: "L'amour est un désir irrésistible d'être irrésistiblement désiré.", author: "Robert Frost" },
    { text: "On n'épouse pas quelqu'un avec qui on peut vivre, on épouse la personne sans qui on ne peut pas vivre.", author: "Inconnu" },
    { text: "Le cours du véritable amour n'a jamais été paisible.", author: "William Shakespeare" },
    { text: "Aime tout le monde, accorde ta confiance à quelques-uns, ne fais de tort à personne.", author: "William Shakespeare" },
    { text: "L'amour ne regarde pas avec les yeux, mais avec l'âme.", author: "William Shakespeare" },
    { text: "J'ai trouvé celui que mon âme aime.", author: "Cantique des Cantiques" },
    { text: "L'amour est patient, l'amour est bon. Il n'envie point, il ne se vante point, il ne s'enfle point d'orgueil.", author: "1 Corinthiens 13:4" },
    { text: "Au contact de l'amour, chacun devient poète.", author: "Platon" },
    { text: "Donner de l'amour est une éducation en soi.", author: "Eleanor Roosevelt" },
    { text: "L'amour est la fleur qu'il faut laisser grandir.", author: "John Lennon" },
    { text: "Tout ce dont on a besoin, c'est d'amour.", author: "John Lennon" },
    { text: "L'amour est, ou il n'est pas. Un amour ténu n'est pas un amour du tout.", author: "Toni Morrison" },
    { text: "L'amour ôte les masques que nous craignons de ne pouvoir vivre sans eux, alors que nous savons ne pouvoir vivre avec.", author: "James Baldwin" },
    { text: "L'amour est un fruit de toutes les saisons, à la portée de toutes les mains.", author: "Mère Teresa" },
    { text: "Répandez l'amour partout où vous allez. Que nul ne vous quitte sans repartir plus heureux.", author: "Mère Teresa" },
    { text: "Ce n'est qu'en aimant que l'on apprend à aimer.", author: "Iris Murdoch" },
    { text: "L'amour n'est pas une chose que l'on trouve. L'amour est une chose qui vous trouve.", author: "Loretta Young" },
    { text: "L'art d'aimer est en grande partie l'art de la persévérance.", author: "Albert Ellis" },
    { text: "Aimer, quoi qu'il arrive, c'est se rendre vulnérable.", author: "C. S. Lewis" },
    { text: "L'amour n'est pas un sentiment d'affection, mais un souhait constant du bien ultime de l'être aimé.", author: "C. S. Lewis" },
    { text: "L'amour est le tout. Nous ne sommes que des fragments.", author: "Rûmî" },
    { text: "Ta tâche n'est pas de chercher l'amour, mais seulement de chercher et de trouver en toi toutes les barrières que tu as dressées contre lui.", author: "Rûmî" },
    { text: "Que la beauté de ce que tu aimes soit ce que tu fais.", author: "Rûmî" },
    { text: "L'amour est le pont entre toi et tout le reste.", author: "Rûmî" },
    { text: "La gravitation n'est pas responsable du fait que les gens tombent amoureux.", author: "Albert Einstein" },
    { text: "L'amour consiste en ceci : deux solitudes se protègent, se touchent et se saluent l'une l'autre.", author: "Rainer Maria Rilke" },
    { text: "Une fois que l'on a appris à aimer, on a appris à vivre.", author: "Inconnu" },
    { text: "L'amour est fait de bien des choses, mais son fondement est l'amitié et la confiance.", author: "Inconnu" },
    { text: "Quand on aime quelqu'un, on l'aime tel qu'il est, et non tel qu'on voudrait qu'il soit.", author: "Léon Tolstoï" },
    { text: "Il descendit en s'efforçant de ne pas la regarder longuement, comme on évite de fixer le soleil, mais il la voyait, comme le soleil, sans même la regarder.", author: "Léon Tolstoï" },
    { text: "Doute que les étoiles soient de feu ; doute que le soleil se meuve ; doute que la vérité soit vérité ; mais ne doute jamais de mon amour.", author: "William Shakespeare" },
    { text: "Comment t'aimé-je ? Laisse-moi en compter les façons.", author: "Elizabeth Barrett Browning" },
    { text: "L'amour précède la vie, succède à la mort, est le commencement de la création et le souffle même de l'être.", author: "Emily Dickinson" },
    { text: "Que l'amour soit tout ce qui existe, voilà tout ce que nous savons de lui.", author: "Emily Dickinson" },
    { text: "Si tu vis jusqu'à cent ans, je veux vivre jusqu'à cent ans moins un jour, pour ne jamais avoir à vivre sans toi.", author: "A. A. Milne" },
    { text: "L'amour est une toile fournie par la nature et brodée par l'imagination.", author: "Voltaire" },
    { text: "Les plus belles choses de ce monde ne peuvent être ni vues ni même entendues, mais doivent être ressenties avec le cœur.", author: "Helen Keller" },
    { text: "Une fleur ne peut s'épanouir sans soleil, et l'homme ne peut vivre sans amour.", author: "Max Müller" },
    { text: "L'amour est comme le vent : on ne le voit pas, mais on le sent.", author: "Nicholas Sparks" },
    { text: "Le simple manque d'elle me touche plus que la présence des autres.", author: "Edward Thomas" },
    { text: "Je préférerais partager une seule vie avec toi que d'affronter seul tous les âges de ce monde.", author: "J. R. R. Tolkien" },
    { text: "L'amour est la clé maîtresse qui ouvre les portes du bonheur.", author: "Oliver Wendell Holmes" },
    { text: "Nous sommes façonnés et formés par ce que nous aimons.", author: "Johann Wolfgang von Goethe" },
    { text: "L'amour et la toux ne peuvent se cacher.", author: "George Herbert" },
    { text: "Deux êtres s'aiment en se passant le monde l'un à l'autre.", author: "Inconnu" },
    { text: "L'amour fait sortir l'âme de sa cachette.", author: "Zora Neale Hurston" },
    { text: "Il y a toujours un peu de folie dans l'amour. Mais il y a aussi toujours un peu de raison dans la folie.", author: "Friedrich Nietzsche" },
    { text: "L'amour est la seule force capable de transformer un ennemi en ami.", author: "Martin Luther King Jr." },
    { text: "Nous devons développer et préserver la capacité de pardonner.", author: "Martin Luther King Jr." },
    { text: "La façon d'aimer une chose, c'est de comprendre qu'elle peut être perdue.", author: "G. K. Chesterton" },
    { text: "Aimer n'est jamais une perte de temps.", author: "Astrid Alauda" },
    { text: "L'amour est la voix sous tous les silences, l'espoir qui n'a pour opposé aucune peur.", author: "E. E. Cummings" },
    { text: "Je porte ton cœur en moi. Je le porte dans mon cœur.", author: "E. E. Cummings" },
    { text: "L'amour grandit en se donnant. L'amour que nous donnons est le seul que nous gardons.", author: "Elbert Hubbard" },
    { text: "Aimer n'est rien. Être aimé est quelque chose. Mais aimer et être aimé, voilà tout.", author: "T. Tolis" },
    { text: "L'amour planta une rose, et le monde devint doux.", author: "Katharine Lee Bates" },
    { text: "L'amour est l'expansion de deux natures de telle sorte que chacune contient l'autre.", author: "Felix Adler" },
    { text: "Dis-moi qui tu aimes, et je te dirai qui tu es.", author: "Houssaye" },
    { text: "Là où tu étais, il y a dans le monde un vide que je me surprends à contourner sans cesse en plein jour.", author: "Edna St. Vincent Millay" },
  ],
};
