import type { RotationalContent } from '@/lib/dailyContentTypes';

export const it: RotationalContent = {
  tips: [
    "Ascolta per capire, non per rispondere. Fare una pausa prima di replicare mostra al partner che le sue parole sono davvero arrivate, e questa piccola abitudine rafforza la fiducia nel tempo.",
    "Ringrazia per le cose ordinarie. Notare il caffè preparato o i piatti lavati ricorda al partner che il suo impegno quotidiano non passa mai inosservato.",
    "Quando nasce un conflitto, affrontate insieme il problema invece di attaccarvi a vicenda. Siete compagni di squadra di fronte a una questione, non avversari che cercano di vincere un punto.",
    "Programmate del tempo insieme senza fretta, anche solo venti minuti. La connessione raramente nasce nei ritagli; cresce quando le fate spazio di proposito.",
    "Chiedi al partner come preferisce essere confortato. Alcuni vogliono soluzioni, altri un abbraccio e il silenzio, e indovinare male può far sentire distanza.",
    "Ripara in fretta dopo un disaccordo. Un sincero confronto quando gli animi si placano conta molto più del fingere che l'attrito non sia mai esistito.",
    "La curiosità mantiene vivo l'amore. Continua a fare nuove domande al partner di sempre, perché le persone cambiano in silenzio e le più interessanti sono ancora in divenire.",
    "Esprimi l'apprezzamento ad alta voce, non solo nella tua testa. La gratitudine taciuta scalda solo te, mentre quella espressa scalda la persona che ami.",
    "Proteggi la relazione dal disprezzo. Alzare gli occhi al cielo e il sarcasmo corrodono il legame più velocemente di quasi tutto, quindi scegli il rispetto anche quando sei frustrato.",
    "Rendi importanti i piccoli inviti alla connessione. Quando il partner condivide qualcosa di piccolo, voltarti verso di lui con attenzione è il collante silenzioso dell'amore duraturo.",
    "Scusati senza aggiungere 'ma'. Una scusa pulita si assume pienamente la propria parte, mentre una scusa condizionata rimanda silenziosamente la colpa dall'altra parte del tavolo.",
    "Conservate alcuni rituali che sono solo vostri. Una passeggiata domenicale o il caffè condiviso al mattino creano un ritmo costante che àncora insieme vite frenetiche.",
    "Presumi la buona intenzione prima di pensare al peggio. La maggior parte dei momenti dolorosi nasce da goffaggine o stress, non da un partner che ti augura segretamente del male.",
    "Parlate di denaro presto e spesso. Allinearsi su spese, risparmi e obiettivi previene il risentimento silenzioso che le finanze possono altrimenti creare di nascosto.",
    "Lascia che il partner sia diverso da te. La compatibilità non è uguaglianza; è due persone distinte che scelgono di onorare il mondo interiore separato dell'altra.",
    "Nota ciò che il partner sta portando sulle spalle. Un gentile 'sembri stanco, al cena ci penso io' può dire ti amo più forte delle parole.",
    "Conserva una certa indipendenza dentro la condivisione. Coltivare amici e passioni tutti tuoi ti rende un partner più interessante ed energico a cui tornare.",
    "Loda in pubblico, risolvi i problemi in privato. Valorizzare il partner davanti agli altri e gestire gli attriti in privato protegge sia l'orgoglio sia la fiducia.",
    "Sostituisci 'tu sempre' e 'tu mai' con 'io mi sento'. Parlare dalla tua esperienza invita alla comprensione, mentre le accuse generiche invitano alla difesa.",
    "Il contatto conta anche quando non c'è niente che non va. Una mano sulla spalla o un abbraccio veloce mantengono il corpo nel ricordo di essere amato.",
    "Scegli di nuovo il tuo partner nei giorni difficili. L'amore non è solo la scintilla in cui sei caduto, ma la decisione che rinnovi quando le cose si fanno pesanti.",
    "Interessati al suo mondo. Fare domande vere sul lavoro, le preoccupazioni e i sogni del partner gli dice che la sua vita conta davvero per te.",
    "Non tenere il conto. La generosità data per essere ricambiata è una transazione; l'amore prospera quando dai liberamente e ti fidi che l'equilibrio si ristabilisca.",
    "Nomina chiaramente i tuoi bisogni. Il partner non può leggerti nel pensiero, e sperare in silenzio che indovini finisce spesso in delusione per entrambi.",
    "Ridete spesso insieme. L'umorismo condiviso abbassa la tensione, costruisce intimità e ti ricorda che la persona accanto a te è anche il tuo compagno preferito.",
    "Donate piena presenza ai ritrovi. Salutare il partner con calore quando vi riunite, telefono giù e occhi su, dà il tono alla serata.",
    "Perdona in fretta le piccole cose. Trattenere i piccoli rancori costruisce un muro mattone dopo mattone, finché non riuscite più a raggiungervi.",
    "Festeggia le vittorie del partner come fossero le tue. La gioia genuina per i suoi successi, senza invidia, è una delle forme più profonde d'amore.",
    "Verifica prima di dare per scontato di esservi allontanati. Un semplice 'come stiamo andando ultimamente?' spesso rivela un legame che la distanza sembrava solo minacciare.",
    "Rispettate i confini l'uno dell'altro senza prenderla sul personale. Un confine è un'informazione sui bisogni del partner, non un rifiuto verso di te.",
    "Fate tentativi di riparazione durante i litigi, come un tono più dolce o una piccola battuta. Accettare questi rami d'ulivo offerti evita che i disaccordi degenerino.",
    "Presentati per la logistica noiosa. Dividere equamente faccende, commissioni e organizzazione è uno dei linguaggi dell'amore più sottovalutati che esistano.",
    "Sii onesto sulle piccole cose. La fiducia si costruisce in minuscoli momenti di verità, e le piccole bugie insegnano in silenzio al partner a dubitare di te.",
    "Chiedi 'di cosa hai bisogno da me in questo momento?'. Questa sola domanda taglia corto le supposizioni e dà al partner esattamente il sostegno che desidera.",
    "Continua a flirtare con il partner di sempre. Un occhiolino, un complimento, un bacio rubato gli ricordano che è ancora desiderato, non solo affidabile.",
    "Lascia che abbia una brutta giornata. Non devi sistemare ogni umore; a volte la cosa più gentile è semplicemente restargli vicino mentre passa.",
    "Parlate della relazione quando le cose vanno bene, non solo quando si rompono. Le conversazioni di manutenzione prevengono quelle di crisi più grandi.",
    "Onora la relazione davanti agli altri. Parlare con calore del partner quando non c'è protegge il legame dalla corrosione esterna.",
    "Nota il tuo ruolo nei litigi ricorrenti. Chiedersi 'qual è il mio dieci per cento qui?' trasforma un punto morto in un'occasione per crescere insieme.",
    "Prendete le decisioni l'uno con l'altro, non l'uno per l'altro. Anche le piccole consultazioni comunicano rispetto e ricordano al partner che siete davvero una squadra.",
    "Calmati prima delle grandi conversazioni. Affrontare un discorso difficile sereni anziché travolti aiuta a dire ciò che si intende invece di ciò che ferisce.",
    "Accogli la crescita del partner anche quando è scomoda. Amare qualcuno significa tifare per la persona che sta diventando, non solo per quella che hai incontrato.",
    "Sorprendilo con l'impegno, non solo con i regali. Organizzare una serata premurosa o imparare la sua ricetta preferita mostra un amore che il denaro non può comprare.",
    "Sii il luogo sicuro in cui può espirare. Quando casa è l'unico posto in cui può rilassarsi del tutto, la vostra relazione diventa il suo rifugio.",
    "Chiedi dei momenti belli e brutti della sua giornata. Questo semplice rituale crea una finestra quotidiana sul clima emotivo interiore del partner.",
    "Convalida i sentimenti anche quando non sei d'accordo con la logica. 'Ha senso che tu ti senta così' placa le tempeste molto meglio del correggere i fatti.",
    "Fai promesse abbastanza piccole da mantenere. L'affidabilità costruita su impegni modesti e rispettati guadagna più fiducia dei grandi voti che fatichi a mantenere.",
    "Prenditi la responsabilità della tua felicità. Un partner può arricchire la tua gioia, ma aspettarsi che ne sia l'unica fonte è un fardello pesante.",
    "Rivisitate ogni tanto i vostri sogni condivisi. Parlare del futuro che state costruendo mantiene in prospettiva gli attriti quotidiani e viva la motivazione.",
    "Fatti sentire durante le lunghe giornate lontani. Un breve messaggio a metà giornata per dire che stai pensando a lui evita che il filo della connessione si allenti.",
    "Lascia perdere il bisogno di avere ragione per restare connessi. Vincere una discussione perdendo il calore del partner è raramente una vittoria da rivendicare.",
    "Riconoscete i linguaggi dell'amore che ciascuno parla. Se tu offri parole ma lui desidera tempo, il tuo impegno potrebbe mancarlo di poco.",
    "Crea una zona senza telefono a cena. I pasti senza distrazioni sono un'occasione quotidiana per vedere e ascoltare davvero la persona seduta di fronte a te.",
    "Sii delicato con le insicurezze del partner. I punti in cui si sente fragile meritano la tua cura, non le tue prese in giro, anche nei momenti scherzosi.",
    "Fate spazio sia al 'tempo per me' sia al 'tempo per noi'. Onorare solitudine e condivisione evita che la relazione sembri una prigione o una distanza.",
    "Esprimi apertamente desiderio e ammirazione. Dire al partner in modo specifico cosa trovi attraente in lui non stanca mai e non resta mai senza riconoscimento.",
    "Affronta il risentimento finché è piccolo. Nominare con gentilezza una frustrazione minore evita che si indurisca in silenzio in un rancore che poi non sai spiegare.",
    "Mostra interesse per i suoi amici e la sua famiglia. Accogliere le persone che il partner ama segnala che ti interessa tutta la sua vita, non solo lui.",
    "Rallenta quando percepisci una disconnessione. Anziché allontanarti ancora di più, avvicinati con delicatezza e chiedi cosa ha in mente il partner.",
    "Custodisci al sicuro i segreti e le storie del partner. Essere qualcuno a cui può confidarsi pienamente è il fondamento della vera intimità emotiva.",
    "Nelle prime frequentazioni, osserva come tratta chi non può fare nulla per lui. La gentilezza verso camerieri e sconosciuti rivela il vero carattere.",
    "Non avere fretta di definire tutto. Lasciare respirare la connessione iniziale ti permette di vedere chi è davvero una persona prima che le etichette creino pressioni o presunzioni.",
    "Adàttati al suo ritmo senza perdere te stesso. Un nuovo amore sano bilancia entusiasmo e pazienza, lasciando che la fiducia cresca naturalmente invece di forzare l'intensità.",
    "Cerca qualcuno con cui anche i giorni ordinari siano belli, non solo quelli emozionanti. La compatibilità quotidiana sopravvive sempre alla chimica drammatica.",
    "Presta attenzione a come un appuntamento gestisce la delusione. Il modo in cui qualcuno reagisce a una piccola contrarietà anticipa come affronterà quelle più grandi.",
    "Nell'amore a distanza, proteggete un senso condiviso di vita normale. Guardare una serie insieme o fare commissioni in videochiamata mantiene viva la vicinanza.",
    "Pianificate la prossima visita prima del saluto attuale. Avere una data sul calendario dà alle coppie a distanza qualcosa di concreto a cui aggrapparsi.",
    "Comunicate con generosità nonostante i chilometri. La distanza rende pericolose le supposizioni, quindi condividete contesto e rassicurazioni più del necessario, invece di lasciare che il silenzio venga frainteso.",
    "La fiducia è la valuta della distanza. Senza la vicinanza quotidiana, scegliere di credere il meglio l'uno dell'altro diventa la spina dorsale della relazione.",
    "Pratica l'amore per te stesso così da portare pienezza, non bisogno. Gradire la propria compagnia ti rende un partner che sceglie l'amore invece di aggrapparsi a esso.",
    "Parla a te stesso come parleresti alla persona amata. Il dialogo interiore duro filtra nelle relazioni, mentre la gentilezza verso sé lascia fluire il calore verso l'esterno.",
    "Cura le tue vecchie ferite invece di chiedere a un partner di farlo. Una relazione amorevole può sostenere la tua crescita, ma non può sostituire il tuo lavoro personale.",
    "Conosci il tuo valore prima di negoziare l'amore. Chi comprende il proprio valore raramente si accontenta di essere il ripensamento o il piano di riserva di qualcuno.",
    "Resta con le emozioni scomode invece di scaricarle. Nominare ciò che provi prima di reagire evita che il partner assorba le tue tempeste non elaborate.",
    "Sviluppa la capacità di restare regolato sotto stress. La tua presenza calma durante i momenti difficili del partner è una forma d'amore silenziosa e potente.",
    "Leggi l'emozione sotto le parole. Quando il partner sbotta per i piatti, il vero messaggio è spesso 'mi sento poco sostenuto', e questo merita la tua attenzione.",
    "Guida con l'empatia quando il partner è turbato, anche con te. La difesa può aspettare; sentirsi compresi è ciò che davvero distende il momento.",
    "Costruite insieme un vocabolario emotivo. Le coppie che sanno nominare con precisione i sentimenti tendono a risolvere i conflitti più in fretta di chi resta bloccato su 'bene' e 'arrabbiato'.",
    "Lascia che la vicinanza fisica sia una conversazione a sé. Tenersi senza secondi fini può comunicare una sicurezza che le parole a volte faticano a raggiungere.",
    "Mantieni l'intimità varia e senza fretta. Il legame si approfondisce quando trattate la vicinanza fisica come esplorazione e gioco anziché routine o obbligo.",
    "Parlate apertamente di ciò che ciascuno ama. Una conversazione comoda e onesta sull'intimità costruisce fiducia e impedisce al desiderio di svanire nelle supposizioni.",
    "Sii prima di tutto amico del tuo partner. Le coppie che durano tendono a piacersi davvero, godendo della conversazione molto dopo che le prime scintille si sono placate.",
    "Compi piccoli gesti di servizio senza che te lo chiedano. Riempirgli il serbatoio o caricargli il telefono dice in silenzio 'ti penso' per tutto il giorno.",
    "Trovate un compromesso scambiando priorità, non dividendo tutto a metà. Cedere del tutto dove conta meno per te guadagna benevolenza dove conta di più.",
    "Cerca la soluzione vantaggiosa per entrambi prima di accontentarti del compromesso. Molti conflitti si ammorbidiscono quando ci si chiede cosa soddisferebbe davvero entrambi.",
    "Mantieni i confini con calore, non con freddezza. Puoi dire di no con chiarezza lasciando comunque che il partner si senta amato e rispettato per tutto il tempo.",
    "Non punire la vulnerabilità. Quando il partner si apre su una paura o un errore, accoglierlo con tenerezza fa sì che si fidi di nuovo di te.",
    "Costruite una cultura dell'apprezzamento, cercando ciò che va bene. Le coppie che notano attivamente il buono l'uno nell'altro riferiscono una felicità molto più duratura.",
    "Fai sentire il partner scelto, non solo tollerato. Ricordargli, a parole e con i fatti, che lo sceglieresti di nuovo mantiene vivo l'amore.",
    "Concedi al partner il beneficio del dubbio ad alta voce. Dire 'sono sicuro che non intendevi così' disinnesca la tensione prima che si accumuli.",
    "Tratta le irritazioni del partner come dati, non come attacchi. Ciò che lo infastidisce spesso indica un bisogno insoddisfatto che vale la pena capire anziché liquidare.",
    "Mantieni la curiosità più grande del giudizio. Quando qualcosa del partner ti lascia perplesso, chiedi con interesse invece di concludere con la critica.",
    "Festeggiate gli anniversari delle piccole cose, come la vostra prima conversazione. Onorare la vostra storia condivisa ricorda a entrambi quanta strada avete fatto insieme.",
    "Lascia che il partner ti influenzi. Le coppie prosperano quando ciascuno tiene davvero conto delle opinioni e delle preferenze dell'altro nel fare le scelte.",
    "Cura l'amicizia dentro la vostra storia d'amore. Battute private condivise, conversazione facile e semplice compagnia sono ciò che porta l'amore attraverso le stagioni meno glamour.",
    "Sii rapido a confortare, lento a criticare. Il rapporto tra calore e lamentela che offri determina se casa sembra un rifugio o un giudizio.",
    "Chiedi ciò che vuoi in modo diretto e gentile. Le allusioni generano frustrazione, mentre una richiesta chiara e delicata dà al partner una vera possibilità di accontentarti.",
    "Resta disposto a imparare come amare questa persona specifica. Ciò che funzionava nelle relazioni passate potrebbe non andare bene; lascia che il partner ti mostri di cosa ha bisogno.",
    "Riconosci l'impegno anche quando i risultati sono insufficienti. Riconoscere che il partner ci ha provato lo incoraggia a continuare invece di arrendersi in silenzio.",
    "Guardati negli occhi quando conta. Guardare il partner mentre condivide qualcosa di importante gli dice che ha tutto il tuo cuore, non metà.",
    "Non affidare la relazione al pilota automatico. L'amore duraturo ha bisogno di attenzione intenzionale, altrimenti la routine sostituisce lentamente la connessione che un tempo sembrava naturale.",
    "Sii disposto a essere il primo ad ammorbidirti. Qualcuno deve abbassare la spada per primo, e scegliere di essere quella persona è una forza, non una perdita.",
    "Tratta con rispetto gli hobby del partner anche se non li condividi. Onorare ciò che lo illumina mostra che hai a cuore tutto il suo essere.",
    "Costruisci fiducia con la coerenza. Fare ciò che dici, ancora e ancora, insegna al partner che può finalmente abbassare la guardia.",
    "Offri rassicurazione prima che venga richiesta. Dare conforto quando percepisci la preoccupazione del partner mostra un'attenzione che le sole parole d'amore non possono.",
    "Discutete senza farne un referendum sulla relazione. Non ogni conflitto significa che qualcosa non va; a volte significa solo che siete due persone.",
    "Continua a corteggiare il tuo partner. Programmare un tempo intenzionale per agghindarvi, uscire e concentrarvi l'uno sull'altro evita che il romanticismo svanisca nella logistica.",
    "Accogli i riscontri su come ami. Chiedere 'c'è qualcosa che vorresti facessi diversamente?' mostra umiltà e un vero desiderio di crescere.",
    "Lascia che le piccole gentilezze si accumulino. Una relazione si costruisce meno dai grandi gesti che da mille minuscole scelte di essere premurosi e affettuosi.",
    "Fai spazio al dolore e allo stress del partner senza correre a risolverli. A volte la presenza, non i consigli, è l'amore di cui ha davvero bisogno.",
    "Sii trasparente su telefono e programmi. L'apertura dove altri nasconderebbero costruisce una base di fiducia che fa sentire al sicuro tutto il resto.",
    "Scegli la curiosità invece della gelosia. Quando l'insicurezza divampa, esplora la paura dentro di te invece di proiettare sospetti su un partner che non ha fatto nulla di male.",
    "Fai del 'lo risolveremo insieme' la tua impostazione predefinita. Affrontare l'incertezza come fronte unito trasforma gli ignoti spaventosi in avventure condivise che potete gestire.",
    "Fai i complimenti per chi sono, non solo per ciò che fanno. Dire al partner che ammiri la sua gentilezza o il suo coraggio lo nutre più profondamente della lode per i compiti svolti.",
    "Proteggi i momenti di transizione, come i primi minuti a casa. Salutarvi con calore invece che con lamentele dà il tono emotivo alle ore a venire.",
    "Ricorda le cose che ti dice avere importanza. Tornare su una preoccupazione che ha menzionato giorni fa dimostra che stavi davvero ascoltando fin dall'inizio.",
    "Restate dalla stessa parte del tavolo. Quando sorge un problema, immagina di sederti accanto al partner per affrontarlo, anziché di fronte a lui per incolparlo.",
    "Mantieni privato il vostro amore quando ha bisogno di protezione. Non ogni dettaglio appartiene ai social; una certa intimità resta più forte quando rimane tra voi.",
    "Sii generoso con i meriti e lento con le colpe. Nominare ciò che il partner ha fatto bene, e ammettere i tuoi passi falsi, impedisce al risentimento di mettere radici.",
    "Lascia che l'affetto sia incondizionato, non una ricompensa. Trattenere il calore per fare un punto insegna al partner che il tuo amore ha delle condizioni.",
    "Crescete insieme provando cose nuove fianco a fianco. La novità condivisa, da un viaggio a un nuovo corso, riaccende l'entusiasmo che il primo amore aveva naturalmente.",
    "Concludete ogni giornata con un momento di connessione. Poche parole sincere o un lungo abbraccio prima di dormire vi ricuciono insieme dopo che il giorno vi ha separati.",
  ],
  facts: [
    "Quando ti innamori, il cervello si riempie di dopamina, la stessa sostanza della ricompensa coinvolta nella motivazione e nel piacere, ed è per questo che un nuovo amore può sembrare quasi una dipendenza.",
    "L'ossitocina, spesso chiamata 'ormone del legame', aumenta durante abbracci, tenersi per mano e vicinanza, aiutando i partner a sentirsi legati e fiduciosi l'uno verso l'altro.",
    "Alcuni studi suggeriscono che guardarsi negli occhi per qualche minuto può accrescere il senso di intimità, persino tra relativi estranei.",
    "L'espressione 'cadere innamorati' può essere più letterale che poetica; il primo amore può abbassare la serotonina a livelli simili a quelli osservati nel pensiero ossessivo.",
    "I ricercatori hanno scoperto che tenere la mano di una persona amata può ridurre in modo misurabile la percezione del dolore fisico e dello stress.",
    "Il tuo battito cardiaco può davvero sincronizzarsi con quello di un partner romantico quando vi sedete vicini e vi guardate, secondo studi sulle coppie.",
    "Gli antichi Greci descrivevano vari tipi di amore, tra cui eros (passione), philia (amicizia) e agape (amore altruistico), riconoscendo l'amore come molto più di un singolo sentimento.",
    "Le arvicole della prateria sono famose nella scienza per formare legami di coppia che durano tutta la vita, e studiarle ha insegnato molto ai ricercatori sulla chimica della monogamia.",
    "La tradizione dell'anello di fidanzamento con diamante si diffuse in gran parte dopo una famosa campagna pubblicitaria del Novecento che dichiarava 'Un diamante è per sempre'.",
    "Le farfalle nello stomaco durante il primo amore sono reali; l'adrenalina dell'attrazione può deviare il sangue dall'apparato digerente, creando quella sensazione di frullo.",
    "Alcuni studi suggeriscono che le coppie che ridono insieme regolarmente tendono a riferire una maggiore soddisfazione nella relazione e a sentirsi più connesse nel tempo.",
    "La tradizione nuziale di portare l'anello all'anulare risale a un'antica credenza in una 'vena amoris', una vena che correrebbe dritta fino al cuore.",
    "L'amore romantico e l'attaccamento profondo attivano sistemi cerebrali leggermente diversi, il che aiuta a spiegare come la passione possa maturare in un legame più calmo e stabile.",
    "I cigni, spesso visti come simboli d'amore, formano frequentemente legami di coppia duraturi, restando talvolta con lo stesso compagno per molti anni.",
    "I ricercatori stimano che possano servire da pochi secondi a qualche minuto perché una persona decida se prova attrazione per qualcuno di nuovo.",
    "La 'fase della luna di miele', fatta di intensa passione iniziale, dura tipicamente tra diversi mesi e circa due anni prima di stabilizzarsi in un attaccamento più profondo.",
    "Le coccole e l'affetto fisico possono innescare il rilascio di endorfine, le sostanze naturali del benessere del corpo che aiutano anche a ridurre lo stress.",
    "In molte culture, storicamente, il matrimonio veniva combinato per motivi economici o politici, e l'idea di sposarsi soprattutto per amore è relativamente moderna.",
    "Alcuni studi suggeriscono che le persone spesso si sentono più attratte da volti grosso modo simmetrici, cosa che alcuni scienziati collegano a segnali inconsci sulla salute.",
    "La parola 'romanticismo' si riferiva in origine a uno stile di narrazione medievale, e solo in seguito arrivò a indicare l'amore appassionato che vi associamo oggi.",
    "L'olfatto ha un ruolo sorprendente nell'attrazione; la ricerca suggerisce che l'odore possa influenzare sottilmente chi troviamo attraente come potenziale partner.",
    "Le coppie di lungo corso a volte iniziano a somigliarsi leggermente, un fenomeno che i ricercatori collegano in parte a decenni di espressioni, ambiente ed emozioni condivise.",
    "L'usanza di baciarsi sotto il vischio risale a secoli fa ed era un tempo legata ad antiche tradizioni di pace, fertilità e buona volontà.",
    "Innamorarsi può ridurre temporaneamente l'attività nelle regioni cerebrali legate al giudizio critico, il che spiega in parte perché l'amore possa sembrare un po' cieco.",
    "Alcuni studi suggeriscono che il semplice aspettarsi che qualcuno sia caloroso e amichevole può portarti a comportarti in modi che lo fanno rispondere con calore a sua volta.",
    "Gli albatri eseguono elaborate danze di corteggiamento e possono mantenere la stessa unione attraverso molte stagioni riproduttive, talvolta per gran parte delle loro lunghe vite.",
    "Il cervello nel primo amore può somigliare al cervello sotto l'effetto di certe ricompense, illuminando i centri del piacere che ci spingono a cercare la vicinanza con il partner.",
    "I ricercatori hanno scoperto che le coppie che esprimono regolarmente gratitudine l'una verso l'altra tendono a sentirsi più impegnate e soddisfatte nella relazione.",
    "Il simbolo a forma di cuore che associamo all'amore non somiglia in realtà a un cuore umano; le sue origini sono dibattute e probabilmente stilizzate nel corso dei secoli.",
    "Il tatto è uno dei primi sensi a svilupparsi, e l'affetto fisico delicato resta un modo potente con cui gli esseri umani comunicano l'amore per tutta la vita.",
    "Alcuni studi suggeriscono che fare attività nuove ed eccitanti insieme può aumentare la soddisfazione di coppia ricreando un po' della novità del primo amore.",
    "Alcuni pinguini sono noti per rituali di corteggiamento che includono l'offrire un sassolino accuratamente scelto a un potenziale compagno.",
    "Si ritiene che l'ormone vasopressina, accanto all'ossitocina, svolga un ruolo importante nel legame e nell'attaccamento a lungo termine tra partner.",
    "San Valentino affonda le radici in antiche feste e nella leggenda di San Valentino, evolvendosi nei secoli nell'odierna celebrazione dell'amore romantico.",
    "La ricerca suggerisce che le persone tendono a sentirsi più vicine a coloro a cui si confidano, ed è per questo che condividere storie personali può accelerare l'intimità.",
    "L'arrossire, una risposta tipicamente umana, può segnalare attrazione e imbarazzo, e alcuni ricercatori ritengono si sia evoluto in parte come un onesto segnale sociale.",
    "L'effetto della 'mera esposizione' significa che spesso una persona ci piace di più semplicemente vedendola ripetutamente, ecco perché la vicinanza può accendere il romanticismo.",
    "Alcuni studi suggeriscono che le coppie che affrontano i conflitti con umorismo e gentilezza, anziché con disprezzo, hanno molte più probabilità di restare insieme.",
    "I cavallucci marini sono famosi per una disposizione insolita in cui è il maschio a portare e nutrire i piccoli in sviluppo.",
    "La sostanza chimica feniletilammina, talvolta soprannominata 'molecola dell'amore', viene rilasciata durante l'attrazione e si trova anche naturalmente in piccole quantità nel cioccolato.",
    "In molte culture ed epoche, i poeti hanno trattato l'amore come uno dei temi centrali dell'umanità, a suggerire che il suo richiamo emotivo è notevolmente universale.",
    "La ricerca sugli 'stili di attaccamento' suggerisce che i nostri primi legami con chi si prende cura di noi possono influenzare quanto ci sentiamo sicuri o ansiosi nelle relazioni romantiche da adulti.",
    "Alcuni studi suggeriscono che anche brevi gesti di gentilezza tra partner, come preparare il tè o un messaggio veloce, si accumulano in una benevolenza duratura nella relazione.",
    "L'usanza della torta nuziale ha radici antiche, con varie culture che storicamente usavano pane o torta nei riti matrimoniali a simboleggiare la prosperità.",
    "Alcuni scienziati credono che il potere della musica di suscitare emozioni sia strettamente legato al legame, il che potrebbe spiegare perché le canzoni d'amore si trovino in quasi ogni cultura.",
    "I ricercatori hanno osservato che le coppie appena innamorate sperimentano a volte una riduzione dell'appetito e difficoltà a dormire, in parte a causa dell'impennata di sostanze dello stress e della ricompensa.",
    "La 'danza dell'addome' delle api non è romanticismo, ma molte parate di corteggiamento animale sono esibizioni elaborate destinate ad attrarre e impressionare un compagno.",
    "Alcuni studi suggeriscono che sentirsi apprezzati è uno dei più forti predittori del fatto che le persone si sentano soddisfatte e vogliano restare in una relazione.",
    "La tradizione di portare la sposa oltre la soglia ha radici in antiche usanze un tempo ritenute capaci di proteggere la coppia dalla sfortuna.",
    "Amore e dolore possono condividere percorsi cerebrali sovrapposti, il che può aiutare a spiegare perché un cuore spezzato possa davvero far male fisicamente.",
    "I ricercatori che studiano coppie sposate da lungo tempo hanno scoperto che un piccolo numero di esse, che dice di provare ancora un amore intenso, mostra un'attività cerebrale simile a quella del primo amore.",
    "Molte specie di uccelli cantano duetti con i loro compagni, coordinando i richiami con tale precisione da sembrare un'unica voce.",
    "Alcuni studi suggeriscono che le coppie tendono a essere più felici quando mantengono un sano equilibrio tra interazioni positive e negative nella vita quotidiana.",
    "Lo scambio di anelli come simbolo di impegno è una pratica antica, presente in varie forme presso molte civiltà primitive.",
    "L'attrazione fisica può essere influenzata da qualcosa di semplice come un battito accelerato; l'eccitazione da emozione viene talvolta scambiata per attrazione romantica.",
    "Alcuni ricercatori descrivono l'amore romantico come composto da tre grandi componenti: desiderio, attrazione e attaccamento, ciascuno guidato da una diversa chimica cerebrale.",
    "I lupi formano tipicamente forti legami di coppia, e una coppia legata costituisce spesso il nucleo sociale del branco.",
    "Alcuni studi suggeriscono che i partner che sentono la propria relazione come un luogo di accettazione sono più disposti a correre sani rischi emotivi l'uno con l'altro.",
    "Il colore rosso è stato collegato in alcuni studi alle percezioni di attrazione, con persone talvolta valutate come più attraenti quando lo indossano.",
    "Nel corso della storia, le lettere d'amore sono state cimeli preziosi, ed esempi sopravvissuti di secoli fa rivelano che desiderio e devozione cambiano poco nel tempo.",
    "I ricercatori hanno scoperto che il tocco affettuoso di un partner può aiutare ad abbassare la pressione sanguigna e ad alleviare la risposta del corpo allo stress.",
    "Alcune specie di pinguini, gibboni e certe volpi sono segnalate dai biologi per la formazione di legami di coppia particolarmente forti e duraturi.",
    "L''effetto Romeo e Giulietta' descrive come l'opposizione esterna a una relazione possa talvolta intensificare, anziché indebolire, la passione di una coppia.",
    "Alcuni studi suggeriscono che il semplice pensare a una persona amata può attivare le aree della ricompensa nel cervello e offrire un cuscinetto misurabile contro lo stress.",
    "Molte culture, storicamente, scambiavano pegni di fidanzamento, da anelli a nastri a monete, molto prima che prendessero forma le moderne tradizioni di promessa.",
    "La ricerca suggerisce che le persone spesso sottovalutano quanto un complimento sincero rallegrerà la giornata del partner, lasciando troppo spesso le parole gentili non dette.",
    "I gibboni sono noti tra i primati per la formazione di legami di coppia a lungo termine e persino per cantare insieme richiami mattutini coordinati.",
    "La sensazione di 'feeling' con qualcuno può riflettere in parte quanto a proprio agio e rilassato si senta il tuo sistema nervoso in sua presenza.",
    "Alcuni studi suggeriscono che le coppie che condividono e festeggiano insieme le buone notizie, non solo si sostengono nei momenti difficili, tendono a sentirsi più connesse.",
    "I castori formano tipicamente una coppia e collaborano per costruire e mantenere le loro tane, condividendo il lavoro di crescere i piccoli.",
    "L'espressione 'legare il nodo' deriva probabilmente da antiche usanze matrimoniali di varie culture che prevedevano letteralmente di unire le mani della coppia.",
    "La ricerca sull'attrazione suggerisce che il senso dell'umorismo è uno dei tratti più comunemente apprezzati che le persone cercano in un partner a lungo termine.",
    "Alcuni scienziati credono che la tendenza umana a formare legami di coppia possa essersi evoluta in parte per sostenere il lungo compito di crescere i figli.",
    "Alcuni studi suggeriscono che le coppie che mantengono rituali condivisi, per quanto piccoli, riferiscono un più forte senso di identità e appartenenza insieme.",
    "Il mito di Cupido, la figura alata che colpisce i cuori con le frecce, proviene dalla mitologia romana e dalla più antica figura greca di Eros.",
    "I ricercatori hanno scoperto che sentirsi compresi da un partner è strettamente legato al sentirsi amati, a volte persino più dei grandi gesti romantici.",
    "Certe antilopi, gru e pappagalli sono tra i molti animali che i biologi hanno osservato mantenere legami duraturi con un unico partner.",
    "Alcuni studi suggeriscono che il modo in cui le coppie gestiscono i piccoli fastidi quotidiani predice la soddisfazione a lungo termine più affidabilmente di come affrontano le rare grandi crisi.",
    "La tradizione della 'luna di miele' dopo il matrimonio divenne popolare nell'Ottocento, anche se la parola stessa è molto più antica.",
    "La ricerca suggerisce che la vicinanza fisica durante il sonno, come la presenza ravvicinata di un partner, può migliorare sottilmente i sentimenti di sicurezza e riposo.",
    "Alcuni fiori, specialmente la rosa rossa, sono diventati simboli duraturi dell'amore attraverso secoli di poesia, arte e tradizione culturale.",
    "Alcuni studi suggeriscono che le coppie capaci di riparare in fretta dopo un conflitto, anziché evitarlo perfettamente, tendono ad avere le relazioni più solide.",
    "Il sistema della ricompensa del cervello può rispondere al sorriso di un partner in modi simili ad altre esperienze profondamente gratificanti, rafforzando il richiamo dell'amore.",
    "Molte culture hanno sviluppato tradizioni di mediazione matrimoniale, e i sensali professionisti sono esistiti in varie società per centinaia di anni.",
    "La ricerca suggerisce che esprimere affetto attraverso il 'linguaggio dell'amore' preferito dal partner tende ad arrivare in modo più potente dell'affetto secondo i propri termini.",
    "Le cicogne, spesso associate ai neonati nel folklore, sono note anche per tornare di frequente allo stesso nido e allo stesso compagno anno dopo anno.",
    "Alcuni studi suggeriscono che la nostalgia per i ricordi condivisi può rafforzare il legame di coppia ricordando loro la propria storia e la resilienza insieme.",
    "L'usanza delle damigelle d'onore potrebbe risalire ad antiche tradizioni in cui accompagnatrici vestite in modo simile si pensava confondessero gli spiriti maligni.",
    "La ricerca suggerisce che le coppie che mantengono un senso di 'noi' anziché di 'me contro te' durante i disaccordi tendono a risolverli in modo più costruttivo.",
    "Le aquile calve formano spesso legami di coppia a lungo termine e possono tornare insieme allo stesso sito di nidificazione per molti anni.",
    "Alcuni studi suggeriscono che l'attesa può intensificare la felicità, ed è per questo che attendere con ansia del tempo con il partner può essere quasi gioioso quanto il tempo stesso.",
    "La tradizione di regalare fiori come gesto romantico è documentata presso molte culture e secoli come un linguaggio dell'affetto.",
    "La ricerca suggerisce che le persone in relazioni di sostegno tendono a riprendersi da malattie e stress un po' più in fretta di chi si sente isolato.",
    "Alcune specie di pesci ciclidi sono segnalate dai biologi per la cooperazione in coppia nella custodia e nella cura delle uova e dei piccoli.",
    "Alcuni studi suggeriscono che le coppie che esprimono affetto fisico regolarmente, oltre che durante la risoluzione dei conflitti, tendono a mantenere legami emotivi più forti.",
    "La nozione di 'anima gemella' compare nella filosofia fin dall'antichità, incluso un famoso mito raccontato negli scritti di Platone.",
    "La ricerca suggerisce che il semplice avere un partner con cui confidarsi è associato a una maggiore resilienza nei momenti più stressanti della vita.",
    "I pesci angelo francesi sono tra le specie che i biologi hanno osservato viaggiare e difendere il territorio come coppie fedeli e cooperative.",
    "Alcuni studi suggeriscono che l'abitudine, propria delle prime fasi, di idealizzare un partner, entro certi limiti, può effettivamente aiutare le coppie a restare soddisfatte nel tempo.",
    "La stretta di mano e il bacio come saluti hanno entrambi radici storiche profonde, con il bacio romantico che compare presso molte culture antiche.",
    "La ricerca suggerisce che le coppie che trovano tempo per lo svago condiviso, anche brevi momenti, riferiscono di sentirsi più vicine e più come una squadra.",
    "Alcuni scienziati ritengono che l'universale capacità umana di amare possa essere uno degli strumenti più potenti dell'evoluzione per la cooperazione e la sopravvivenza.",
    "Alcuni studi suggeriscono che sentirsi sicuri in una relazione libera le persone a essere più avventurose e fiduciose nel resto della loro vita.",
    "La tradizione della poesia d'amore risale a migliaia di anni fa, con alcune delle più antiche poesie d'amore conosciute scritte su antiche tavolette d'argilla.",
    "La ricerca suggerisce che i partner si sentono spesso più amati non durante i gesti eclatanti, ma nei piccoli e costanti momenti di attenzione e cura.",
    "Certe specie di gufi formano legami di coppia duraturi e collaborano strettamente per crescere i piccoli, condividendo i compiti di caccia e nidificazione.",
    "Alcuni studi suggeriscono che le coppie che mantengono amicizie e interessi individuali, accanto alla relazione, tendono a riferire una maggiore felicità a lungo termine insieme.",
    "Il velo indossato da alcune spose ha origini antiche, comparendo in varie culture come simbolo di modestia, mistero o protezione.",
    "La ricerca suggerisce che l'esperienza dello stupore, come guardare un tramonto insieme, può approfondire il senso di connessione e di significato condiviso di una coppia.",
    "Molte culture hanno tradizioni popolari su filtri e pegni d'amore, riflettendo un desiderio umano senza tempo di attrarre e trattenere l'affetto.",
    "Alcuni studi suggeriscono che la reattività, la sensazione che il partner noti davvero i tuoi bisogni e se ne curi, è centrale per sentirsi profondamente amati.",
    "L'idea di celebrare un anniversario di matrimonio con doni specifici, come la carta o l'oro per certi anni, si è sviluppata gradualmente negli ultimi secoli.",
    "La ricerca suggerisce che persino immaginare momenti futuri con un partner può rafforzare l'impegno presente e la motivazione a coltivare la relazione.",
    "Alcuni pinguini macaroni e altri uccelli marini si riuniscono con lo stesso compagno a ogni stagione riproduttiva dopo aver trascorso mesi separati in mare.",
    "Alcuni studi suggeriscono che il semplice gesto di dire 'grazie' a un partner può innescare un ciclo positivo di apprezzamento e generosità.",
    "La parola 'coccola' può suonare moderna, ma gli esseri umani cercano il conforto del contatto fisico ravvicinato fin dai primissimi momenti della nostra specie.",
    "La ricerca suggerisce che le coppie che vedono le sfide come problemi condivisi da risolvere, anziché come fallimenti personali, tendono a uscire più forti dalle difficoltà.",
  ],
  quotes: [
    { text: "Di qualunque cosa siano fatte le nostre anime, la sua e la mia sono uguali.", author: "Emily Brontë" },
    { text: "Sai di essere innamorato quando non riesci ad addormentarti perché la realtà è finalmente migliore dei tuoi sogni.", author: "Dr. Seuss" },
    { text: "L'amore è composto da una sola anima che abita due corpi.", author: "Aristotele" },
    { text: "La cosa migliore a cui aggrapparsi nella vita è l'altro.", author: "Audrey Hepburn" },
    { text: "Siamo più vivi quando siamo innamorati.", author: "John Updike" },
    { text: "L'amore è quella condizione in cui la felicità di un'altra persona è essenziale per la propria.", author: "Robert A. Heinlein" },
    { text: "Amare ed essere amati è sentire il sole da entrambi i lati.", author: "David Viscott" },
    { text: "Non c'è rimedio all'amore se non amare di più.", author: "Henry David Thoreau" },
    { text: "L'amore non consiste nel guardarsi l'un l'altro, ma nel guardare insieme nella stessa direzione.", author: "Antoine de Saint-Exupéry" },
    { text: "Se so cos'è l'amore, è grazie a te.", author: "Hermann Hesse" },
    { text: "La più grande felicità della vita è la convinzione di essere amati.", author: "Victor Hugo" },
    { text: "L'amore è amicizia che ha preso fuoco.", author: "Ann Landers" },
    { text: "Dove c'è amore c'è vita.", author: "Mahatma Gandhi" },
    { text: "Essere profondamente amati da qualcuno ti dà forza, mentre amare qualcuno profondamente ti dà coraggio.", author: "Lao Tzu" },
    { text: "L'amore è quando la felicità dell'altra persona è più importante della tua.", author: "H. Jackson Brown Jr." },
    { text: "Il cuore ha le sue ragioni che la ragione non conosce.", author: "Blaise Pascal" },
    { text: "Un matrimonio riuscito richiede di innamorarsi molte volte, sempre della stessa persona.", author: "Mignon McLaughlin" },
    { text: "Amavamo con un amore che era più dell'amore.", author: "Edgar Allan Poe" },
    { text: "Ma le cose più belle del mondo non si possono vedere né toccare, vanno sentite con il cuore.", author: "Helen Keller" },
    { text: "L'amore non è trovare qualcuno con cui vivere. È trovare qualcuno senza cui non puoi vivere.", author: "Rafael Ortiz" },
    { text: "L'amore non riconosce barriere. Salta ostacoli, scavalca recinti, penetra muri per arrivare a destinazione pieno di speranza.", author: "Maya Angelou" },
    { text: "L'amore è un irresistibile desiderio di essere irresistibilmente desiderati.", author: "Robert Frost" },
    { text: "Non sposi qualcuno con cui puoi vivere, sposi la persona senza cui non puoi vivere.", author: "Anonimo" },
    { text: "Il corso del vero amore non è mai stato facile.", author: "William Shakespeare" },
    { text: "Ama tutti, fidati di pochi, non fare torto a nessuno.", author: "William Shakespeare" },
    { text: "L'amore non guarda con gli occhi, ma con la mente.", author: "William Shakespeare" },
    { text: "Ho trovato colui che la mia anima ama.", author: "Cantico dei Cantici" },
    { text: "L'amore è paziente, l'amore è benevolo. Non è invidioso, non si vanta, non si gonfia d'orgoglio.", author: "1 Corinzi 13:4" },
    { text: "Al tocco dell'amore ognuno diventa poeta.", author: "Platone" },
    { text: "Donare amore è di per sé un'educazione.", author: "Eleanor Roosevelt" },
    { text: "L'amore è il fiore che devi lasciar crescere.", author: "John Lennon" },
    { text: "Tutto ciò di cui hai bisogno è amore.", author: "John Lennon" },
    { text: "L'amore o c'è o non c'è. L'amore tenue non è affatto amore.", author: "Toni Morrison" },
    { text: "L'amore toglie le maschere che temiamo di non poter vivere senza e sappiamo di non poter vivere con esse.", author: "James Baldwin" },
    { text: "L'amore è un frutto di stagione in ogni momento, e alla portata di ogni mano.", author: "Madre Teresa" },
    { text: "Diffondi l'amore ovunque tu vada. Che nessuno venga mai a te senza andarsene più felice.", author: "Madre Teresa" },
    { text: "Possiamo imparare ad amare solo amando.", author: "Iris Murdoch" },
    { text: "L'amore non è qualcosa che trovi. L'amore è qualcosa che trova te.", author: "Loretta Young" },
    { text: "L'arte di amare è in gran parte l'arte della perseveranza.", author: "Albert Ellis" },
    { text: "Amare in qualsiasi modo significa essere vulnerabili.", author: "C. S. Lewis" },
    { text: "L'amore non è un sentimento affettuoso, ma un desiderio costante del bene supremo della persona amata.", author: "C. S. Lewis" },
    { text: "L'amore è il tutto. Noi siamo solo frammenti.", author: "Rumi" },
    { text: "Il tuo compito non è cercare l'amore, ma soltanto cercare e trovare tutte le barriere dentro di te che hai costruito contro di esso.", author: "Rumi" },
    { text: "Lascia che la bellezza di ciò che ami sia ciò che fai.", author: "Rumi" },
    { text: "L'amore è il ponte tra te e ogni cosa.", author: "Rumi" },
    { text: "La gravità non è responsabile delle persone che si innamorano.", author: "Albert Einstein" },
    { text: "L'amore consiste in questo: che due solitudini si proteggano, si tocchino e si salutino a vicenda.", author: "Rainer Maria Rilke" },
    { text: "Una volta che hai imparato ad amare, avrai imparato a vivere.", author: "Anonimo" },
    { text: "L'amore è composto da molte cose, ma la sua base è l'amicizia e la fiducia.", author: "Anonimo" },
    { text: "Quando ami qualcuno, ami la persona così com'è, e non come vorresti che fosse.", author: "Lev Tolstoj" },
    { text: "Scese, cercando di non guardarla a lungo, come fosse il sole, eppure la vedeva, come il sole, anche senza guardare.", author: "Lev Tolstoj" },
    { text: "Dubita che le stelle siano fuoco; dubita che il sole si muova; dubita che la verità sia menzogna; ma non dubitare mai del mio amore.", author: "William Shakespeare" },
    { text: "Come ti amo? Lascia che conti i modi.", author: "Elizabeth Barrett Browning" },
    { text: "L'amore precede la vita, segue la morte, è l'inizio della creazione e l'esponente del respiro.", author: "Emily Dickinson" },
    { text: "Che l'amore sia tutto ciò che esiste, è tutto ciò che sappiamo dell'amore.", author: "Emily Dickinson" },
    { text: "Se vivrai fino a cento anni, io voglio vivere fino a cento anni meno un giorno, così da non dover mai vivere senza di te.", author: "A. A. Milne" },
    { text: "L'amore è una tela fornita dalla natura e ricamata dall'immaginazione.", author: "Voltaire" },
    { text: "Le cose migliori e più belle di questo mondo non si possono vedere né udire, ma vanno sentite con il cuore.", author: "Helen Keller" },
    { text: "Un fiore non può sbocciare senza il sole, e l'uomo non può vivere senza amore.", author: "Max Müller" },
    { text: "L'amore è come il vento, non puoi vederlo ma puoi sentirlo.", author: "Nicholas Sparks" },
    { text: "La semplice mancanza di lei è per me più della presenza degli altri.", author: "Edward Thomas" },
    { text: "Preferirei condividere una sola vita con te che affrontare tutte le ere di questo mondo da solo.", author: "J. R. R. Tolkien" },
    { text: "L'amore è la chiave maestra che apre le porte della felicità.", author: "Oliver Wendell Holmes" },
    { text: "Siamo plasmati e modellati da ciò che amiamo.", author: "Johann Wolfgang von Goethe" },
    { text: "L'amore, e la tosse, non si possono nascondere.", author: "George Herbert" },
    { text: "Due persone amano consegnandosi a vicenda il mondo.", author: "Anonimo" },
    { text: "L'amore fa uscire l'anima dal suo nascondiglio.", author: "Zora Neale Hurston" },
    { text: "C'è sempre un po' di follia nell'amore. Ma c'è sempre anche un po' di ragione nella follia.", author: "Friedrich Nietzsche" },
    { text: "L'amore è l'unica forza capace di trasformare un nemico in un amico.", author: "Martin Luther King Jr." },
    { text: "Dobbiamo sviluppare e mantenere la capacità di perdonare.", author: "Martin Luther King Jr." },
    { text: "Il modo per amare qualcosa è rendersi conto che potrebbe andare perduta.", author: "G. K. Chesterton" },
    { text: "Amare non è mai una perdita di tempo.", author: "Astrid Alauda" },
    { text: "L'amore è la voce sotto tutti i silenzi, la speranza che non ha opposto nella paura.", author: "E. E. Cummings" },
    { text: "Porto il tuo cuore con me. Lo porto nel mio cuore.", author: "E. E. Cummings" },
    { text: "L'amore cresce donando. L'amore che doniamo è l'unico amore che conserviamo.", author: "Elbert Hubbard" },
    { text: "Amare non è nulla. Essere amati è qualcosa. Ma amare ed essere amati, questo è tutto.", author: "T. Tolis" },
    { text: "L'amore piantò una rosa, e il mondo divenne dolce.", author: "Katharine Lee Bates" },
    { text: "L'amore è l'espansione di due nature in modo tale che ciascuna include l'altra.", author: "Felix Adler" },
    { text: "Dimmi chi ami, e ti dirò chi sei.", author: "Houssaye" },
    { text: "Dove eri tu, ora c'è un buco nel mondo, attorno al quale mi ritrovo a camminare di continuo durante il giorno.", author: "Edna St. Vincent Millay" },
  ],
};
