import type { RotationalContent } from '@/lib/dailyContentTypes';

export const pt: RotationalContent = {
  tips: [
    "Escute para entender, não para responder. Fazer uma pausa antes de responder mostra ao seu parceiro que as palavras dele realmente foram ouvidas, e esse pequeno hábito aprofunda a confiança com o tempo.",
    "Agradeça pelas coisas comuns. Reparar no café feito ou na louça lavada lembra ao seu parceiro que o esforço dele no dia a dia nunca passa despercebido.",
    "Quando o conflito surge, ataquem o problema juntos, e não um ao outro. Vocês são uma equipe enfrentando uma questão, não adversários tentando vencer uma disputa.",
    "Reserve um tempo tranquilo juntos, mesmo que sejam só vinte minutos. A conexão raramente acontece nas brechas; ela cresce quando você abre espaço de propósito para ela.",
    "Pergunte ao seu parceiro como ele prefere ser confortado. Alguns querem soluções, outros querem um abraço e silêncio, e errar nessa hora pode parecer distância.",
    "Reconcilie-se logo após um desentendimento. Uma conversa sincera quando os ânimos esfriam vale muito mais do que fingir que o atrito nunca aconteceu.",
    "A curiosidade mantém o amor vivo. Continue fazendo novas perguntas ao seu parceiro de longa data, porque as pessoas mudam silenciosamente e as mais interessantes ainda estão se revelando.",
    "Expresse o seu apreço em voz alta, não apenas na sua cabeça. A gratidão não dita aquece só você, enquanto a gratidão dita aquece a pessoa que você ama.",
    "Proteja o seu relacionamento do desprezo. Revirar os olhos e o sarcasmo corroem a conexão mais rápido do que quase qualquer coisa, então escolha o respeito mesmo quando estiver frustrado.",
    "Faça com que os convites de conexão importem. Quando o seu parceiro compartilha algo pequeno, voltar-se para ele com atenção é a cola silenciosa de um amor duradouro.",
    "Peça desculpas sem acrescentar um 'mas'. Um pedido de desculpas limpo assume a sua parte por inteiro, enquanto um pedido condicionado devolve a culpa discretamente para o outro lado da mesa.",
    "Mantenha alguns rituais que são só de vocês. Uma caminhada de domingo ou um café compartilhado pela manhã cria um ritmo constante que ancora as vidas corridas de vocês.",
    "Presuma boa intenção antes de presumir o pior. A maioria dos momentos magoados vem de descuido ou estresse, não de um parceiro secretamente desejando o seu mal.",
    "Falem sobre dinheiro cedo e com frequência. Alinhar gastos, economias e objetivos evita o ressentimento silencioso que as finanças podem criar discretamente.",
    "Deixe o seu parceiro ser diferente de você. Compatibilidade não é igualdade; são duas pessoas distintas escolhendo honrar o mundo interior separado uma da outra.",
    "Repare no que o seu parceiro está carregando. Um gentil 'você parece cansado, deixa que eu cuido do jantar' pode dizer eu te amo mais alto do que palavras.",
    "Mantenha alguma independência dentro da união. Cultivar os seus próprios amigos e paixões faz de você um parceiro mais interessante e cheio de energia para se voltar.",
    "Elogie em público, resolva os problemas em particular. Valorizar o seu parceiro diante dos outros e lidar com o atrito de forma reservada protege tanto o orgulho quanto a confiança.",
    "Troque 'você sempre' e 'você nunca' por 'eu sinto'. Falar a partir da sua experiência convida ao entendimento, enquanto acusações generalizadas convidam à defensiva.",
    "O toque importa mesmo quando nada está errado. Uma mão no ombro ou um abraço rápido mantém o corpo lembrando que é amado.",
    "Escolha o seu parceiro de novo nos dias difíceis. O amor não é só a faísca em que você caiu, mas a decisão que você renova quando as coisas ficam pesadas.",
    "Interesse-se pelo mundo dele. Fazer perguntas verdadeiras sobre o trabalho, as preocupações e os sonhos do seu parceiro diz a ele que a vida dele realmente importa para você.",
    "Não fique contando pontos. A generosidade dada para ser retribuída é uma transação; o amor prospera quando você dá livremente e confia que o equilíbrio se acerta.",
    "Nomeie as suas necessidades com clareza. O seu parceiro não consegue ler a sua mente, e esperar em silêncio que ele adivinhe costuma terminar em decepção para os dois.",
    "Riam juntos com frequência. O humor compartilhado reduz a tensão, constrói intimidade e lembra você de que a pessoa ao seu lado também é a sua companhia favorita.",
    "Esteja totalmente presente nos reencontros. Receber o seu parceiro com carinho quando vocês se reencontram, com o celular guardado e o olhar atento, dá o tom da noite.",
    "Perdoe as pequenas coisas rápido. Guardar mágoas pequenas constrói um muro tijolo por tijolo até que vocês não consigam mais se alcançar.",
    "Comemore as vitórias do seu parceiro como se fossem suas. A alegria genuína pelo sucesso dele, sem inveja, é uma das formas mais profundas de amor.",
    "Verifique antes de supor que vocês se afastaram. Um simples 'como temos andado ultimamente?' muitas vezes revela uma conexão que a distância só parecia ameaçar.",
    "Respeitem os limites um do outro sem levar para o lado pessoal. Um limite é uma informação sobre as necessidades do seu parceiro, não uma rejeição a você.",
    "Faça tentativas de reconciliação durante as discussões, como um tom mais suave ou uma pequena piada. Aceitar esses ramos de oliveira oferecidos evita que os desentendimentos saiam do controle.",
    "Apareça para a logística chata. Dividir tarefas, compromissos e o planejamento de forma justa é uma das linguagens do amor mais subestimadas que existem.",
    "Seja honesto nas pequenas coisas. A confiança é construída em pequenos momentos de verdade, e mentirinhas ensinam discretamente o parceiro a duvidar de você.",
    "Pergunte 'do que você precisa de mim agora?'. Essa única pergunta corta as suposições e dá ao seu parceiro exatamente o apoio que ele deseja.",
    "Continue flertando com o seu parceiro de longa data. Uma piscadela, um elogio, um beijo roubado lembra a ele que ainda é desejado, e não apenas confiável.",
    "Deixe que ele tenha um dia ruim. Você não precisa consertar todo humor; às vezes a coisa mais gentil é simplesmente ficar por perto enquanto ele passa.",
    "Falem sobre o relacionamento quando as coisas estão bem, não só quando estão quebradas. As conversas de manutenção previnem as conversas de crise maiores.",
    "Honre o relacionamento diante dos outros. Falar com carinho sobre o seu parceiro quando ele não está por perto protege a relação da corrosão externa.",
    "Repare no seu próprio papel nas brigas que se repetem. Perguntar 'qual é a minha parte aqui?' transforma um impasse em uma chance de crescerem juntos.",
    "Tomem decisões um com o outro, não um pelo outro. Mesmo pequenas consultas comunicam respeito e lembram ao seu parceiro que vocês são realmente uma equipe.",
    "Acalme-se antes de conversas importantes. Encarar uma conversa difícil tranquilo, em vez de transbordando, ajuda você a dizer o que sente em vez do que fere.",
    "Acolha o crescimento do seu parceiro mesmo quando for inconveniente. Amar alguém significa torcer pela pessoa que ele está se tornando, não só por quem você conheceu.",
    "Surpreenda-o com esforço, não apenas com presentes. Planejar uma noite especial ou aprender a receita favorita dele mostra um amor que o dinheiro não compra.",
    "Seja o lugar seguro onde ele pode respirar fundo. Quando a casa é o único lugar em que ele pode relaxar de verdade, o relacionamento se torna o refúgio dele.",
    "Pergunte sobre os altos e baixos do dia dele. Esse simples ritual cria uma janela diária para o clima emocional interior do seu parceiro.",
    "Valide os sentimentos mesmo quando você discorda da lógica. 'Faz sentido você se sentir assim' acalma tempestades muito melhor do que corrigir fatos.",
    "Faça promessas pequenas o suficiente para cumprir. A confiabilidade construída sobre compromissos modestos e honrados conquista mais confiança do que grandes juras que você luta para cumprir.",
    "Assuma a responsabilidade pela sua própria felicidade. Um parceiro pode enriquecer a sua alegria, mas esperar que ele seja a única fonte dela é um fardo pesado.",
    "Revisitem os sonhos que vocês compartilham de vez em quando. Falar sobre o futuro que estão construindo mantém o atrito do dia a dia em perspectiva e a motivação viva.",
    "Mantenham contato nos longos dias separados. Uma mensagem rápida no meio do dia dizendo que você está pensando nele evita que o fio da conexão fique frouxo.",
    "Abra mão de ter razão para manter a conexão. Vencer uma discussão e perder o carinho do seu parceiro raramente é uma vitória que valha a pena reivindicar.",
    "Reparem nas linguagens do amor que cada um de vocês fala. Se você dá palavras, mas ele anseia por tempo, o seu esforço pode estar passando por pouco.",
    "Crie uma zona livre de celular no jantar. Refeições sem distrações são uma chance diária de realmente ver e ouvir a pessoa sentada à sua frente.",
    "Seja gentil com as inseguranças do seu parceiro. Os lugares onde ele se sente frágil merecem o seu cuidado, não a sua zombaria, mesmo em momentos de brincadeira.",
    "Abra espaço tanto para o 'meu tempo' quanto para o 'nosso tempo'. Honrar a solidão e a união evita que o relacionamento pareça uma prisão ou uma distância.",
    "Expresse desejo e admiração abertamente. Dizer ao seu parceiro especificamente o que você acha atraente nele raramente perde a graça e nunca passa despercebido.",
    "Resolva o ressentimento enquanto ele é pequeno. Nomear uma frustração menor com gentileza evita que ela endureça silenciosamente em um rancor que você não consegue explicar depois.",
    "Demonstre interesse pelos amigos e pela família dele. Acolher as pessoas que o seu parceiro ama sinaliza que você está investido na vida inteira dele, não só nele.",
    "Diminua o ritmo quando perceber uma desconexão. Em vez de se afastar mais, aproxime-se com gentileza e pergunte o que tem ocupado a mente do seu parceiro.",
    "Guarde bem os segredos e as histórias do seu parceiro. Ser alguém em quem ele pode confiar plenamente é a base da verdadeira intimidade emocional.",
    "No começo do namoro, observe como ele trata as pessoas que não podem fazer nada por ele. A gentileza com garçons e estranhos revela o caráter de verdade.",
    "Não tenha pressa de definir tudo. Deixar a conexão inicial respirar permite que você veja quem alguém realmente é antes que os rótulos criem pressão ou suposições.",
    "Acompanhe o ritmo dele sem se perder. Um amor novo e saudável equilibra entusiasmo com paciência, deixando a confiança crescer naturalmente em vez de forçar intensidade.",
    "Procure alguém cujos dias comuns sejam bons, não apenas os empolgantes. A compatibilidade do dia a dia dura mais do que a química dramática, sempre.",
    "Preste atenção em como um par lida com a decepção. A forma como alguém reage a uma pequena frustração antecipa como lidará com as maiores.",
    "No amor à distância, protejam um senso compartilhado de vida normal. Assistir a uma série juntos ou resolver tarefas por vídeo mantém a proximidade viva.",
    "Planeje a próxima visita antes da despedida atual. Ter uma data no calendário dá aos casais à distância algo concreto para se apoiar.",
    "Comunique-se com generosidade através da distância. A distância torna as suposições perigosas, então compartilhe contexto e tranquilização em excesso, em vez de deixar o silêncio ser mal interpretado.",
    "A confiança é a moeda da distância. Sem a proximidade diária, escolher acreditar no melhor um do outro se torna a espinha dorsal do relacionamento.",
    "Pratique o amor-próprio para que você traga plenitude, e não carência. Gostar da própria companhia faz de você um parceiro que escolhe o amor, em vez de se agarrar a ele.",
    "Fale consigo mesmo do jeito que você falaria com a pessoa amada. O diálogo interno duro vaza para os relacionamentos, enquanto a autocompaixão deixa o carinho fluir para fora.",
    "Cure as suas próprias feridas antigas em vez de pedir que um parceiro faça isso. Um relacionamento amoroso pode apoiar o seu crescimento, mas não pode substituir o seu próprio trabalho.",
    "Conheça o seu valor antes de negociar o amor. Pessoas que entendem o próprio valor raramente se contentam em ser uma lembrança tardia ou o plano reserva de alguém.",
    "Sente-se com as emoções desconfortáveis em vez de despejá-las. Nomear o que você sente antes de reagir evita que o seu parceiro absorva as suas tempestades não processadas.",
    "Desenvolva a habilidade de se manter equilibrado sob estresse. A sua presença calma durante os momentos difíceis do seu parceiro é um tipo de amor silencioso e poderoso.",
    "Leia a emoção por trás das palavras. Quando o seu parceiro reclama da louça, a mensagem real muitas vezes é 'eu me sinto sem apoio', e isso merece a sua atenção.",
    "Lidere com empatia quando o seu parceiro estiver chateado, mesmo com você. Defender-se pode esperar; sentir-se compreendido é o que realmente acalma o momento.",
    "Construam juntos um vocabulário emocional. Casais que conseguem nomear sentimentos com precisão tendem a resolver conflitos mais rápido do que aqueles presos no 'tudo bem' e no 'irritado'.",
    "Deixe a proximidade física ser uma conversa por si só. Abraçar um ao outro sem uma agenda pode comunicar uma segurança que as palavras às vezes têm dificuldade de alcançar.",
    "Mantenham a intimidade variada e sem pressa. A conexão se aprofunda quando vocês tratam a proximidade física como exploração e brincadeira, e não como rotina ou obrigação.",
    "Conversem abertamente sobre o que cada um gosta. Uma conversa confortável e honesta sobre intimidade constrói confiança e impede que o desejo se perca em suposições.",
    "Seja primeiro o amigo do seu parceiro. Os casais que duram tendem a gostar genuinamente um do outro, aproveitando a conversa muito depois que as faíscas iniciais se acalmam.",
    "Faça pequenos atos de serviço sem que peçam. Encher o tanque do carro dele ou carregar o celular dele diz silenciosamente 'estou pensando em você' o dia todo.",
    "Façam concessões trocando prioridades, não dividindo tudo ao meio. Ceder por completo onde importa menos para você conquista boa vontade onde importa mais.",
    "Encontre o ganha-ganha antes de se contentar com a troca. Muitos conflitos amenizam quando vocês perguntam o que deixaria os dois genuinamente satisfeitos.",
    "Mantenha os limites com calor, não com frieza. Você pode dizer não com clareza e ainda assim deixar o seu parceiro se sentir amado e respeitado o tempo todo.",
    "Não puna a vulnerabilidade. Quando o seu parceiro se abre sobre um medo ou um erro, recebê-lo com ternura garante que ele vai confiar em você de novo.",
    "Construam uma cultura de apreço, atentos ao que está certo. Casais que ativamente reparam no que há de bom um no outro relatam uma felicidade muito mais duradoura.",
    "Faça o seu parceiro se sentir escolhido, e não apenas tolerado. Lembrá-lo, em palavras e atitudes, de que você o escolheria de novo mantém o amor vivo.",
    "Dê ao seu parceiro o benefício da dúvida em voz alta. Dizer 'tenho certeza de que você não quis dizer dessa forma' dissolve a tensão antes que ela aumente.",
    "Trate as irritações do seu parceiro como dados, não como ataques. O que o incomoda muitas vezes aponta para uma necessidade não atendida que vale a pena entender em vez de descartar.",
    "Mantenha a curiosidade maior do que o julgamento. Quando algo no seu parceiro o intriga, pergunte com interesse em vez de concluir com crítica.",
    "Comemorem aniversários de pequenas coisas, como a primeira conversa de vocês. Honrar a história compartilhada lembra os dois de quanto já caminharam juntos.",
    "Deixe o seu parceiro influenciar você. Os casais prosperam quando cada um genuinamente leva em conta as opiniões e preferências do outro ao tomar decisões.",
    "Cuide da amizade dentro do seu romance. Piadas internas, conversa fácil e companheirismo simples são o que carregam o amor através das estações sem glamour.",
    "Seja rápido para confortar e lento para criticar. A proporção de carinho e queixa que você oferece define se a casa parece um refúgio ou um julgamento.",
    "Peça o que você quer de forma direta e gentil. Ficar dando indiretas gera frustração, enquanto um pedido claro e suave dá ao seu parceiro uma chance real de atender.",
    "Mantenha-se aberto a aprender como amar essa pessoa específica. O que funcionou em relacionamentos passados pode não servir; deixe o seu parceiro mostrar do que ele precisa.",
    "Reconheça o esforço mesmo quando os resultados ficam aquém. Reconhecer que o seu parceiro tentou o incentiva a continuar tentando em vez de desistir em silêncio.",
    "Mantenha contato visual quando importa. Olhar para o seu parceiro enquanto ele compartilha algo importante diz a ele que tem o seu coração inteiro, não metade.",
    "Não deixe o relacionamento no piloto automático. O amor de longo prazo precisa de atenção intencional, ou a rotina aos poucos substitui a conexão que um dia pareceu natural.",
    "Esteja disposto a ser o primeiro a ceder. Alguém tem que baixar a espada primeiro, e escolher ser essa pessoa é uma força, não uma perda.",
    "Trate os hobbies do seu parceiro com respeito mesmo que você não os compartilhe. Honrar o que o ilumina mostra que você valoriza o ser inteiro dele.",
    "Construa confiança sendo consistente. Fazer o que você diz, repetidas vezes, ensina ao seu parceiro que ele finalmente pode baixar a guarda.",
    "Ofereça tranquilização antes que ela seja pedida. Oferecer conforto quando você percebe a preocupação do seu parceiro mostra uma atenção que só palavras de amor não conseguem.",
    "Discordem sem fazer disso um plebiscito sobre o relacionamento. Nem todo conflito significa que algo está errado; às vezes significa apenas que vocês são duas pessoas.",
    "Continue saindo com o seu parceiro. Planejar momentos intencionais para se arrumar, sair e focar um no outro impede que o romance se desvaneça discretamente em logística.",
    "Acolha o retorno sobre como você ama. Perguntar 'há algo que você gostaria que eu fizesse de outro jeito?' mostra humildade e um desejo real de crescer.",
    "Deixe as pequenas gentilezas se acumularem. Um relacionamento é construído menos por grandes gestos do que por mil escolhas minúsculas de ser atencioso e caloroso.",
    "Abra espaço para o luto e o estresse do seu parceiro sem correr para consertar. Às vezes a presença, e não o conselho, é o amor de que ele realmente precisa.",
    "Seja transparente sobre o seu celular e os seus planos. A abertura onde outros poderiam esconder cria uma base de confiança que faz todo o resto parecer seguro.",
    "Escolha a curiosidade em vez do ciúme. Quando a insegurança se acende, explore o medo dentro de você em vez de projetar suspeita sobre um parceiro que não fez nada de errado.",
    "Faça do 'a gente resolve isso juntos' o seu padrão. Encarar a incerteza como uma frente unida transforma desconhecidos assustadores em aventuras compartilhadas que vocês conseguem encarar.",
    "Elogie quem ele é, não apenas o que ele faz. Dizer ao seu parceiro que você admira a gentileza ou a coragem dele o nutre mais profundamente do que elogiar tarefas.",
    "Proteja os momentos de transição, como os primeiros minutos em casa. Cumprimentar um ao outro com carinho em vez de reclamações define o tom emocional das horas seguintes.",
    "Lembre-se das coisas que ele diz que importam. Voltar a falar sobre uma preocupação que ele mencionou dias atrás prova que você estava realmente escutando o tempo todo.",
    "Fiquem do mesmo lado da mesa. Quando um problema surge, imagine sentar-se ao lado do seu parceiro encarando-o, em vez de ficar à frente dele culpando.",
    "Mantenha o seu amor reservado quando ele precisar de proteção. Nem todo detalhe pertence às redes sociais; certa intimidade fica mais forte quando permanece entre vocês.",
    "Seja generoso com o crédito e lento com a culpa. Nomear o que o seu parceiro fez certo e assumir os seus próprios deslizes impede que o ressentimento crie raízes.",
    "Deixe o afeto ser incondicional, não uma recompensa. Negar o carinho para provar um ponto ensina ao seu parceiro que o seu amor vem com condições atreladas.",
    "Cresçam juntos experimentando coisas novas lado a lado. A novidade compartilhada, de uma viagem a um curso novo, reacende a empolgação que o amor inicial tinha naturalmente.",
    "Termine cada dia com um momento de conexão. Algumas palavras honestas ou um abraço longo antes de dormir costuram vocês de volta depois que o dia os puxou para longe.",
  ],
  facts: [
    "Quando você se apaixona, o seu cérebro se inunda de dopamina, a mesma substância de recompensa envolvida na motivação e no prazer, e é por isso que um romance novo pode parecer quase viciante.",
    "A ocitocina, frequentemente chamada de 'hormônio do vínculo', dispara durante abraços, mãos dadas e proximidade, ajudando os parceiros a se sentirem ligados e a confiar um no outro.",
    "Estudos sugerem que olhar nos olhos um do outro por alguns minutos pode aumentar os sentimentos de intimidade, mesmo entre relativos desconhecidos.",
    "A expressão 'cair de amores' pode ser mais literal do que poética; o romance inicial pode reduzir a serotonina a níveis parecidos com os observados no pensamento obsessivo.",
    "Pesquisadores descobriram que segurar a mão de uma pessoa amada pode reduzir de forma mensurável a percepção de dor física e estresse.",
    "O seu batimento cardíaco pode de fato se sincronizar com o de um parceiro romântico quando vocês se sentam perto e se olham, segundo estudos com casais.",
    "Os antigos gregos descreviam vários tipos de amor, incluindo eros (paixão), philia (amizade) e agape (amor altruísta), reconhecendo o amor como muito mais do que um único sentimento.",
    "Os ratos-do-campo da pradaria são famosos na ciência por formarem vínculos de casal para a vida toda, e estudá-los ensinou muito aos pesquisadores sobre a química da monogamia.",
    "A tradição do anel de noivado de diamante se tornou difundida em grande parte após uma famosa campanha publicitária do século XX que declarou 'Um diamante é para sempre'.",
    "As borboletas no estômago durante o amor inicial são reais; a adrenalina da atração pode desviar sangue do sistema digestivo, criando aquela sensação de frio na barriga.",
    "Estudos sugerem que casais que riem juntos com frequência tendem a relatar maior satisfação no relacionamento e a se sentir mais conectados ao longo do tempo.",
    "A tradição de usar a aliança no dedo anelar remonta a uma antiga crença em uma 'vena amoris', uma veia que correria direto até o coração.",
    "O amor romântico e o apego profundo ativam sistemas cerebrais ligeiramente diferentes, o que ajuda a explicar como a paixão pode amadurecer em um vínculo mais calmo e estável.",
    "Os cisnes, muitas vezes vistos como símbolos do amor, frequentemente formam vínculos de casal duradouros, às vezes permanecendo com o mesmo parceiro por muitos anos.",
    "Pesquisadores estimam que pode levar de alguns segundos a alguns minutos para alguém decidir se sente atração por uma pessoa nova.",
    "A 'fase da lua de mel' de paixão intensa do início costuma durar algo entre vários meses e cerca de dois anos antes de se acomodar em um apego mais profundo.",
    "Os carinhos e o afeto físico podem desencadear a liberação de endorfinas, as substâncias naturais do bem-estar do corpo, que também ajudam a reduzir o estresse.",
    "Em muitas culturas, historicamente, o casamento era arranjado por razões econômicas ou políticas, e a ideia de casar principalmente por amor é relativamente moderna.",
    "Estudos sugerem que as pessoas costumam se sentir mais atraídas por rostos que são mais ou menos simétricos, algo que alguns cientistas associam a sinais inconscientes sobre saúde.",
    "A palavra 'romance' se referia originalmente a um estilo de narrativa medieval, passando só mais tarde a significar o amor apaixonado que associamos a ela hoje.",
    "O olfato desempenha um papel surpreendente na atração; pesquisas sugerem que o cheiro pode influenciar sutilmente quem achamos atraente como possível parceiro.",
    "Casais de longa data às vezes começam a se parecer ligeiramente, um fenômeno que os pesquisadores associam em parte a décadas de expressões, ambiente e emoções compartilhados.",
    "O costume de se beijar embaixo do visco remonta a séculos e já esteve ligado a antigas tradições de paz, fertilidade e boa vontade.",
    "Apaixonar-se pode reduzir temporariamente a atividade em regiões cerebrais ligadas ao juízo crítico, o que faz parte do motivo pelo qual o amor pode parecer um pouco cego.",
    "Estudos sugerem que simplesmente esperar que alguém seja caloroso e amigável pode levar você a agir de formas que fazem essa pessoa responder com calor em troca.",
    "Os albatrozes realizam danças de corte elaboradas e podem manter a mesma parceria por muitas épocas de reprodução, às vezes por grande parte de suas longas vidas.",
    "O cérebro no amor inicial pode se assemelhar ao cérebro diante de certas recompensas, acendendo os centros de recompensa que nos impulsionam a buscar proximidade com o parceiro.",
    "Pesquisadores descobriram que casais que expressam gratidão um ao outro regularmente tendem a se sentir mais comprometidos e satisfeitos em seu relacionamento.",
    "O símbolo em formato de coração que associamos ao amor não se parece de fato com um coração humano; suas origens são debatidas e provavelmente foram estilizadas ao longo dos séculos.",
    "O tato é um dos primeiros sentidos a se desenvolver, e o afeto físico gentil continua sendo uma forma poderosa de os humanos comunicarem amor ao longo da vida.",
    "Estudos sugerem que fazer atividades novas e empolgantes juntos pode aumentar a satisfação no relacionamento ao recriar parte da novidade do romance inicial.",
    "Alguns pinguins são conhecidos por rituais de corte que incluem oferecer uma pedrinha cuidadosamente escolhida a um possível parceiro.",
    "Acredita-se que o hormônio vasopressina, ao lado da ocitocina, desempenhe um papel importante no vínculo e no apego de longo prazo entre parceiros.",
    "O Dia dos Namorados tem raízes em antigos festivais e na lenda de São Valentim, evoluindo ao longo dos séculos até a celebração do amor romântico de hoje.",
    "Pesquisas sugerem que as pessoas tendem a se sentir mais próximas daquelas para quem se abrem, e é por isso que compartilhar histórias pessoais pode acelerar a intimidade.",
    "O rubor, uma resposta unicamente humana, pode sinalizar atração e constrangimento, e alguns pesquisadores acreditam que ele evoluiu em parte como um sinal social honesto.",
    "O 'efeito da mera exposição' significa que muitas vezes passamos a gostar mais das pessoas simplesmente por vê-las repetidamente, e é por isso que a proximidade pode acender o romance.",
    "Estudos sugerem que casais que enfrentam o conflito com humor e gentileza, em vez de desprezo, têm muito mais probabilidade de permanecer juntos.",
    "Os cavalos-marinhos são famosos por um arranjo incomum em que o macho carrega e nutre os filhotes em desenvolvimento.",
    "A substância feniletilamina, às vezes apelidada de 'molécula do amor', é liberada durante a atração e também é encontrada naturalmente em pequenas quantidades no chocolate.",
    "Em muitas culturas e épocas, os poetas trataram o amor como um dos temas centrais da humanidade, sugerindo que sua força emocional é notavelmente universal.",
    "Pesquisas sobre 'estilos de apego' sugerem que nossos vínculos iniciais com os cuidadores podem influenciar quão seguros ou ansiosos nos sentimos em relacionamentos adultos.",
    "Estudos sugerem que mesmo pequenos atos de gentileza entre parceiros, como fazer um chá ou mandar uma mensagem rápida, se acumulam em uma boa vontade duradoura no relacionamento.",
    "O costume do bolo de casamento tem raízes antigas, com diversas culturas usando historicamente pão ou bolo em rituais de casamento que simbolizavam prosperidade.",
    "Alguns cientistas acreditam que o poder da música de mexer com as emoções está intimamente ligado ao vínculo, o que pode explicar por que canções de amor existem em quase toda cultura.",
    "Pesquisadores observaram que casais recém-apaixonados às vezes têm o apetite reduzido e dificuldade para dormir, em parte devido às substâncias de estresse e recompensa em alta.",
    "A 'dança do requebrado' das abelhas não é romance, mas muitas exibições de corte animais são performances elaboradas feitas para atrair e impressionar um parceiro.",
    "Estudos sugerem que sentir-se valorizado é um dos mais fortes indicadores de se as pessoas se sentem satisfeitas e querem permanecer em um relacionamento.",
    "A tradição de carregar a noiva sobre a soleira da porta tem raízes em costumes antigos que se acreditava proteger o casal do azar.",
    "O amor e a dor podem compartilhar vias cerebrais sobrepostas, o que pode ajudar a explicar por que um coração partido pode realmente parecer fisicamente doloroso.",
    "Pesquisadores que estudam casais casados há muito tempo descobriram que um pequeno número, que relata ainda sentir um amor intenso, mostra atividade cerebral parecida com a do romance inicial.",
    "Muitas espécies de aves cantam duetos com seus parceiros, com os pares coordenando suas chamadas de forma tão precisa que pode soar como uma única voz.",
    "Estudos sugerem que os casais tendem a ser mais felizes quando mantêm um equilíbrio saudável entre interações positivas e negativas no dia a dia.",
    "A troca de anéis como símbolo de compromisso é uma prática antiga, que aparece em várias formas em muitas civilizações primitivas.",
    "A atração física pode ser influenciada por algo tão simples quanto um coração acelerado; a excitação da empolgação às vezes é confundida com atração romântica.",
    "Alguns pesquisadores descrevem o amor romântico como tendo três componentes amplos: desejo, atração e apego, cada um movido por uma química cerebral diferente.",
    "Os lobos normalmente formam vínculos de casal fortes, e um par ligado muitas vezes forma o núcleo social de sua matilha.",
    "Estudos sugerem que parceiros que sentem que o relacionamento é um lugar de aceitação ficam mais dispostos a assumir riscos emocionais saudáveis um com o outro.",
    "A cor vermelha foi associada em alguns estudos à percepção de atração, com as pessoas às vezes avaliando outras como mais atraentes quando vestidas dela.",
    "Ao longo da história, as cartas de amor foram lembranças preciosas, e exemplos sobreviventes de séculos atrás revelam que a saudade e a devoção mudam pouco com o tempo.",
    "Pesquisadores descobriram que o toque acolhedor de um parceiro pode ajudar a baixar a pressão arterial e a aliviar a resposta do corpo ao estresse.",
    "Algumas espécies de pinguins, gibões e certas raposas são notadas pelos biólogos por formarem vínculos de casal notavelmente fortes e duradouros.",
    "O 'efeito Romeu e Julieta' descreve como a oposição externa a um relacionamento às vezes pode intensificar, em vez de enfraquecer, a paixão de um casal.",
    "Estudos sugerem que simplesmente pensar em uma pessoa amada pode ativar áreas de recompensa do cérebro e oferecer um amortecedor mensurável contra o estresse.",
    "Muitas culturas historicamente trocavam fichas de noivado, de anéis a fitas e moedas, muito antes de as tradições modernas de noivado tomarem forma.",
    "Pesquisas sugerem que as pessoas muitas vezes subestimam o quanto um elogio sincero vai alegrar o dia de seu parceiro, deixando palavras gentis não ditas com frequência demais.",
    "Os gibões são conhecidos entre os primatas por formarem vínculos de casal de longo prazo e até por cantarem chamadas matinais coordenadas juntos.",
    "A sensação de 'química' com alguém pode refletir em parte o quão confortável e à vontade o seu sistema nervoso se sente na presença dessa pessoa.",
    "Estudos sugerem que casais que compartilham e comemoram boas notícias juntos, e não apenas se apoiam em momentos difíceis, tendem a se sentir mais conectados.",
    "Os castores normalmente formam pares e trabalham juntos para construir e manter suas tocas, dividindo o trabalho de criar os filhotes.",
    "A expressão 'dar o nó' provavelmente vem de antigos costumes de casamento em diversas culturas que literalmente envolviam amarrar as mãos do casal.",
    "Pesquisas sobre atração sugerem que o senso de humor é um dos traços mais comumente valorizados que as pessoas buscam em um parceiro de longo prazo.",
    "Alguns cientistas acreditam que a tendência humana de formar vínculos de casal pode ter evoluído em parte para apoiar a longa tarefa de criar os filhos.",
    "Estudos sugerem que casais que mantêm rituais compartilhados, por menores que sejam, relatam um senso mais forte de identidade e de pertencimento juntos.",
    "O mito de Cupido, a figura alada que atinge corações com flechas, vem da mitologia romana e da mais antiga figura grega de Eros.",
    "Pesquisadores descobriram que sentir-se compreendido por um parceiro está intimamente ligado a sentir-se amado, às vezes até mais do que grandes gestos românticos.",
    "Certos antílopes, grous e papagaios estão entre os muitos animais que os biólogos observaram manterem vínculos duradouros com um único parceiro.",
    "Estudos sugerem que a forma como os casais lidam com pequenos aborrecimentos do dia a dia prevê a satisfação de longo prazo de modo mais confiável do que como lidam com raras grandes crises.",
    "A tradição de uma viagem de 'lua de mel' após o casamento se popularizou no século XIX, embora a própria palavra seja bem mais antiga.",
    "Pesquisas sugerem que a proximidade física durante o sono, como a presença próxima de um parceiro, pode melhorar sutilmente as sensações de segurança e descanso.",
    "Algumas flores, especialmente a rosa vermelha, se tornaram símbolos duradouros do amor ao longo de séculos de poesia, arte e tradição cultural.",
    "Estudos sugerem que casais que conseguem se reconciliar rapidamente após um conflito, em vez de evitá-lo perfeitamente, tendem a ter os relacionamentos mais fortes.",
    "O sistema de recompensa do cérebro pode responder ao sorriso de um parceiro de formas parecidas com outras experiências profundamente gratificantes, reforçando a força do amor.",
    "Muitas culturas desenvolveram tradições de arranjar casamentos, e casamenteiros profissionais existem em várias sociedades há centenas de anos.",
    "Pesquisas sugerem que expressar afeto pela 'linguagem do amor' preferida do seu parceiro tende a chegar com mais força do que o afeto nos seus próprios termos.",
    "As cegonhas, frequentemente associadas a bebês no folclore, também são conhecidas por voltarem com frequência ao mesmo ninho e parceiro ano após ano.",
    "Estudos sugerem que a nostalgia por memórias compartilhadas pode fortalecer o vínculo de um casal ao lembrá-los de sua história e de sua resiliência juntos.",
    "O costume das damas de honra pode remontar a antigas tradições nas quais acompanhantes vestidas de forma parecida eram pensadas para confundir os espíritos malignos.",
    "Pesquisas sugerem que casais que mantêm um senso de 'nós' em vez de 'eu contra você' durante os desentendimentos tendem a resolvê-los de forma mais construtiva.",
    "As águias-de-cabeça-branca muitas vezes formam vínculos de casal de longo prazo e podem voltar juntas ao mesmo local de nidificação ao longo de muitos anos.",
    "Estudos sugerem que a expectativa pode intensificar a felicidade, e é por isso que aguardar ansiosamente um tempo com um parceiro pode ser quase tão alegre quanto o tempo em si.",
    "A tradição de presentear com flores como gesto romântico foi documentada em muitas culturas e séculos como uma linguagem de afeto.",
    "Pesquisas sugerem que pessoas em relacionamentos acolhedores tendem a se recuperar de doenças e do estresse um pouco mais rápido do que aquelas que se sentem isoladas.",
    "Algumas espécies de peixe ciclídeo são notadas pelos biólogos por cooperarem em pares para guardar e cuidar de seus ovos e filhotes.",
    "Estudos sugerem que casais que demonstram afeto físico regularmente, além de durante a resolução de conflitos, tendem a manter vínculos emocionais mais fortes.",
    "A noção de uma 'alma gêmea' aparece na filosofia desde a antiguidade, incluindo um famoso mito contado nos escritos de Platão.",
    "Pesquisas sugerem que simplesmente ter um parceiro em quem você pode confiar está associado a uma maior resiliência durante os momentos mais estressantes da vida.",
    "Os peixes-anjo-francês estão entre as espécies que os biólogos observaram viajando e defendendo o território como pares fiéis e cooperativos.",
    "Estudos sugerem que o hábito do início do relacionamento de idealizar um parceiro, dentro de certos limites, pode de fato ajudar os casais a se manterem satisfeitos ao longo do tempo.",
    "O aperto de mão e o beijo como cumprimentos têm raízes históricas profundas, com o beijo romântico aparecendo em muitas culturas antigas.",
    "Pesquisas sugerem que casais que reservam tempo para o lazer compartilhado, mesmo em breves momentos, relatam se sentir mais próximos e mais como uma equipe.",
    "Alguns cientistas acreditam que a capacidade humana universal de amar pode ser uma das ferramentas mais poderosas da evolução para a cooperação e a sobrevivência.",
    "Estudos sugerem que sentir-se seguro em um relacionamento liberta as pessoas para serem mais aventureiras e confiantes no resto de suas vidas.",
    "A tradição da poesia de amor remonta a milhares de anos, com alguns dos mais antigos poemas de amor conhecidos escritos em antigas tábuas de argila.",
    "Pesquisas sugerem que os parceiros costumam se sentir mais amados não durante gestos dramáticos, mas em pequenos e constantes momentos de atenção e cuidado.",
    "Certas espécies de coruja formam vínculos de casal duradouros e cooperam de perto para criar os filhotes, dividindo as tarefas de caça e de ninho.",
    "Estudos sugerem que casais que mantêm amizades e interesses individuais, ao lado do relacionamento, tendem a relatar uma felicidade de longo prazo maior juntos.",
    "O véu usado por algumas noivas tem origens antigas, aparecendo em várias culturas como símbolo de modéstia, mistério ou proteção.",
    "Pesquisas sugerem que a experiência do encantamento, como assistir a um pôr do sol juntos, pode aprofundar o senso de conexão e de significado compartilhado de um casal.",
    "Muitas culturas têm tradições populares sobre amuletos e fichas do amor, refletindo um desejo humano atemporal de atrair e manter o afeto.",
    "Estudos sugerem que a responsividade, a sensação de que o seu parceiro realmente percebe e se importa com as suas necessidades, é central para sentir-se profundamente amado.",
    "A ideia de comemorar um aniversário de casamento com presentes específicos, como papel ou ouro para certos anos, se desenvolveu gradualmente ao longo dos últimos séculos.",
    "Pesquisas sugerem que até imaginar momentos futuros com um parceiro pode fortalecer o compromisso presente e a motivação para cuidar do relacionamento.",
    "Alguns pinguins-macaroni e outras aves marinhas se reencontram com o mesmo parceiro a cada época de reprodução, depois de passarem meses separados no mar.",
    "Estudos sugerem que o simples ato de dizer 'obrigado' a um parceiro pode desencadear um ciclo positivo de apreço e generosidade.",
    "A palavra 'aconchego' pode soar moderna, mas os humanos buscam o conforto do contato físico próximo desde os primeiros momentos de nossa espécie.",
    "Pesquisas sugerem que casais que veem os desafios como problemas compartilhados a serem resolvidos, e não como falhas pessoais, tendem a se fortalecer através das dificuldades.",
  ],
  quotes: [
    { text: "Sejam do que forem feitas as nossas almas, a dele e a minha são iguais.", author: "Emily Brontë" },
    { text: "Você sabe que está apaixonado quando não consegue dormir porque a realidade finalmente está melhor do que os seus sonhos.", author: "Dr. Seuss" },
    { text: "O amor é composto de uma única alma habitando dois corpos.", author: "Aristóteles" },
    { text: "A melhor coisa a que se agarrar na vida é um ao outro.", author: "Audrey Hepburn" },
    { text: "Estamos mais vivos quando estamos apaixonados.", author: "John Updike" },
    { text: "O amor é aquela condição na qual a felicidade de outra pessoa é essencial para a sua.", author: "Robert A. Heinlein" },
    { text: "Amar e ser amado é sentir o sol dos dois lados.", author: "David Viscott" },
    { text: "Não há remédio para o amor a não ser amar mais.", author: "Henry David Thoreau" },
    { text: "O amor não consiste em olhar um para o outro, mas em olhar juntos na mesma direção.", author: "Antoine de Saint-Exupéry" },
    { text: "Se eu sei o que é o amor, é por sua causa.", author: "Hermann Hesse" },
    { text: "A maior felicidade da vida é a convicção de que somos amados.", author: "Victor Hugo" },
    { text: "O amor é a amizade que pegou fogo.", author: "Ann Landers" },
    { text: "Onde há amor, há vida.", author: "Mahatma Gandhi" },
    { text: "Ser profundamente amado por alguém lhe dá força, enquanto amar alguém profundamente lhe dá coragem.", author: "Lao Tzu" },
    { text: "O amor é quando a felicidade da outra pessoa é mais importante do que a sua.", author: "H. Jackson Brown Jr." },
    { text: "O coração tem razões que a razão desconhece.", author: "Blaise Pascal" },
    { text: "Um casamento bem-sucedido exige apaixonar-se muitas vezes, sempre pela mesma pessoa.", author: "Mignon McLaughlin" },
    { text: "Amamos com um amor que era mais do que amor.", author: "Edgar Allan Poe" },
    { text: "Mas as coisas mais belas do mundo não podem ser vistas nem mesmo tocadas, elas precisam ser sentidas com o coração.", author: "Helen Keller" },
    { text: "Amar não é encontrar alguém com quem viver. É encontrar alguém sem quem você não consegue viver.", author: "Rafael Ortiz" },
    { text: "O amor não reconhece barreiras. Ele pula obstáculos, salta cercas, atravessa muros para chegar ao seu destino cheio de esperança.", author: "Maya Angelou" },
    { text: "O amor é um desejo irresistível de ser irresistivelmente desejado.", author: "Robert Frost" },
    { text: "Você não se casa com alguém com quem pode viver, você se casa com a pessoa sem quem não consegue viver.", author: "Desconhecido" },
    { text: "O curso do amor verdadeiro nunca foi tranquilo.", author: "William Shakespeare" },
    { text: "Ame a todos, confie em poucos, não faça mal a ninguém.", author: "William Shakespeare" },
    { text: "O amor não enxerga com os olhos, mas com a mente.", author: "William Shakespeare" },
    { text: "Encontrei aquele a quem a minha alma ama.", author: "Cântico dos Cânticos" },
    { text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.", author: "1 Coríntios 13:4" },
    { text: "Ao toque do amor, todos se tornam poetas.", author: "Platão" },
    { text: "Dar amor é, em si mesmo, uma educação.", author: "Eleanor Roosevelt" },
    { text: "O amor é a flor que você precisa deixar crescer.", author: "John Lennon" },
    { text: "Tudo de que você precisa é amor.", author: "John Lennon" },
    { text: "O amor existe ou não existe. Amor raso não é amor de jeito nenhum.", author: "Toni Morrison" },
    { text: "O amor tira as máscaras que tememos não poder viver sem e sabemos que não podemos viver dentro.", author: "James Baldwin" },
    { text: "O amor é um fruto que está em estação o tempo todo e ao alcance de toda mão.", author: "Madre Teresa" },
    { text: "Espalhe amor por onde você for. Que ninguém jamais venha até você sem sair mais feliz.", author: "Madre Teresa" },
    { text: "Só podemos aprender a amar amando.", author: "Iris Murdoch" },
    { text: "O amor não é algo que você encontra. O amor é algo que encontra você.", author: "Loretta Young" },
    { text: "A arte de amar é, em grande parte, a arte da persistência.", author: "Albert Ellis" },
    { text: "Amar, de qualquer forma, é tornar-se vulnerável.", author: "C. S. Lewis" },
    { text: "O amor não é um sentimento afetuoso, mas um desejo constante pelo bem maior da pessoa amada.", author: "C. S. Lewis" },
    { text: "O amor é o todo. Nós somos apenas pedaços.", author: "Rumi" },
    { text: "A sua tarefa não é buscar o amor, mas apenas buscar e encontrar todas as barreiras dentro de você que você construiu contra ele.", author: "Rumi" },
    { text: "Deixe que a beleza do que você ama seja o que você faz.", author: "Rumi" },
    { text: "O amor é a ponte entre você e tudo.", author: "Rumi" },
    { text: "A gravidade não é responsável por as pessoas se apaixonarem.", author: "Albert Einstein" },
    { text: "O amor consiste nisto: que duas solidões protejam, toquem e saúdem uma à outra.", author: "Rainer Maria Rilke" },
    { text: "Uma vez que você tenha aprendido a amar, terá aprendido a viver.", author: "Desconhecido" },
    { text: "O amor é composto de muitas coisas, mas sua base é a amizade e a confiança.", author: "Desconhecido" },
    { text: "Quando você ama alguém, você ama a pessoa como ela é, e não como gostaria que ela fosse.", author: "Liev Tolstói" },
    { text: "Ele desceu, tentando não olhar demais para ela, como se fosse o sol, e mesmo assim a via, como ao sol, sem precisar olhar.", author: "Liev Tolstói" },
    { text: "Duvide que as estrelas são fogo; duvide que o sol se move; duvide que a verdade seja mentira; mas nunca duvide do meu amor.", author: "William Shakespeare" },
    { text: "Como eu te amo? Deixe-me contar as maneiras.", author: "Elizabeth Barrett Browning" },
    { text: "O amor é anterior à vida, posterior à morte, princípio da criação e o expoente da respiração.", author: "Emily Dickinson" },
    { text: "Que o amor é tudo o que existe é tudo o que sabemos sobre o amor.", author: "Emily Dickinson" },
    { text: "Se você viver até os cem, eu quero viver até os cem menos um dia, para que eu nunca tenha que viver sem você.", author: "A. A. Milne" },
    { text: "O amor é uma tela fornecida pela natureza e bordada pela imaginação.", author: "Voltaire" },
    { text: "As coisas mais belas e melhores deste mundo não podem ser vistas nem mesmo ouvidas, mas precisam ser sentidas com o coração.", author: "Helen Keller" },
    { text: "Uma flor não desabrocha sem o sol, e o ser humano não vive sem o amor.", author: "Max Müller" },
    { text: "O amor é como o vento, você não pode vê-lo, mas pode senti-lo.", author: "Nicholas Sparks" },
    { text: "A simples falta dela é mais para mim do que a presença dos outros.", author: "Edward Thomas" },
    { text: "Eu preferiria compartilhar uma vida com você a enfrentar todas as eras deste mundo sozinho.", author: "J. R. R. Tolkien" },
    { text: "O amor é a chave-mestra que abre os portões da felicidade.", author: "Oliver Wendell Holmes" },
    { text: "Somos moldados e formados por aquilo que amamos.", author: "Johann Wolfgang von Goethe" },
    { text: "O amor e a tosse não podem ser escondidos.", author: "George Herbert" },
    { text: "Duas pessoas amam, ao passar o mundo, uma à outra.", author: "Desconhecido" },
    { text: "O amor faz a sua alma sair rastejando do seu esconderijo.", author: "Zora Neale Hurston" },
    { text: "Há sempre alguma loucura no amor. Mas há também sempre alguma razão na loucura.", author: "Friedrich Nietzsche" },
    { text: "O amor é a única força capaz de transformar um inimigo em amigo.", author: "Martin Luther King Jr." },
    { text: "Precisamos desenvolver e manter a capacidade de perdoar.", author: "Martin Luther King Jr." },
    { text: "A maneira de amar qualquer coisa é perceber que ela pode ser perdida.", author: "G. K. Chesterton" },
    { text: "Amar nunca é uma perda de tempo.", author: "Astrid Alauda" },
    { text: "O amor é a voz sob todos os silêncios, a esperança que não tem oposto no medo.", author: "E. E. Cummings" },
    { text: "Eu carrego o seu coração comigo. Eu o carrego no meu coração.", author: "E. E. Cummings" },
    { text: "O amor cresce dando. O amor que damos é o único amor que guardamos.", author: "Elbert Hubbard" },
    { text: "Amar não é nada. Ser amado é algo. Mas amar e ser amado, isso é tudo.", author: "T. Tolis" },
    { text: "O amor plantou uma rosa, e o mundo ficou doce.", author: "Katharine Lee Bates" },
    { text: "O amor é a expansão de duas naturezas de tal modo que cada uma inclui a outra.", author: "Felix Adler" },
    { text: "Diga-me quem você ama, e eu lhe direi quem você é.", author: "Houssaye" },
    { text: "Onde você costumava estar, há um buraco no mundo, ao redor do qual me vejo caminhando o tempo todo durante o dia.", author: "Edna St. Vincent Millay" },
  ],
};
