import type { Locale } from '@/i18n/request';

// Localized UI chrome for the blog (nav label, headings, buttons). English is
// the fallback for any unknown locale.
export interface BlogUi {
  nav: string;
  indexTitle: string;
  indexSubtitle: string;
  readArticle: string;
  minRead: string;
  contents: string;
  tryNext: string;
  faqHeading: string;
  keepReading: string;
  published: string;
  updated: string;
  share: string;
  allArticles: string;
}

export const blogUi: Record<Locale, BlogUi> = {
  en: {
    nav: 'Blog',
    indexTitle: 'The LoveCalcs Blog',
    indexSubtitle: 'Playful, honest reads on love, attraction, and compatibility.',
    readArticle: 'Read article',
    minRead: 'min read',
    contents: 'Contents',
    tryNext: 'Try these next',
    faqHeading: 'Frequently asked questions',
    keepReading: 'Keep reading',
    published: 'Published',
    updated: 'Updated',
    share: 'Share',
    allArticles: 'All articles',
  },
  es: {
    nav: 'Blog',
    indexTitle: 'El blog de LoveCalcs',
    indexSubtitle: 'Lecturas divertidas y honestas sobre el amor, la atracción y la compatibilidad.',
    readArticle: 'Leer artículo',
    minRead: 'min de lectura',
    contents: 'Contenido',
    tryNext: 'Prueba esto ahora',
    faqHeading: 'Preguntas frecuentes',
    keepReading: 'Sigue leyendo',
    published: 'Publicado',
    updated: 'Actualizado',
    share: 'Compartir',
    allArticles: 'Todos los artículos',
  },
  fr: {
    nav: 'Blog',
    indexTitle: 'Le blog LoveCalcs',
    indexSubtitle: "Des lectures ludiques et sincères sur l'amour, l'attirance et la compatibilité.",
    readArticle: "Lire l'article",
    minRead: 'min de lecture',
    contents: 'Sommaire',
    tryNext: 'À essayer ensuite',
    faqHeading: 'Questions fréquentes',
    keepReading: 'À lire aussi',
    published: 'Publié',
    updated: 'Mis à jour',
    share: 'Partager',
    allArticles: 'Tous les articles',
  },
  de: {
    nav: 'Blog',
    indexTitle: 'Der LoveCalcs-Blog',
    indexSubtitle: 'Verspielte, ehrliche Beiträge über Liebe, Anziehung und Kompatibilität.',
    readArticle: 'Artikel lesen',
    minRead: 'Min. Lesezeit',
    contents: 'Inhalt',
    tryNext: 'Das könnte dich auch interessieren',
    faqHeading: 'Häufige Fragen',
    keepReading: 'Weiterlesen',
    published: 'Veröffentlicht',
    updated: 'Aktualisiert',
    share: 'Teilen',
    allArticles: 'Alle Artikel',
  },
  it: {
    nav: 'Blog',
    indexTitle: 'Il blog di LoveCalcs',
    indexSubtitle: 'Letture leggere e sincere su amore, attrazione e compatibilità.',
    readArticle: "Leggi l'articolo",
    minRead: 'min di lettura',
    contents: 'Indice',
    tryNext: 'Prova anche questi',
    faqHeading: 'Domande frequenti',
    keepReading: 'Continua a leggere',
    published: 'Pubblicato',
    updated: 'Aggiornato',
    share: 'Condividi',
    allArticles: 'Tutti gli articoli',
  },
  pt: {
    nav: 'Blog',
    indexTitle: 'O blog da LoveCalcs',
    indexSubtitle: 'Leituras leves e sinceras sobre amor, atração e compatibilidade.',
    readArticle: 'Ler artigo',
    minRead: 'min de leitura',
    contents: 'Conteúdo',
    tryNext: 'Experimente agora',
    faqHeading: 'Perguntas frequentes',
    keepReading: 'Continue lendo',
    published: 'Publicado',
    updated: 'Atualizado',
    share: 'Compartilhar',
    allArticles: 'Todos os artigos',
  },
  ru: {
    nav: 'Блог',
    indexTitle: 'Блог LoveCalcs',
    indexSubtitle: 'Лёгкие и честные статьи о любви, влечении и совместимости.',
    readArticle: 'Читать статью',
    minRead: 'мин чтения',
    contents: 'Содержание',
    tryNext: 'Попробуйте дальше',
    faqHeading: 'Частые вопросы',
    keepReading: 'Читать дальше',
    published: 'Опубликовано',
    updated: 'Обновлено',
    share: 'Поделиться',
    allArticles: 'Все статьи',
  },
  zh: {
    nav: '博客',
    indexTitle: 'LoveCalcs 博客',
    indexSubtitle: '关于爱情、吸引力与契合度的轻松而真诚的文章。',
    readArticle: '阅读文章',
    minRead: '分钟阅读',
    contents: '目录',
    tryNext: '接下来试试',
    faqHeading: '常见问题',
    keepReading: '继续阅读',
    published: '发布于',
    updated: '更新于',
    share: '分享',
    allArticles: '全部文章',
  },
  ja: {
    nav: 'ブログ',
    indexTitle: 'LoveCalcs ブログ',
    indexSubtitle: '恋愛・惹かれ合い・相性についての、楽しくて正直な読み物。',
    readArticle: '記事を読む',
    minRead: '分で読めます',
    contents: '目次',
    tryNext: '次はこちら',
    faqHeading: 'よくある質問',
    keepReading: 'もっと読む',
    published: '公開日',
    updated: '更新日',
    share: 'シェア',
    allArticles: 'すべての記事',
  },
  ar: {
    nav: 'المدونة',
    indexTitle: 'مدونة LoveCalcs',
    indexSubtitle: 'مقالات خفيفة وصادقة عن الحب والانجذاب والتوافق.',
    readArticle: 'اقرأ المقال',
    minRead: 'دقيقة قراءة',
    contents: 'المحتويات',
    tryNext: 'جرّب هذه التالية',
    faqHeading: 'الأسئلة الشائعة',
    keepReading: 'تابع القراءة',
    published: 'نُشر',
    updated: 'حُدّث',
    share: 'مشاركة',
    allArticles: 'كل المقالات',
  },
  hi: {
    nav: 'ब्लॉग',
    indexTitle: 'LoveCalcs ब्लॉग',
    indexSubtitle: 'प्यार, आकर्षण और अनुकूलता पर मज़ेदार और ईमानदार लेख।',
    readArticle: 'लेख पढ़ें',
    minRead: 'मिनट पढ़ें',
    contents: 'विषय-सूची',
    tryNext: 'आगे ये आज़माएँ',
    faqHeading: 'अक्सर पूछे जाने वाले सवाल',
    keepReading: 'पढ़ते रहें',
    published: 'प्रकाशित',
    updated: 'अपडेटेड',
    share: 'शेयर करें',
    allArticles: 'सभी लेख',
  },
};
